export const colors_ua = [
    {word: "оксамитовий", translation: "velvety", guessed: false, example: "The fabric is velvety"},
    {word: "коричневий", translation: "brown", guessed: false, example: "She has brown hair"},
    {word: "золотий", translation: "gold", guessed: false, example: "She wore gold earrings"},
    {word: "синюватий", translation: "bluish", guessed: false, example: "The sky looked bluish at dusk"},
    {word: "білий", translation: "white", guessed: false, example: "She wore a white dress"},
    {word: "білуватий", translation: "whitish", guessed: false, example: "The paint is whitish"},
    {word: "фіолетовий", translation: "violet", guessed: false, example: "She wore a violet dress"},
    {word: "жовтий", translation: "yellow", guessed: false, example: "She wore a yellow dress"},
    {word: "червоний", translation: "red", guessed: false, example: "She wore a red dress"},
    {word: "рудий", translation: "red", guessed: false, example: "He has red hair"},
    {word: "синій/блакитний", translation: "blue", guessed: false, example: "She wore a blue dress"},
    {word: "зелений", translation: "green", guessed: false, example: "She wore a green dress"},
    {word: "зеленкуватий", translation: "greenish", guessed: false, example: "The water looked greenish"},
    {word: "сірий", translation: "grey", guessed: false, example: "The sky is grey"},
    {word: "чорний", translation: "black", guessed: false, example: "She wore a black dress"},
    {word: "чорно-білий", translation: "black and white", guessed: false, example: "The photo was black and white"},
    {word: "бежевий", translation: "beige", guessed: false, example: "She wore a beige coat"},
    {word: "помаранчевий", translation: "orange", guessed: false, example: "She wore an orange shirt"},
    {word: "темно-синій", translation: "navy blue", guessed: false, example: "She wore a navy blue dress"},
    {word: "рожевий", translation: "pink", guessed: false, example: "She wore a pink dress"},
    {word: "пурпурний", translation: "purple", guessed: false, example: "She wore a purple dress"},
    {word: "червонуватий", translation: "reddish", guessed: false, example: "The leaves are reddish"},
    {word: "срібний", translation: "silver", guessed: false, example: "She wore silver jewelry"},
    {word: "бірюзовий", translation: "turquoise", guessed: false, example: "She wore a turquoise dress"}
];
