export const communication = [
    {word: "мета", translation: "purpose", guessed: false, example: "She found a new purpose in life"},
    {word: "інформація", translation: "information", guessed: false, example: "They gathered all the information they could"},
    {word: "повідомлення", translation: "report", guessed: false, example: "The report was detailed and informative"},
    {word: "новини", translation: "news", guessed: false, example: "The news was spread quickly"},
    {word: "чутки", translation: "rumour", guessed: false, example: "The rumour was completely unfounded"},
    {word: "правда", translation: "truth", guessed: false, example: "The truth eventually came to light"},
    {word: "брехня", translation: "lie", guessed: false, example: "A lie can cause a lot of damage"},
    {word: "мова", translation: "language", guessed: false, example: "Learning a new language is challenging"},
    {word: "слово", translation: "word", guessed: false, example: "Each word has its own meaning"},
    {word: "іноземна мова", translation: "foreign language", guessed: false, example: "She studied a foreign language in school"},
    {word: "рідна мова", translation: "mother tongue", guessed: false, example: "He spoke in his mother tongue at home"},
    {word: "пропозиція", translation: "sentence", guessed: false, example: "The sentence was grammatically correct"},
    {word: "словосполучення", translation: "phrase", guessed: false, example: "She repeated the phrase to remember it"},
    {word: "значення", translation: "meaning", guessed: false, example: "The meaning of the word was unclear"},
    {word: "вимова", translation: "pronunciation", guessed: false, example: "Her pronunciation was flawless"},
    {word: "наголос", translation: "stress", guessed: false, example: "The stress on the syllable changed the meaning"},
    {word: "наголос", translation: "accent", guessed: false, example: "His accent was strong and distinctive"},
    {word: "бесіда", translation: "conversation", guessed: false, example: "They had a long conversation about the future"},
    {word: "питання", translation: "question", guessed: false, example: "She asked a difficult question"},
    {word: "відповідь", translation: "answer", guessed: false, example: "His answer was thoughtful and considered"},
    {word: "порада", translation: "advice", guessed: false, example: "She gave him good advice"},
    {word: "попередження", translation: "warning", guessed: false, example: "The warning was clear and urgent"},
    {word: "прохання", translation: "request", guessed: false, example: "He made a polite request"},
    {word: "вимога", translation: "demand", guessed: false, example: "The demand for the product was high"},
    {word: "обіцянка", translation: "promise", guessed: false, example: "She made a promise to always be there"},
    {word: "зауваження", translation: "remark", guessed: false, example: "His remark was taken out of context"},
    {word: "допомога", translation: "help", guessed: false, example: "She offered her help with the project"},
    {word: "асистування", translation: "assistance", guessed: false, example: "They needed assistance to complete the task"},
    {word: "поведінка", translation: "behaviour", guessed: false, example: "His behaviour was exemplary"},
    {word: "ввічливість", translation: "politeness", guessed: false, example: "Politeness is a valuable trait"},
    {word: "вибачення", translation: "apology", guessed: false, example: "He offered a sincere apology"},
    {word: "прощення", translation: "forgiveness", guessed: false, example: "Forgiveness can be difficult but important"},
    {word: "ставлення", translation: "attitude", guessed: false, example: "Her positive attitude was infectious"},
    {word: "причина", translation: "cause", guessed: false, example: "The cause of the fire was unknown"},
    {word: "установлення", translation: "establishment", guessed: false, example: "The establishment of the company was a milestone"},
    {word: "привід", translation: "occasion", guessed: false, example: "It was a special occasion for the family"},
    {word: "зрада", translation: "cheat", guessed: false, example: "He felt betrayed by the cheat"},
    {word: "обставини", translation: "circumstances", guessed: false, example: "The circumstances were beyond their control"},
    {word: "перешкода", translation: "obstacle", guessed: false, example: "The obstacle was difficult to overcome"},
    {word: "знак валюти", translation: "currency sign", guessed: false, example: "The currency sign indicated the price"},
    {word: "розміри", translation: "dimensions", guessed: false, example: "They measured the dimensions of the room"},
    {word: "можливість", translation: "possibility", guessed: false, example: "There is a possibility of rain tomorrow"},
    {word: "шанс", translation: "chance", guessed: false, example: "He took a chance and applied for the job"},
    {word: "вимога", translation: "requirement", guessed: false, example: "Meeting the requirement was essential for success"},
    {word: "зусилля", translation: "effort", guessed: false, example: "Their effort paid off in the end"},
    {word: "готово", translation: "done", guessed: false, example: "The project was finally done"},
    {word: "сумісність", translation: "compatibility", guessed: false, example: "Compatibility is important in a relationship"},
    {word: "сенс", translation: "sense", guessed: false, example: "It made perfect sense to him"},
    {word: "досягнення", translation: "accomplishment", guessed: false, example: "Her accomplishment was celebrated by all"},
    {word: "вимоги", translation: "demands", guessed: false, example: "The job had high demands"},
    {word: "навантаження", translation: "workload", guessed: false, example: "Her workload was heavy this week"},
    {word: "застереження", translation: "cautions", guessed: false, example: "They took all necessary cautions"},
    {word: "неправомірна поведінка", translation: "misconduct", guessed: false, example: "The employee was fired for misconduct"},
    {word: "рішення", translation: "decision", guessed: false, example: "The decision was made after careful consideration"},
    {word: "інсайти", translation: "insights", guessed: false, example: "Her insights were valuable to the discussion"},
    {word: "опитування", translation: "surveys", guessed: false, example: "The surveys revealed interesting results"},
    {word: "залучення", translation: "engagement", guessed: false, example: "Engagement with the audience was high"},
    {word: "замість", translation: "instead", guessed: false, example: "They chose to stay home instead"},
    {word: "навіть", translation: "even", guessed: false, example: "Even he was surprised by the outcome"}
];