export const cosmos_ua = [
    {word: "інопланетянин, позаземне створіння", translation: "alien", guessed: false, example: "The movie featured an alien invasion"},
    {word: "астероїд", translation: "asteroid", guessed: false, example: "An asteroid passed close to Earth"},
    {word: "астронавт", translation: "astronaut", guessed: false, example: "The astronaut landed on the moon"},
    {word: "астроном", translation: "astronomer", guessed: false, example: "The astronomer studied distant stars"},
    {word: "астрономічний", translation: "astronomical", guessed: false, example: "The distances in space are astronomical"},
    {word: "астрономія", translation: "astronomy", guessed: false, example: "Astronomy is the study of celestial objects"},
    {word: "комета", translation: "comet", guessed: false, example: "The comet was visible in the night sky"},
    {word: "сузір'я", translation: "constellation", guessed: false, example: "Orion is a well-known constellation"},
    {word: "космічний", translation: "cosmic", guessed: false, example: "They explored the cosmic mysteries"},
    {word: "космос", translation: "cosmos", guessed: false, example: "The cosmos is vast and endless"},
    {word: "Земля", translation: "Earth", guessed: false, example: "Earth is the third planet from the sun"},
    {word: "землянин", translation: "Earthman", guessed: false, example: "The Earthman traveled to Mars"},
    {word: "літаюча тарілка", translation: "flying saucer", guessed: false, example: "They claimed to see a flying saucer"},
    {word: "галактика", translation: "galaxy", guessed: false, example: "The Milky Way is our galaxy"},
    {word: "тяжіння", translation: "gravitation", guessed: false, example: "Gravitation pulls objects towards Earth"},
    {word: "тяжіння", translation: "gravity", guessed: false, example: "Gravity keeps us grounded"},
    {word: "марсіянин", translation: "Martian", guessed: false, example: "The story was about a Martian invasion"},
    {word: "метеорит", translation: "meteorite", guessed: false, example: "A meteorite landed in the desert"},
    {word: "Місяць", translation: "moon", guessed: false, example: "The moon orbits around Earth"},
    {word: "приземлення на Місяці", translation: "moon landing", guessed: false, example: "The first moon landing was in 1969"},
    {word: "космічний простір", translation: "outer space", guessed: false, example: "Astronauts travel through outer space"},
    {word: "планета", translation: "planet", guessed: false, example: "Mars is a neighboring planet to Earth"},
    {word: "планетарний", translation: "planetary", guessed: false, example: "The planetary system includes many planets"},
    {word: "супутник", translation: "satellite", guessed: false, example: "The satellite orbits the Earth"},
    {word: "зірка, що падає", translation: "shooting star", guessed: false, example: "We saw a shooting star last night"},
    {word: "шатл", translation: "shuttle", guessed: false, example: "The space shuttle launched successfully"},
    {word: "космічна станція", translation: "space base", guessed: false, example: "The space base is in orbit"},
    {word: "космічний політ", translation: "space flight", guessed: false, example: "They prepared for the space flight"},
    {word: "космічний корабель", translation: "spaceship", guessed: false, example: "The spaceship traveled to distant stars"},
    {word: "зірковий", translation: "stellar", guessed: false, example: "They observed stellar formations"},
    {word: "сонце", translation: "sun", guessed: false, example: "The sun is the center of our solar system"},
    {word: "телескоп", translation: "telescope", guessed: false, example: "He used a telescope to view the stars"},
    {word: "земний", translation: "terrestrial", guessed: false, example: "Terrestrial life is found on Earth"},
    {word: "неопізнаний літаючий об'єкт", translation: "unidentified flying object", guessed: false, example: "They saw an unidentified flying object in the sky"},
    {word: "всесвіт", translation: "universe", guessed: false, example: "The universe is vast and mysterious"},
    {word: "невагомість", translation: "weightlessness", guessed: false, example: "Astronauts experience weightlessness in space"},
    {word: "світ", translation: "world", guessed: false, example: "We live in a diverse world"}
]


