export const disasters_ua = [
    {word: "лавина", translation: "avalanche", guessed: false, example: "An avalanche buried the mountain village"},
    {word: "катастрофа", translation: "catastrophe", guessed: false, example: "The earthquake was a major catastrophe"},
    {word: "циклон", translation: "cyclone", guessed: false, example: "A powerful cyclone hit the coast"},
    {word: "сходження з рейок", translation: "derailment", guessed: false, example: "The train derailment caused chaos"},
    {word: "винищення", translation: "destruction", guessed: false, example: "The storm left a trail of destruction"},
    {word: "катастрофа", translation: "disaster", guessed: false, example: "The flood was a terrible disaster"},
    {word: "засуха", translation: "drought", guessed: false, example: "The drought affected many crops"},
    {word: "землетрус", translation: "earthquake", guessed: false, example: "The earthquake shook the city"},
    {word: "екологічний", translation: "ecological", guessed: false, example: "An ecological crisis is unfolding"},
    {word: "катастрофа екологічна", translation: "environmental disaster", guessed: false, example: "The oil spill was an environmental disaster"},
    {word: "епідемія", translation: "epidemic", guessed: false, example: "The epidemic spread quickly"},
    {word: "смертельний", translation: "fatal", guessed: false, example: "The accident was fatal for three people"},
    {word: "вогонь", translation: "fire", guessed: false, example: "The fire burned for hours"},
    {word: "пожежа", translation: "fire", guessed: false, example: "A forest fire destroyed many trees"},
    {word: "пожежна сирена", translation: "fire alarm", guessed: false, example: "The fire alarm rang loudly"},
    {word: "пожежний автомобіль", translation: "fire engine", guessed: false, example: "The fire engine arrived quickly"},
    {word: "пожежник", translation: "firefighter", guessed: false, example: "The firefighter saved many lives"},
    {word: "рятувальник", translation: "first-aid worker", guessed: false, example: "First-aid workers treated the injured"},
    {word: "повінь", translation: "flood", guessed: false, example: "The floodwaters covered the town"},
    {word: "допомога", translation: "help", guessed: false, example: "Emergency help arrived swiftly"},
    {word: "ураган", translation: "hurricane", guessed: false, example: "The hurricane caused widespread damage"},
    {word: "рана", translation: "injury", guessed: false, example: "He had a severe injury from the accident"},
    {word: "рятувальний човен", translation: "lifeboat", guessed: false, example: "The lifeboat saved the stranded sailors"},
    {word: "рятувальне коло", translation: "lifebuoy", guessed: false, example: "He threw a lifebuoy to the drowning person"},
    {word: "рятувальний жилет", translation: "life jacket", guessed: false, example: "Wear a life jacket when on a boat"},
    {word: "рятувальне коло", translation: "life ring", guessed: false, example: "The life ring was used in the rescue"},
    {word: "зниклий", translation: "missing", guessed: false, example: "Several people are still missing"},
    {word: "авіакатастрофа", translation: "plane crash", guessed: false, example: "The plane crash shocked the nation"},
    {word: "порятунок", translation: "rescue", guessed: false, example: "The rescue operation was successful"},
    {word: "рятувальник", translation: "rescuer", guessed: false, example: "The rescuer found the lost hikers"},
    {word: "цілий і здоровий", translation: "safe and sound", guessed: false, example: "Everyone was found safe and sound"},
    {word: "морська катастрофа", translation: "shipwreck", guessed: false, example: "The shipwreck was found after years"},
    {word: "уціліла особа", translation: "survivor", guessed: false, example: "The survivor recounted their ordeal"},
    {word: "загроза", translation: "threat", guessed: false, example: "The storm posed a serious threat"},
    {word: "викликати", translation: "to cause", guessed: false, example: "The flood caused extensive damage"},
    {word: "зійти з рейок", translation: "to derail", guessed: false, example: "The train derailed near the station"},
    {word: "руйнувати", translation: "to devastate", guessed: false, example: "The hurricane devastated the coastal town"},
    {word: "збити літак", translation: "to down a plane", guessed: false, example: "The military managed to down a plane"},
    {word: "розливатись", translation: "to flood", guessed: false, example: "The river overflowed and flooded the fields"},
    {word: "зникнути", translation: "to go missing", guessed: false, example: "The hiker went missing in the mountains"},
    {word: "відбудувати", translation: "to rebuild", guessed: false, example: "They planned to rebuild the damaged homes"},
    {word: "одержати компенсацію", translation: "to receive compensation", guessed: false, example: "Victims will receive compensation soon"},
    {word: "рятувати", translation: "to rescue", guessed: false, example: "Firefighters worked to rescue the trapped people"},
    {word: "торнадо", translation: "tornado", guessed: false, example: "The tornado destroyed everything in its path"},
    {word: "рятувати", translation: "to save", guessed: false, example: "Lifeguards managed to save the swimmer"},
    {word: "залишитись живим", translation: "to survive", guessed: false, example: "They managed to survive the storm"},
    {word: "пережити", translation: "to survive", guessed: false, example: "She survived the earthquake with minor injuries"},
    {word: "трагедія", translation: "tragedy", guessed: false, example: "The accident was a terrible tragedy"},
    {word: "трагічний", translation: "tragic", guessed: false, example: "It was a tragic event for everyone"},
    {word: "вихор", translation: "whirlwind", guessed: false, example: "A whirlwind swept through the valley"},
    {word: "покинутий корпус авто, корабля", translation: "wreck", guessed: false, example: "The wreck of the ship was found"},
    {word: "рештки", translation: "wreckage", guessed: false, example: "The wreckage was scattered over a large area"}
]
