export const emotion = [
    {word: "емоція", translation: "emotion", guessed: false, example: "She couldn't hide her emotion"},
    {word: "почуття", translation: "feeling", guessed: false, example: "He expressed his feelings openly"},
    {word: "задоволення", translation: "pleasure", guessed: false, example: "Reading books gave her great pleasure"},
    {word: "задоволення", translation: "satisfaction", guessed: false, example: "He felt satisfaction after completing the project"},
    {word: "щастя", translation: "happiness", guessed: false, example: "Happiness is often found in simple things"},
    {word: "радість", translation: "joy", guessed: false, example: "The birth of her child brought her immense joy"},
    {word: "сум", translation: "sadness", guessed: false, example: "There was a deep sadness in her eyes"},
    {word: "збудження", translation: "excitement", guessed: false, example: "The excitement in the room was palpable"},
    {word: "страждання", translation: "suffering", guessed: false, example: "The story of their suffering was heartbreaking"},
    {word: "співчуття", translation: "sympathy", guessed: false, example: "She showed great sympathy for their situation"},
    {word: "захоплення", translation: "admiration", guessed: false, example: "He looked at her with admiration"},
    {word: "повага", translation: "respect", guessed: false, example: "Respect is earned through actions"},
    {word: "кохання", translation: "love", guessed: false, example: "Love is a powerful emotion"},
    {word: "дружба", translation: "friendship", guessed: false, example: "Their friendship lasted through the years"},
    {word: "заздрість", translation: "envy", guessed: false, example: "He couldn't hide his envy of her success"},
    {word: "бажання", translation: "wish", guessed: false, example: "She made a wish on a falling star"},
    {word: "намір", translation: "intention", guessed: false, example: "His intention was to help, not hinder"},
    {word: "мрія", translation: "dream", guessed: false, example: "Her dream was to become a writer"},
    {word: "надія", translation: "hope", guessed: false, example: "They never gave up hope"},
    {word: "роздуми", translation: "thoughts", guessed: false, example: "He shared his thoughts on the matter"},
    {word: "ставлення", translation: "opinions", guessed: false, example: "Their opinions differed greatly"},
    {word: "спантеличеність", translation: "confusion", guessed: false, example: "There was confusion about the instructions"},
    {word: "побоювання", translation: "concerns", guessed: false, example: "They expressed their concerns about the project"}
];