export const family_ua = [
    {word: "родина", translation: "family", guessed: false, example: "Family gatherings are always special"},
    {word: "батько", translation: "father", guessed: false, example: "Her father taught her how to ride a bike"},
    {word: "мати", translation: "mother", guessed: false, example: "Her mother baked delicious cookies"},
    {word: "дитина", translation: "child", guessed: false, example: "The child played happily in the park"},
    {word: "сестра", translation: "sister", guessed: false, example: "She has an older sister"},
    {word: "брат", translation: "brother", guessed: false, example: "His brother is a professional athlete"},
    {word: "чоловік", translation: "husband", guessed: false, example: "Her husband surprised her with flowers"},
    {word: "дружина", translation: "wife", guessed: false, example: "His wife is a talented musician"},
    {word: "син", translation: "son", guessed: false, example: "Their son graduated from college"},
    {word: "дочка", translation: "daughter", guessed: false, example: "Their daughter is studying abroad"},
    {word: "весілля", translation: "wedding", guessed: false, example: "The wedding was a beautiful ceremony"},
    {word: "розлучення", translation: "divorce", guessed: false, example: "They decided to get a divorce after many years"},
    {word: "батьки", translation: "parents", guessed: false, example: "Her parents are very supportive"},
    {word: "рідні", translation: "relatives", guessed: false, example: "They invited all their relatives to the party"},
    {word: "дідусь", translation: "grandfather", guessed: false, example: "Her grandfather told fascinating stories"},
    {word: "бабуся", translation: "grandmother", guessed: false, example: "His grandmother makes the best pies"},
    {word: "дядько", translation: "uncle", guessed: false, example: "Her uncle works as a firefighter"},
    {word: "тітка", translation: "aunt", guessed: false, example: "His aunt lives in a different city"},
    {word: "племінник", translation: "nephew", guessed: false, example: "She bought a gift for her nephew's birthday"},
    {word: "племінниця", translation: "niece", guessed: false, example: "His niece loves to draw and paint"},
    {word: "двоюрідний брат/сестра", translation: "cousin", guessed: false, example: "Her cousin is visiting from abroad"},
    {word: "онук", translation: "grandson", guessed: false, example: "He is proud of his grandson's achievements"},
    {word: "онука", translation: "granddaughter", guessed: false, example: "They are excited to see their granddaughter"},
    {word: "відносини", translation: "relations", guessed: false, example: "They have good relations with their neighbors"},
    {word: "друг", translation: "friend", guessed: false, example: "She met her best friend at school"},
    {word: "колега", translation: "colleague", guessed: false, example: "His colleague helped him with the project"},
    {word: "роботодавець", translation: "employer", guessed: false, example: "Her employer offered her a promotion"},
    {word: "найманий працівник", translation: "employee", guessed: false, example: "The company values its employees"},
    {word: "знайомство", translation: "acquaintance", guessed: false, example: "She made a new acquaintance at the party"}
];