export const food = [
    {word: "їжа", translation: "meals", guessed: false, example: "They enjoyed their meals together as a family"},
    {word: "сніданок", translation: "breakfast", guessed: false, example: "Breakfast is the most important meal of the day"},
    {word: "пізній сніданок", translation: "lunch", guessed: false, example: "They had a light lunch at the cafe"},
    {word: "обід", translation: "dinner", guessed: false, example: "Dinner was served at eight o'clock"},
    {word: "вечеря", translation: "supper", guessed: false, example: "Supper was a simple affair"},
    {word: "апетит", translation: "appetite", guessed: false, example: "He had a healthy appetite after the workout"},
    {word: "напій", translation: "drink", guessed: false, example: "She poured herself a drink of water"},
    {word: "чай", translation: "tea", guessed: false, example: "They enjoyed a cup of tea in the afternoon"},
    {word: "кава", translation: "coffee", guessed: false, example: "He needed his morning coffee to wake up"},
    {word: "молоко", translation: "milk", guessed: false, example: "She added milk to her cereal"},
    {word: "сік", translation: "juice", guessed: false, example: "Fresh orange juice was served at breakfast"},
    {word: "вино", translation: "wine", guessed: false, example: "They toasted with a glass of wine"},
    {word: "солодощі", translation: "sweets", guessed: false, example: "The children were given sweets as a treat"},
    {word: "шоколад", translation: "chocolate", guessed: false, example: "She loved dark chocolate"},
    {word: "печиво", translation: "biscuit", guessed: false, example: "He enjoyed a biscuit with his tea"},
    {word: "торт", translation: "cake", guessed: false, example: "The birthday cake was delicious"},
    {word: "пиріг", translation: "pie", guessed: false, example: "The apple pie was homemade"},
    {word: "варення", translation: "jam", guessed: false, example: "They spread jam on their toast"},
    {word: "цукор", translation: "sugar", guessed: false, example: "She added sugar to her coffee"},
    {word: "мед", translation: "honey", guessed: false, example: "Honey is a natural sweetener"},
    {word: "ковбаса", translation: "sausage", guessed: false, example: "They grilled sausages for the barbecue"},
    {word: "сир", translation: "cheese", guessed: false, example: "The cheese platter had a variety of flavors"},
    {word: "магазин", translation: "shop", guessed: false, example: "They went to the shop to buy groceries"},
    {word: "товари", translation: "goods", guessed: false, example: "The store had a wide variety of goods"},
    {word: "риба", translation: "fish", guessed: false, example: "They had fish for dinner"},
    {word: "консерви", translation: "canned goods", guessed: false, example: "The pantry was stocked with canned goods"},
    {word: "вершкове масло", translation: "butter", guessed: false, example: "She spread butter on her toast"},
    {word: "рослинна олія", translation: "vegetable oil", guessed: false, example: "She used vegetable oil for cooking"},
    {word: "хліб", translation: "bread", guessed: false, example: "The bread was freshly baked"},
    {word: "ємність", translation: "capacity", guessed: false, example: "The room capacity was 50 people"},
    {word: "м'ясний магазин", translation: "butcher shop", guessed: false, example: "He bought steaks from the butcher’s"},
    {word: "молочний відділ", translation: "dairy", guessed: false, example: "They got milk and cheese from the dairy"}
];