export const house = [
    {word: "адреса", translation: "address", guessed: false, example: "Please send the package to this address"},
    {word: "будинок", translation: "house", guessed: false, example: "They moved into a new house last year"},
    {word: "будівля", translation: "building", guessed: false, example: "The building is over a hundred years old"},
    {word: "вулиця", translation: "street", guessed: false, example: "Their house is on a quiet street"},
    {word: "площа", translation: "square", guessed: false, example: "The town square was decorated for the festival"},
    {word: "квартира", translation: "apartment", guessed: false, example: "She lives in a small apartment downtown"},
    {word: "поверх", translation: "floor", guessed: false, example: "Their office is on the third floor"},
    {word: "двір", translation: "yard", guessed: false, example: "The children played in the yard all afternoon"},
    {word: "паркан", translation: "fence", guessed: false, example: "They built a new fence around their property"},
    {word: "дах", translation: "roof", guessed: false, example: "The roof was damaged in the storm"},
    {word: "стіна", translation: "wall", guessed: false, example: "They painted the wall a bright color"},
    {word: "підлога", translation: "floor", guessed: false, example: "She cleaned the floor until it shone"},
    {word: "стеля", translation: "ceiling", guessed: false, example: "The ceiling was high and vaulted"},
    {word: "вікно", translation: "window", guessed: false, example: "She looked out the window at the rain"},
    {word: "кут", translation: "corner", guessed: false, example: "They placed the table in the corner of the room"},
    {word: "сходи", translation: "staircase", guessed: false, example: "The grand staircase was a focal point of the house"},
    {word: "сходовий майданчик", translation: "landing", guessed: false, example: "The landing was decorated with plants"},
    {word: "пральня", translation: "laundry", guessed: false, example: "They did their laundry every weekend"},
    {word: "ліфт", translation: "lift", guessed: false, example: "They took the lift to the top floor"},
    {word: "двері", translation: "door", guessed: false, example: "She knocked on the door and waited"},
    {word: "дзвінок", translation: "bell", guessed: false, example: "The doorbell rang loudly"},
    {word: "замок", translation: "lock", guessed: false, example: "He turned the key in the lock"},
    {word: "ключ", translation: "key", guessed: false, example: "She misplaced her house key"},
    {word: "кімната", translation: "room", guessed: false, example: "The room was filled with sunlight"},
    {word: "передпокій", translation: "entrance hall", guessed: false, example: "The entrance hall was spacious and welcoming"},
    {word: "кухня", translation: "kitchen", guessed: false, example: "She loves to cook in her new kitchen"},
    {word: "ванна", translation: "bathroom", guessed: false, example: "The bathroom was recently renovated"},
    {word: "туалет", translation: "toilet", guessed: false, example: "The toilet is down the hall"},
    {word: "спальня", translation: "bedroom", guessed: false, example: "The bedroom was decorated in soft colors"},
    {word: "меблі", translation: "furniture", guessed: false, example: "They bought new furniture for the living room"},
    {word: "стіл", translation: "table", guessed: false, example: "The table was set for dinner"},
    {word: "стілець", translation: "chair", guessed: false, example: "He pulled out a chair and sat down"},
    {word: "крісло", translation: "armchair", guessed: false, example: "She sat in a comfortable armchair"},
    {word: "ліжко", translation: "bed", guessed: false, example: "The bed was soft and inviting"},
    {word: "диван", translation: "sofa", guessed: false, example: "They lounged on the sofa watching TV"},
    {word: "килим", translation: "carpet", guessed: false, example: "The carpet was plush and warm underfoot"},
    {word: "дзеркало", translation: "mirror", guessed: false, example: "She checked her reflection in the mirror"},
    {word: "холодильник", translation: "fridge", guessed: false, example: "The fridge was stocked with fresh food"},
    {word: "порохотяг", translation: "vacuum cleaner", guessed: false, example: "She used the vacuum cleaner to clean the carpets"},
    {word: "пральна машина", translation: "washing machine", guessed: false, example: "The washing machine was very efficient"},
    {word: "плита", translation: "stove", guessed: false, example: "She cooked dinner on the new stove"},
    {word: "стіна", translation: "wall", guessed: false, example: "The wall was painted a bright color"},
    {word: "дно", translation: "bottom", guessed: false, example: "The bottom of the ocean is deep and dark"},
    {word: "праска", translation: "iron", guessed: false, example: "He used the iron to smooth out his shirt"},
    {word: "місто", translation: "city", guessed: false, example: "The city was bustling with activity"},
    {word: "маленьке місто", translation: "town", guessed: false, example: "The town had a quaint charm"},
    {word: "вулиця", translation: "street", guessed: false, example: "They walked down the busy street"},
    {word: "площа", translation: "square", guessed: false, example: "The square was filled with people"},
    {word: "будівля", translation: "building", guessed: false, example: "The building was an architectural marvel"},
    {word: "готель", translation: "hotel", guessed: false, example: "They stayed at a luxurious hotel"},
    {word: "поліція", translation: "police", guessed: false, example: "The police maintained order"},
    {word: "лікарня", translation: "hospital", guessed: false, example: "She was taken to the hospital after the accident"},
    {word: "церква", translation: "church", guessed: false, example: "The church was a historic landmark"},
    {word: "ринок", translation: "market", guessed: false, example: "The market was bustling with vendors"},
    {word: "ресторан", translation: "restaurant", guessed: false, example: "They had dinner at a fancy restaurant"},
    {word: "цирк", translation: "circus", guessed: false, example: "The circus entertained the crowd"},
    {word: "театр", translation: "theatre", guessed: false, example: "They went to the theatre to see a play"},
    {word: "кінотеатр", translation: "cinema", guessed: false, example: "The cinema was showing the latest blockbuster"},
];