export const human = [
    {word: "людина", translation: "human", guessed: false, example: "Every human being deserves respect and dignity"},
    {word: "чоловік", translation: "man", guessed: false, example: "The man helped the elderly lady cross the street"},
    {word: "жінка", translation: "woman", guessed: false, example: "The woman spoke passionately about her cause"},
    {word: "дитина", translation: "child", guessed: false, example: "The child played happily in the park"},
    {word: "дівчинка", translation: "girl", guessed: false, example: "The girl sang beautifully at the talent show"},
    {word: "хлопчик", translation: "boy", guessed: false, example: "The boy rode his bike around the neighborhood"},
    {word: "юність", translation: "youth", guessed: false, example: "Youth is a time of exploration and growth"},
    {word: "дорослий", translation: "grown-up", guessed: false, example: "He felt like a grown-up after getting his first job"},
    {word: "національність", translation: "nationality", guessed: false, example: "She is proud of her nationality and heritage"},
    {word: "тіло", translation: "body", guessed: false, example: "Exercise is important for maintaining a healthy body"},
    {word: "вага", translation: "weight", guessed: false, example: "She was concerned about her weight and diet"},
    {word: "кістка", translation: "bone", guessed: false, example: "He broke a bone in his arm while playing sports"},
    {word: "м'язи", translation: "muscle", guessed: false, example: "Lifting weights helps to build muscle"},
    {word: "кров", translation: "blood", guessed: false, example: "Blood is essential for transporting oxygen in the body"},
    {word: "шкіра", translation: "skin", guessed: false, example: "She applied lotion to keep her skin soft and smooth"},
    {word: "волосся", translation: "hair", guessed: false, example: "Her hair was long and shiny"},
    {word: "голова", translation: "head", guessed: false, example: "He nodded his head in agreement"},
    {word: "шия", translation: "neck", guessed: false, example: "She wore a scarf around her neck to keep warm"},
    {word: "груди", translation: "chest", guessed: false, example: "His chest heaved as he caught his breath"},
    {word: "спина", translation: "back", guessed: false, example: "She had a tattoo on her lower back"},
    {word: "живіт", translation: "stomach", guessed: false, example: "He complained of a stomach ache after eating too much"},
    {word: "нога", translation: "leg", guessed: false, example: "She injured her leg while hiking"},
    {word: "стопа", translation: "foot", guessed: false, example: "His foot was sore after walking all day"},
    {word: "рука", translation: "arm", guessed: false, example: "He flexed his arm muscles"},
    {word: "палець", translation: "finger", guessed: false, example: "He cut his finger while chopping vegetables"},
    {word: "лікоть", translation: "elbow", guessed: false, example: "She leaned on her elbow while reading a book"},
    {word: "коліно", translation: "knee", guessed: false, example: "He fell and scraped his knee"},
    {word: "талія", translation: "waist", guessed: false, example: "The dress fit snugly around her waist"},
    {word: "п'ята", translation: "heel", guessed: false, example: "Her heel was blistered from the new shoes"},
    {word: "ніготь", translation: "nail", guessed: false, example: "She painted her nails a bright color"},
    {word: "обличчя", translation: "face", guessed: false, example: "Her face lit up with a smile"},
    {word: "око", translation: "eye", guessed: false, example: "He has blue eyes"},
    {word: "вухо", translation: "ear", guessed: false, example: "She wore earrings in her left ear"},
    {word: "лоб", translation: "forehead", guessed: false, example: "He wiped the sweat from his forehead"},
    {word: "щока", translation: "cheek", guessed: false, example: "She blushed and her cheeks turned red"},
    {word: "рот", translation: "mouth", guessed: false, example: "He opened his mouth to speak"},
    {word: "губа", translation: "lip", guessed: false, example: "She applied lipstick to her lips"},
    {word: "зуб", translation: "tooth", guessed: false, example: "He brushed his teeth twice a day"},
    {word: "язик", translation: "tongue", guessed: false, example: "She bit her tongue to stop herself from speaking"},
    {word: "ніс", translation: "nose", guessed: false, example: "He has a sharp nose"},
    {word: "брова", translation: "eyebrow", guessed: false, example: "She raised her eyebrow in surprise"},
    {word: "вія", translation: "eyelash", guessed: false, example: "She has long eyelashes"},
    {word: "череп", translation: "skull", guessed: false, example: "The skull protects the brain"},
    {word: "підборіддя", translation: "chin", guessed: false, example: "He stroked his chin thoughtfully"},
    {word: "скроню", translation: "temple", guessed: false, example: "He rubbed his temples to ease the headache"},
    {word: "мозок", translation: "brain", guessed: false, example: "The brain is a complex organ"},
    {word: "легені", translation: "lungs", guessed: false, example: "He took a deep breath to fill his lungs"},
    {word: "серце", translation: "heart", guessed: false, example: "The heart pumps blood through the body"},
    {word: "шлунок", translation: "stomach", guessed: false, example: "She felt butterflies in her stomach"},
    {word: "печінка", translation: "liver", guessed: false, example: "The liver detoxifies chemicals in the body"},
    {word: "нирка", translation: "kidney", guessed: false, example: "He donated a kidney to his brother"},
    {word: "здоров'я", translation: "health", guessed: false, example: "Health is the greatest wealth"},
    {word: "гігієна", translation: "hygiene", guessed: false, example: "Good hygiene is important for preventing illness"},
    {word: "хвороба", translation: "illness", guessed: false, example: "He was out of work due to illness"},
    {word: "захворювання", translation: "disease", guessed: false, example: "The disease spread quickly through the population"},
    {word: "одужання", translation: "recovery", guessed: false, example: "His recovery was slow but steady"},
    {word: "смерть", translation: "death", guessed: false, example: "The death of a loved one is always difficult"},
    {word: "пошкодження", translation: "injury", guessed: false, example: "He suffered an injury during the game"},
    {word: "перелом", translation: "fracture", guessed: false, example: "She had a fracture in her arm"},
    {word: "рана", translation: "wound", guessed: false, example: "The wound was deep and required stitches"},
    {word: "опік", translation: "burn", guessed: false, example: "He had a burn on his hand"},
    {word: "алергія", translation: "allergy", guessed: false, example: "She has a severe allergy to peanuts"}
];