export const natureWeather = [
    {word: "кислотний дощ", translation: "acid rain", guessed: false, example: "Acid rain can damage buildings"},
    {word: "повітря", translation: "air", guessed: false, example: "Clean air is essential for health"},
    {word: "атмосферний тиск", translation: "air pressure", guessed: false, example: "Air pressure affects weather patterns"},
    {word: "висота над рівнем моря", translation: "altitude", guessed: false, example: "Higher altitude can cause breathing difficulties"},
    {word: "територія, галузь", translation: "area", guessed: false, example: "This area is known for its natural beauty"},
    {word: "територія, зона", translation: "area", guessed: false, example: "The area was cordoned off by police"},
    {word: "атмосфера", translation: "atmosphere", guessed: false, example: "The atmosphere at the event was electric"},
    {word: "атом", translation: "atom", guessed: false, example: "An atom is the basic unit of matter"},
    {word: "лавина", translation: "avalanche", guessed: false, example: "The avalanche destroyed several homes"},
    {word: "повернення до природи", translation: "back to nature", guessed: false, example: "He decided to go back to nature and live in the countryside"},
    {word: "рівновага", translation: "balance", guessed: false, example: "Yoga helps improve your balance and flexibility"},
    {word: "країна", translation: "country", guessed: false, example: "She traveled to a new country every year"},
    {word: "природа", translation: "nature", guessed: false, example: "They spent the weekend enjoying the beauty of nature"},
    {word: "небо", translation: "sky", guessed: false, example: "The sky was filled with beautiful stars at night"},
    {word: "сонце", translation: "sun", guessed: false, example: "The sun set behind the mountains creating a stunning view"},
    {word: "повітря", translation: "air", guessed: false, example: "The fresh air in the mountains was invigorating"},
    {word: "хмара", translation: "cloud", guessed: false, example: "A single cloud drifted across the clear blue sky"},
    {word: "суша", translation: "land", guessed: false, example: "The boat finally reached the land after days at sea"},
    {word: "континент", translation: "continent", guessed: false, example: "Africa is a continent rich in cultural diversity"},
    {word: "територія", translation: "territory", guessed: false, example: "The wildlife sanctuary expanded its territory"},
    {word: "вода", translation: "water", guessed: false, example: "Water is essential for all living organisms"},
    {word: "річка", translation: "river", guessed: false, example: "The river flows through the heart of the city"},
    {word: "море", translation: "sea", guessed: false, example: "We spent our vacation by the sea"},
    {word: "озеро", translation: "lake", guessed: false, example: "The lake was surrounded by dense forest"},
    {word: "ліс", translation: "forest", guessed: false, example: "The forest is home to many different species of animals"},
    {word: "північ", translation: "North", guessed: false, example: "They traveled north to see the aurora borealis"},
    {word: "південь", translation: "South", guessed: false, example: "The climate is warmer in the south"},
    {word: "схід", translation: "East", guessed: false, example: "The sun rises in the east every morning"},
    {word: "крапля", translation: "drop", guessed: false, example: "A drop of rain fell on his face"},
    {word: "захід", translation: "West", guessed: false, example: "The sun sets in the west every evening"},
    {word: "атмосферний тиск", translation: "barometric pressure", guessed: false, example: "Barometric pressure is important for weather forecasting"},
    {word: "затока", translation: "bay", guessed: false, example: "The bay is a popular spot for fishing"},
    {word: "пляж", translation: "beach", guessed: false, example: "We spent the day relaxing on the beach"},
    {word: "біолог", translation: "biologist", guessed: false, example: "The biologist studied marine life in the coral reef"},
    {word: "біологія", translation: "biology", guessed: false, example: "Biology is the study of living organisms"},
    {word: "ботаніка", translation: "botany", guessed: false, example: "Botany is a branch of biology that focuses on plants"},
    {word: "дно", translation: "bottom", guessed: false, example: "The treasure was found at the bottom of the ocean"},
    {word: "повів вітру, порив вітру", translation: "breath of wind", guessed: false, example: "A breath of wind rustled the leaves"},
    {word: "вітерець", translation: "breeze", guessed: false, example: "A gentle breeze kept us cool in the summer heat"},
    {word: "діоксид вуглецю, вуглекислий газ", translation: "carbon dioxide", guessed: false, example: "Plants absorb carbon dioxide during photosynthesis"},
    {word: "м'ясоїдний", translation: "carnivorous", guessed: false, example: "Lions are carnivorous animals that hunt for their food"},
    {word: "печера", translation: "cave", guessed: false, example: "We explored a dark cave filled with bats"},
    {word: "кровообіг", translation: "circulation", guessed: false, example: "Good circulation is vital for maintaining health"},
    {word: "прозорий", translation: "clear", guessed: false, example: "The water in the lake was so clear you could see the fish swimming"},
    {word: "клімат", translation: "climate", guessed: false, example: "The climate in this region is very mild"},
    {word: "кліматичний", translation: "climatic", guessed: false, example: "Climatic changes have a significant impact on agriculture"},
    {word: "клонування", translation: "cloning", guessed: false, example: "Cloning technology has advanced rapidly in recent years"},
    {word: "хмара", translation: "cloud", guessed: false, example: "A single cloud floated across the blue sky"},
    {word: "вугільна шахта", translation: "coalmine", guessed: false, example: "He worked in a coalmine for over twenty years"},
    {word: "узбережжя", translation: "coast", guessed: false, example: "We took a scenic drive along the coast"},
    {word: "прибережний", translation: "coastal", guessed: false, example: "Coastal areas are often popular tourist destinations"},
    {word: "склад", translation: "composition", guessed: false, example: "The chemical composition of the water was analyzed"},
    {word: "кратер", translation: "crater", guessed: false, example: "The meteor left a huge crater in the ground"},
    {word: "схрещування, схрещування видів", translation: "crossbreeding", guessed: false, example: "Crossbreeding can produce new and stronger species"},
    {word: "цикл", translation: "cycle", guessed: false, example: "The water cycle is an essential part of Earth's ecosystem"},
    {word: "циклічний", translation: "cyclical", guessed: false, example: "Economic activity often follows a cyclical pattern"},
    {word: "вологий", translation: "damp", guessed: false, example: "The basement was damp and smelled musty"},
    {word: "темно", translation: "dark", guessed: false, example: "It gets dark early in the winter months"},
    {word: "темрява", translation: "darkness", guessed: false, example: "The room was plunged into darkness when the lights went out"},
    {word: "світанок", translation: "dawn", guessed: false, example: "We woke up at dawn to watch the sunrise"},
    {word: "глибокий", translation: "deep", guessed: false, example: "The lake is very deep in the center"},
    {word: "дефіцит", translation: "deficit", guessed: false, example: "There is a significant deficit in the budget"},
    {word: "глибина", translation: "depth", guessed: false, example: "The depth of the ocean is difficult to measure accurately"},
    {word: "пустельний", translation: "desert", guessed: false, example: "Desert areas receive very little rainfall"},
    {word: "пустеля", translation: "desert", guessed: false, example: "The Sahara is the largest hot desert in the world"},
    {word: "безлюдний", translation: "deserted", guessed: false, example: "The town was deserted after the factory closed"},
    {word: "роса", translation: "dew", guessed: false, example: "Morning dew covered the grass in tiny droplets"},
    {word: "мжичка", translation: "drizzle", guessed: false, example: "It was a grey day with light drizzle falling continuously"},
    {word: "крапля", translation: "drop", guessed: false, example: "A single drop of water fell from the faucet"},
    {word: "засуха", translation: "drought", guessed: false, example: "The drought caused severe water shortages"},
    {word: "сухий", translation: "dry", guessed: false, example: "The desert air was extremely dry and hot"},
    {word: "прах", translation: "dust", guessed: false, example: "Dust covered the shelves and furniture in the old house"},
    {word: "земля", translation: "earth", guessed: false, example: "Farmers till the earth to prepare for planting"},
    {word: "Земля", translation: "Earth", guessed: false, example: "Earth is the third planet from the Sun"},
    {word: "землетрус", translation: "earthquake", guessed: false, example: "The earthquake caused widespread damage"},
    {word: "відплив", translation: "ebb tide", guessed: false, example: "We walked along the shore during the ebb tide"},
    {word: "затемнення", translation: "eclipse", guessed: false, example: "The solar eclipse was an incredible sight"},
    {word: "екологічний", translation: "ecological", guessed: false, example: "Ecological conservation is vital for our planet"},
    {word: "еколог", translation: "ecologist", guessed: false, example: "An ecologist studies the relationships between living organisms and their environment"},
    {word: "екологія", translation: "ecology", guessed: false, example: "Ecology is the study of ecosystems"},
    {word: "екосистема", translation: "ecosystem", guessed: false, example: "A healthy ecosystem is balanced and sustainable"},
    {word: "середовище", translation: "environment", guessed: false, example: "Protecting the environment is everyone's responsibility"},
    {word: "ерозія", translation: "erosion", guessed: false, example: "Erosion can reshape landscapes over time"},
    {word: "екзотичний", translation: "exotic", guessed: false, example: "The exotic flowers added a splash of color to the garden"},
    {word: "екзотика", translation: "exoticism", guessed: false, example: "The exoticism of the decor gave the room a unique atmosphere"},
    {word: "пожежа", translation: "fire", guessed: false, example: "The fire spread quickly through the forest"},
    {word: "вогонь", translation: "fire", guessed: false, example: "The campers sat around the fire telling stories"},
    {word: "полум'я", translation: "flame", guessed: false, example: "The candle's flame flickered in the breeze"},
    {word: "квітковий магазин", translation: "florist", guessed: false, example: "She bought roses from the local florist"},
    {word: "квітка", translation: "flower", guessed: false, example: "The flower bloomed in the spring sunshine"},
    {word: "туман", translation: "fog", guessed: false, example: "The fog made it difficult to see the road ahead"},
    {word: "ліс", translation: "forest", guessed: false, example: "The forest was full of tall, ancient trees"},
    {word: "мороз", translation: "frost", guessed: false, example: "Frost covered the ground on the cold winter morning"},
    {word: "іній", translation: "frost", guessed: false, example: "The windows were covered with a thin layer of frost"},
    {word: "повний місяць, повня", translation: "full moon", guessed: false, example: "The full moon illuminated the night sky"},
    {word: "ген", translation: "gene", guessed: false, example: "Scientists are studying the gene responsible for the disease"},
    {word: "льодовик", translation: "glacier", guessed: false, example: "The glacier is slowly melting due to climate change"},
    {word: "глобальне потепління", translation: "global warming", guessed: false, example: "Global warming is causing sea levels to rise"},
    {word: "ущелина", translation: "gorge", guessed: false, example: "The river carved a deep gorge through the mountains"},
    {word: "трава", translation: "grass", guessed: false, example: "The grass was wet with morning dew"},
    {word: "тяжіння", translation: "gravitation", guessed: false, example: "Gravitation keeps the planets in orbit around the sun"},
    {word: "тяжіння", translation: "gravity", guessed: false, example: "Gravity causes objects to fall towards the earth"},
    {word: "парниковий ефект", translation: "greenhouse effect", guessed: false, example: "The greenhouse effect is a major factor in global warming"},
    {word: "земля", translation: "ground", guessed: false, example: "The ground was covered in fallen leaves"},
    {word: "приморозок", translation: "ground frost", guessed: false, example: "Ground frost can damage crops if not protected"},
    {word: "затока", translation: "gulf", guessed: false, example: "The Gulf of Mexico is known for its warm waters"},
    {word: "повів вітру, порив вітру", translation: "gust of wind", guessed: false, example: "A gust of wind knocked over the garden furniture"},
    {word: "град", translation: "hail", guessed: false, example: "The hail damaged cars and rooftops during the storm"},
    {word: "спека", translation: "heat", guessed: false, example: "The heat of the summer sun was unbearable"},
    {word: "спадковий", translation: "hereditary", guessed: false, example: "Certain diseases are hereditary and run in families"},
    {word: "спадковість", translation: "heredity", guessed: false, example: "Heredity plays a role in determining physical traits"},
    {word: "узгір'я", translation: "hill", guessed: false, example: "We climbed the hill to get a better view of the valley"},
    {word: "горбистий", translation: "hilly", guessed: false, example: "The hilly terrain made the hike challenging"},
    {word: "діра, яма", translation: "hole", guessed: false, example: "He dug a hole in the garden to plant a tree"},
    {word: "горизонт", translation: "horizon", guessed: false, example: "The sun set below the horizon, painting the sky with colors"},
    {word: "людина", translation: "human", guessed: false, example: "Every human has the right to freedom and dignity"},
    {word: "ураган", translation: "hurricane", guessed: false, example: "The hurricane caused extensive damage to the coastal town"},
    {word: "лід", translation: "ice", guessed: false, example: "The ice on the lake was thick enough to skate on"},
    {word: "льодовиковий період", translation: "Ice Age", guessed: false, example: "The Ice Age shaped much of the Earth's current landscape"},
    {word: "обледенілий", translation: "icy", guessed: false, example: "The roads were icy and dangerous to drive on"},
    {word: "комаха", translation: "insect", guessed: false, example: "The garden was buzzing with various insect species"},
    {word: "в тіні", translation: "in the shade", guessed: false, example: "We sat in the shade to escape the heat of the sun"},
    {word: "на сонці", translation: "in the sun", guessed: false, example: "She lay in the sun to get a tan"},
    {word: "острів", translation: "island", guessed: false, example: "The island was surrounded by crystal-clear water"},
    {word: "джунглі", translation: "jungle", guessed: false, example: "The jungle was dense with tropical plants and wildlife"},
    {word: "озеро", translation: "lake", guessed: false, example: "We went fishing on the lake early in the morning"},
    {word: "краєвид", translation: "landscape", guessed: false, example: "The landscape was dotted with picturesque villages"},
    {word: "лава", translation: "lava", guessed: false, example: "Lava flowed from the volcano during the eruption"},
    {word: "газон", translation: "lawn", guessed: false, example: "He mowed the lawn every weekend"},
    {word: "листок", translation: "leaf", guessed: false, example: "The leaf turned bright red in the autumn"},
    {word: "тривалість життя", translation: "lifespan", guessed: false, example: "The lifespan of a butterfly is typically very short"},
    {word: "світло", translation: "light", guessed: false, example: "The room was filled with natural light from the windows"},
    {word: "блискавка", translation: "lightning", guessed: false, example: "The storm brought heavy rain and frequent lightning"},
    {word: "ссавець", translation: "mammal", guessed: false, example: "Humans are classified as mammals"},
    {word: "людина", translation: "man", guessed: false, example: "The man walked his dog in the park every morning"},
    {word: "мужність", translation: "manhood", guessed: false, example: "He proved his manhood by standing up for what was right"},
    {word: "морський", translation: "maritime", guessed: false, example: "Maritime law governs nautical issues and private maritime disputes"},
    {word: "луг", translation: "meadow", guessed: false, example: "The meadow was filled with wildflowers in the spring"},
    {word: "шахта", translation: "mine", guessed: false, example: "They worked in a coal mine deep underground"},
    {word: "плавлений", translation: "molten", guessed: false, example: "The molten lava flowed slowly down the mountainside"},
    {word: "Місяць", translation: "moon", guessed: false, example: "The full moon shone brightly in the night sky"},
    {word: "гора", translation: "mountain", guessed: false, example: "The mountain was covered in snow year-round"},
    {word: "болото", translation: "mud", guessed: false, example: "The rain turned the dirt road into a quagmire of mud"},
    {word: "болотистий", translation: "muddy", guessed: false, example: "The trail was muddy after the rainstorm"},
    {word: "природний", translation: "natural", guessed: false, example: "The park is known for its natural beauty"},
    {word: "природні ресурси", translation: "natural resources", guessed: false, example: "The country is rich in natural resources like coal and timber"},
    {word: "природа", translation: "nature", guessed: false, example: "We took a walk to enjoy the beauty of nature"},
    {word: "ніч", translation: "night", guessed: false, example: "The stars were visible in the clear night sky"},
    {word: "ядерна енергія", translation: "nuclear energy", guessed: false, example: "Nuclear energy is a powerful source of electricity"},
    {word: "океан", translation: "ocean", guessed: false, example: "The ocean waves crashed against the shore"},
    {word: "органічне добриво", translation: "organic fertilizer", guessed: false, example: "Organic fertilizer is better for the environment than synthetic types"},
    {word: "стежка", translation: "path", guessed: false, example: "The path through the forest was narrow and winding"},
    {word: "вершина", translation: "peak", guessed: false, example: "The peak of the mountain was covered in snow"},
    {word: "пікоподібний", translation: "peaked", guessed: false, example: "The house had a peaked roof"},
    {word: "півострів", translation: "peninsula", guessed: false, example: "The peninsula juts out into the sea"},
    {word: "пелюстка", translation: "petal", guessed: false, example: "The flower's petal was delicate and soft"},
    {word: "фотосинтез", translation: "photosynthesis", guessed: false, example: "Photosynthesis is how plants make food from sunlight"},
    {word: "мальовничий", translation: "picturesque", guessed: false, example: "The village was picturesque with its charming cottages"},
    {word: "шишка", translation: "pine cone", guessed: false, example: "We collected a pine cone from the forest floor"},
    {word: "рівнина", translation: "plain", guessed: false, example: "The plains were vast and flat, stretching for miles"},
    {word: "рослина", translation: "plant", guessed: false, example: "The plant needs sunlight and water to grow"},
    {word: "плоскогір'я", translation: "plateau", guessed: false, example: "The plateau was a high, flat expanse of land"},
    {word: "отруйний", translation: "poisonous", guessed: false, example: "Some mushrooms are poisonous and should not be eaten"},
    {word: "Полярна зоря", translation: "Pole Star", guessed: false, example: "The Pole Star is used for navigation"},
    {word: "ставок", translation: "pond", guessed: false, example: "Ducks were swimming in the pond"},
    {word: "провалля", translation: "precipice", guessed: false, example: "The climber looked over the edge of the precipice"},
    {word: "калюжа", translation: "puddle", guessed: false, example: "The child splashed in the puddle after the rain"},
    {word: "раса", translation: "race", guessed: false, example: "Humans are classified into different race groups"},
    {word: "випромінювання", translation: "radiation", guessed: false, example: "Radiation can be harmful to living organisms"},
    {word: "дощ", translation: "rain", guessed: false, example: "The rain poured down all night"},
    {word: "веселка", translation: "rainbow", guessed: false, example: "A rainbow appeared after the rain stopped"},
    {word: "крапля дощу", translation: "raindrop", guessed: false, example: "A raindrop fell on my nose"},
    {word: "дощовий ліс", translation: "rainforest", guessed: false, example: "The rainforest is home to many exotic animals"},
    {word: "рідкісний", translation: "rare", guessed: false, example: "This flower is rare and hard to find"},
    {word: "рідкісний вид", translation: "rare species", guessed: false, example: "The rare species was protected by law"},
    {word: "реальність", translation: "reality", guessed: false, example: "In reality, the situation was much worse than reported"},
    {word: "риф", translation: "reef", guessed: false, example: "The coral reef was teeming with marine life"},
    {word: "регіон", translation: "region", guessed: false, example: "This region is known for its wine production"},
    {word: "розмноження", translation: "reproduction", guessed: false, example: "Reproduction is essential for the survival of a species"},
    {word: "річка", translation: "river", guessed: false, example: "The river flows into the sea"},
    {word: "берег ріки", translation: "river bank", guessed: false, example: "We had a picnic on the river bank"},
    {word: "скеля", translation: "rock", guessed: false, example: "The rock formation was millions of years old"},
    {word: "скелястий", translation: "rocky", guessed: false, example: "The rocky terrain made the hike difficult"},
    {word: "гниття", translation: "rot", guessed: false, example: "The fruit began to rot after a few days"},
    {word: "солона вода", translation: "salt water", guessed: false, example: "Salt water is found in the oceans"},
    {word: "пісок", translation: "sand", guessed: false, example: "The beach was covered in fine white sand"},
    {word: "піщаний", translation: "sandy", guessed: false, example: "The sandy shore was perfect for sunbathing"},
    {word: "який рідко зустрічається", translation: "scarce", guessed: false, example: "Water is scarce in desert regions"},
    {word: "море", translation: "sea", guessed: false, example: "The sea was calm and blue"},
    {word: "узбережжя", translation: "seaside", guessed: false, example: "We spent our vacation at the seaside"},
    {word: "пора року", translation: "season", guessed: false, example: "Autumn is my favorite season"},
    {word: "насіння", translation: "seed", guessed: false, example: "We planted a seed and watched it grow"},
    {word: "тінь", translation: "shade", guessed: false, example: "We sat in the shade to cool off"},
    {word: "тінь", translation: "shadow", guessed: false, example: "The tree cast a long shadow in the evening light"},
    {word: "затінений", translation: "shadowy", guessed: false, example: "The garden was cool and shadowy"},
    {word: "мілкий", translation: "shallow", guessed: false, example: "The water was too shallow for swimming"},
    {word: "блиск", translation: "shine", guessed: false, example: "The sun's shine was blindingly bright"},
    {word: "зірка, що падає", translation: "shooting star", guessed: false, example: "We made a wish upon a shooting star"},
    {word: "прохідний дощ", translation: "shower", guessed: false, example: "A quick shower passed over us"},
    {word: "територія, зона", translation: "site", guessed: false, example: "The construction site was bustling with activity"},
    {word: "небо", translation: "sky", guessed: false, example: "The sky was clear and blue"},
    {word: "схил", translation: "slope", guessed: false, example: "We skied down the steep slope"},
    {word: "похилий", translation: "sloping", guessed: false, example: "The sloping hills were dotted with sheep"},
    {word: "дим", translation: "smoke", guessed: false, example: "Smoke rose from the chimney"},
    {word: "сніг", translation: "snow", guessed: false, example: "Snow covered the ground in a thick blanket"},
    {word: "сніговий замет", translation: "snowdrift", guessed: false, example: "The snowdrift was higher than the car"},
    {word: "сніжинка", translation: "snowflake", guessed: false, example: "Each snowflake is unique in its pattern"},
    {word: "ґрунт", translation: "soil", guessed: false, example: "The soil was rich and fertile"},
    {word: "сонячна енергія", translation: "solar energy", guessed: false, example: "Solar energy is a renewable resource"},
    {word: "витік, джерело", translation: "source", guessed: false, example: "The river's source was high in the mountains"},
    {word: "джерело енергії", translation: "source of energy", guessed: false, example: "Wind is a clean source of energy"},
    {word: "простір", translation: "space", guessed: false, example: "Outer space is vast and largely unexplored"},
    {word: "зірка", translation: "star", guessed: false, example: "The night sky was filled with bright stars"},
    {word: "зоряний", translation: "starry", guessed: false, example: "The starry sky was beautiful to behold"},
    {word: "крутий", translation: "steep", guessed: false, example: "The steep path was hard to climb"},
    {word: "палиця", translation: "stick", guessed: false, example: "He used a stick to draw in the sand"},
    {word: "буря", translation: "storm", guessed: false, example: "The storm knocked out power to the entire neighborhood"},
    {word: "протока", translation: "strait", guessed: false, example: "The strait was a busy shipping lane"},
    {word: "струмок", translation: "stream", guessed: false, example: "We followed the stream through the forest"},
    {word: "вершина", translation: "summit", guessed: false, example: "We reached the summit after a long climb"},
    {word: "сонце", translation: "sun", guessed: false, example: "The sun shone brightly all day"},
    {word: "схід сонця", translation: "sunrise", guessed: false, example: "We woke up early to watch the sunrise"},
    {word: "захід сонця", translation: "sunset", guessed: false, example: "The sunset painted the sky in shades of orange and pink"},
    {word: "територія, зона", translation: "territory", guessed: false, example: "The dog marked its territory by the fence"},
    {word: "село", translation: "the country", guessed: false, example: "Life in the country is peaceful and quiet"},
    {word: "грім", translation: "thunder", guessed: false, example: "Thunder rumbled in the distance"},
    {word: "дихати", translation: "to breathe", guessed: false, example: "It is important to breathe deeply and calmly"},
    {word: "вдихати", translation: "to breathe in", guessed: false, example: "She took a moment to breathe in the fresh air"},
    {word: "розпогоджуватись", translation: "to brighten up", guessed: false, example: "The weather is expected to brighten up later"},
    {word: "провести експеримент", translation: "to carry out an experiment", guessed: false, example: "They needed more supplies to carry out an experiment"},
    {word: "осуватися", translation: "to cave in", guessed: false, example: "The roof began to cave in under the weight of the snow"},
    {word: "зрубувати дерево", translation: "to chop down a tree", guessed: false, example: "They decided to chop down a tree for firewood"},
    {word: "клонувати", translation: "to clone", guessed: false, example: "Scientists managed to clone a sheep successfully"},
    {word: "споглядати", translation: "to contemplate", guessed: false, example: "She sat by the lake to contemplate her future"},
    {word: "осушувати", translation: "to drain", guessed: false, example: "We had to drain the swamp to build the road"},
    {word: "висихати", translation: "to dry up", guessed: false, example: "The river began to dry up during the drought"},
    {word: "вибухати", translation: "to erupt", guessed: false, example: "The volcano could erupt at any moment"},
    {word: "використовувати", translation: "to exhaust", guessed: false, example: "They did not want to exhaust all their resources"},
    {word: "розливатись", translation: "to flood", guessed: false, example: "The river began to flood after the heavy rain"},
    {word: "плисти, спливати", translation: "to flow", guessed: false, example: "The water continued to flow steadily downstream"},
    {word: "збирати пилок", translation: "to gather pollen", guessed: false, example: "Bees gather pollen to make honey"},
    {word: "темніти", translation: "to get dark", guessed: false, example: "It started to get dark earlier each day"},
    {word: "світити", translation: "to light", guessed: false, example: "He used a match to light the campfire"},
    {word: "танути", translation: "to melt", guessed: false, example: "The ice began to melt in the warm sun"},
    {word: "вершина", translation: "top", guessed: false, example: "We reached the top of the mountain after hours of hiking"},
    {word: "випромінювати", translation: "to radiate", guessed: false, example: "The heater began to radiate heat throughout the room"},
    {word: "розмножуватись", translation: "to reproduce", guessed: false, example: "Plants can reproduce through seeds or cuttings"},
    {word: "підніматись", translation: "to rise", guessed: false, example: "The sun began to rise over the horizon"},
    {word: "світити", translation: "to shine", guessed: false, example: "The stars continued to shine brightly in the sky"},
    {word: "спадати", translation: "to subside", guessed: false, example: "The floodwaters began to subside after the rain stopped"},
    {word: "випаровуватись", translation: "to vaporize", guessed: false, example: "The heat caused the water to vaporize quickly"},
    {word: "торнадо", translation: "tornado", guessed: false, example: "The tornado left a path of destruction in its wake"},
    {word: "дерево", translation: "tree", guessed: false, example: "We planted a new tree in the backyard"},
    {word: "тропічний", translation: "tropical", guessed: false, example: "The tropical climate is perfect for growing bananas"},
    {word: "цунамі", translation: "tsunami", guessed: false, example: "The tsunami caused severe damage along the coast"},
    {word: "тайфун", translation: "typhoon", guessed: false, example: "The typhoon brought heavy rains and strong winds"},
    {word: "під відкритим небом", translation: "under the open sky", guessed: false, example: "We slept under the open sky on our camping trip"},
    {word: "під водою", translation: "underwater", guessed: false, example: "The shipwreck lies underwater, deep in the ocean"},
    {word: "долина", translation: "valley", guessed: false, example: "The valley was surrounded by towering mountains"},
    {word: "пар", translation: "vapor", guessed: false, example: "The kettle released a steady stream of vapor"},
    {word: "вулкан", translation: "volcano", guessed: false, example: "The volcano erupted, spewing lava and ash"},
    {word: "теплий", translation: "warm", guessed: false, example: "The warm sun felt good on our skin"},
    {word: "вода", translation: "water", guessed: false, example: "We need water to survive"},
    {word: "водяна пара", translation: "water vapor", guessed: false, example: "Water vapor is a key component of the water cycle"},
    {word: "водоспад", translation: "waterfall", guessed: false, example: "The waterfall cascaded down the rocky cliff"},
    {word: "хвиля", translation: "wave", guessed: false, example: "The surfer rode a huge wave"},
    {word: "погода", translation: "weather", guessed: false, example: "The weather was perfect for a picnic"},
    {word: "прогноз погоди", translation: "weather forecast", guessed: false, example: "The weather forecast predicted rain for the weekend"},
    {word: "бур'ян", translation: "weed", guessed: false, example: "We need to pull the weeds from the garden"},
    {word: "мокрий", translation: "wet", guessed: false, example: "My shoes were wet from the rain"},
    {word: "вихрь", translation: "whirlwind", guessed: false, example: "The whirlwind swept across the field"},
    {word: "дикий", translation: "wild", guessed: false, example: "The wild animals roamed freely in the forest"},
    {word: "дика природа", translation: "wildlife", guessed: false, example: "The wildlife sanctuary is home to many endangered species"},
    {word: "вітер", translation: "wind", guessed: false, example: "The wind blew strongly across the plains"}
];