export const time = [
    {word: "час", translation: "time", guessed: false, example: "Time flies when you're having fun"},
    {word: "століття", translation: "century", guessed: false, example: "We are living in the 21st century"},
    {word: "рік", translation: "year", guessed: false, example: "The year 2020 was full of significant events"},
    {word: "місяць", translation: "month", guessed: false, example: "April is my favorite month of the year"},
    {word: "тиждень", translation: "week", guessed: false, example: "The work week felt particularly long this time"},
    {word: "день", translation: "day", guessed: false, example: "The day was bright and sunny"},
    {word: "година", translation: "hour", guessed: false, example: "She waited for an hour at the bus stop"},
    {word: "хвилина", translation: "minute", guessed: false, example: "There are sixty seconds in a minute"},
    {word: "годинник", translation: "clock", guessed: false, example: "The clock on the wall struck twelve"},
    {word: "годинник", translation: "watch", guessed: false, example: "He checked his watch for the time"},
    {word: "календар", translation: "calendar", guessed: false, example: "She marked the important dates on her calendar"},
    {word: "ранок", translation: "morning", guessed: false, example: "The morning was calm and peaceful"},
    {word: "опівдні", translation: "noon", guessed: false, example: "The sun is at its highest point at noon"},
    {word: "час після обіду", translation: "afternoon", guessed: false, example: "We took a walk in the park in the afternoon"},
    {word: "вечір", translation: "evening", guessed: false, example: "The evening sky was painted with beautiful colors"},
    {word: "ніч", translation: "night", guessed: false, example: "The stars were visible in the clear night sky"},
    {word: "даний час", translation: "present", guessed: false, example: "Living in the present moment is important"},
    {word: "минуле", translation: "past", guessed: false, example: "The past is behind us and cannot be changed"},
    {word: "майбутнє", translation: "future", guessed: false, example: "We should plan for a better future"},
    {word: "початок", translation: "beginning", guessed: false, example: "The beginning of the movie was quite interesting"},
    {word: "кінець", translation: "end", guessed: false, example: "They stayed until the very end of the concert"},
    {word: "розклад", translation: "schedule", guessed: false, example: "I need to check my schedule for tomorrow's meeting"},
    {word: "затримка", translation: "delay", guessed: false, example: "There was a delay in the train's arrival"},
    {word: "свято", translation: "holiday", guessed: false, example: "We spent the holiday with family and friends"},
    {word: "вихідні", translation: "weekend", guessed: false, example: "I am looking forward to the weekend"},
    {word: "канікули", translation: "vacation", guessed: false, example: "They planned a vacation to the mountains"}
];