export const transport = [
    {word: "автобус", translation: "bus", guessed: false, example: "They took the bus to the city center"},
    {word: "тролейбус", translation: "trolleybus", guessed: false, example: "The trolleybus was crowded with passengers"},
    {word: "трамвай", translation: "tram", guessed: false, example: "They rode the tram across town"},
    {word: "метро", translation: "metro", guessed: false, example: "The metro was fast and efficient"},
    {word: "автомобіль", translation: "car", guessed: false, example: "They drove a new car"},
    {word: "таксі", translation: "taxi", guessed: false, example: "They called a taxi to get home"},
    {word: "вантажівка", translation: "truck", guessed: false, example: "The truck was loaded with goods"},
    {word: "залізна дорога", translation: "railway station", guessed: false, example: "They waited at the railway station"},
    {word: "платформа", translation: "platform", guessed: false, example: "The train arrived at the platform"},
    {word: "шлях", translation: "track", guessed: false, example: "The train followed the track"},
    {word: "потяг", translation: "train", guessed: false, example: "They took the train to another city"},
    {word: "відправлення", translation: "departure", guessed: false, example: "The departure time was delayed"},
    {word: "прибуття", translation: "arrival", guessed: false, example: "The arrival time was earlier than expected"},
    {word: "пересадка", translation: "change", guessed: false, example: "They had to change trains at the next station"},
    {word: "аеропорт", translation: "airport", guessed: false, example: "They arrived at the airport early"},
    {word: "літак", translation: "plane", guessed: false, example: "They boarded the plane for their flight"},
    {word: "реєстрація", translation: "check in", guessed: false, example: "They completed the check in process quickly"},
    {word: "паспортний контроль", translation: "passport control", guessed: false, example: "They went through passport control"},
    {word: "взліт(літака)", translation: "take-off", guessed: false, example: "The plane's take-off was smooth"},
    {word: "посадка", translation: "landing", guessed: false, example: "The landing was a bit bumpy"},
    {word: "стюардеса", translation: "flight attendant", guessed: false, example: "The flight attendant was very helpful"},
    {word: "пілот", translation: "pilot", guessed: false, example: "The pilot greeted the passengers"},
    {word: "посадка на борт", translation: "boarding", guessed: false, example: "Boarding began at gate 23"},
    {word: "політ", translation: "flight", guessed: false, example: "The flight was long but comfortable"},
    {word: "місце", translation: "seat", guessed: false, example: "She had a window seat"},
    {word: "бронювання", translation: "reservation", guessed: false, example: "They made a reservation at the restaurant"},
    {word: "ремінь безпеки", translation: "seat-belt", guessed: false, example: "They fastened their seat-belts"}
];