export const weather_ua = [
    {word: "атмосферний тиск", translation: "air pressure", guessed: false, example: "The air pressure is very low today"},
    {word: "поганий", translation: "bad", guessed: false, example: "The weather turned bad very suddenly"},
    {word: "атмосферний тиск", translation: "barometric pressure", guessed: false, example: "Barometric pressure changes predict upcoming storms"},
    {word: "вітряний", translation: "blowy", guessed: false, example: "It is a very blowy afternoon outside"},
    {word: "повів вітру, порив вітру", translation: "breath of wind", guessed: false, example: "A breath of wind cooled my face"},
    {word: "вітерець", translation: "breeze", guessed: false, example: "A gentle breeze blew through the trees"},
    {word: "клімат", translation: "climate", guessed: false, example: "The climate here can change very quickly"},
    {word: "хмара", translation: "cloud", guessed: false, example: "A dark cloud signaled the coming rain"},
    {word: "похмурий", translation: "cloudy", guessed: false, example: "It is a cloudy and grey afternoon"},
    {word: "холодно", translation: "cold", guessed: false, example: "It feels very cold outside today"},
    {word: "холодний", translation: "cold", guessed: false, example: "The lake water is extremely cold"},
    {word: "холод", translation: "coldness", guessed: false, example: "The coldness in the room was intense"},
    {word: "холодний", translation: "cool", guessed: false, example: "The evening air is refreshingly cool"},
    {word: "градус", translation: "degree", guessed: false, example: "It is twenty degrees outside today"},
    {word: "злива", translation: "downpour", guessed: false, example: "A sudden downpour caught everyone off guard"},
    {word: "мжичка", translation: "drizzle", guessed: false, example: "A light drizzle began in the evening"},
    {word: "похмурий", translation: "dull", guessed: false, example: "The sky is dull and overcast today"},
    {word: "мінливий", translation: "fickle", guessed: false, example: "The weather in spring is quite fickle"},
    {word: "туман", translation: "fog", guessed: false, example: "The fog is thick and hard to see through"},
    {word: "туманний", translation: "foggy", guessed: false, example: "It is a foggy morning today outside"},
    {word: "погода", translation: "weather", guessed: false, example: "The weather was perfect for a picnic"},
    {word: "сезон", translation: "season", guessed: false, example: "Spring is my favorite season of the year"},
    {word: "зима", translation: "winter", guessed: false, example: "Winter is often associated with cold and snow"},
    {word: "весна", translation: "spring", guessed: false, example: "Spring brings new life and vibrant colors"},
    {word: "літо", translation: "summer", guessed: false, example: "Summer is perfect for beach holidays and outdoor activities"},
    {word: "осінь", translation: "autumn", guessed: false, example: "The leaves turn beautiful colors in autumn"},
    {word: "температура", translation: "temperature", guessed: false, example: "The temperature dropped significantly at night"},
    {word: "тиск", translation: "pressure", guessed: false, example: "The pressure changes can affect the weather patterns"},
    {word: "дощ", translation: "rain", guessed: false, example: "The rain poured down heavily all day"},
    {word: "сніг", translation: "snow", guessed: false, example: "The snow covered the ground in a thick blanket"},
    {word: "грім", translation: "thunder", guessed: false, example: "The thunder rumbled loudly during the storm"},
    {word: "блискавка", translation: "lightning", guessed: false, example: "The lightning lit up the sky in a spectacular display"},
    {word: "вітер", translation: "wind", guessed: false, example: "The wind howled through the trees during the night"},
    {word: "льодяний", translation: "freezing cold", guessed: false, example: "The water in the lake is freezing cold"},
    {word: "іній", translation: "frost", guessed: false, example: "There is frost covering the ground today"},
    {word: "мороз", translation: "frost", guessed: false, example: "A severe frost occurred last night"},
    {word: "морозний", translation: "frosty", guessed: false, example: "It is a frosty and bright winter day"},
    {word: "приморозок", translation: "ground frost", guessed: false, example: "Ground frost is expected to occur tonight"},
    {word: "порив вітру", translation: "gust of wind", guessed: false, example: "A gust of wind knocked over the trash can"},
    {word: "град", translation: "hail", guessed: false, example: "Hail damaged the cars in the parking lot"},
    {word: "тепло́", translation: "heat", guessed: false, example: "The heat of the sun was intense today"},
    {word: "спека", translation: "heat", guessed: false, example: "The summer heat was almost unbearable"},
    {word: "гарячий", translation: "hot", guessed: false, example: "The soup served at lunch was very hot"},
    {word: "гаряче", translation: "hot", guessed: false, example: "It feels extremely hot outside today"},
    {word: "ураган", translation: "hurricane", guessed: false, example: "The hurricane caused widespread damage and flooding"},
    {word: "обледенілий", translation: "icy", guessed: false, example: "The roads were icy and very dangerous"},
    {word: "блискавка", translation: "lightning", guessed: false, example: "The lightning lit up the night sky"},
    {word: "громовідвід", translation: "lightning conductor", guessed: false, example: "A lightning conductor protects buildings from strikes"},
    {word: "метеоролог", translation: "meteorologist", guessed: false, example: "The meteorologist predicted rain for the weekend"},
    {word: "болото", translation: "mud", guessed: false, example: "The path was covered in thick mud"},
    {word: "калюжа", translation: "puddle", guessed: false, example: "Children were jumping in the puddles"},
    {word: "дощ", translation: "rain", guessed: false, example: "The rain began to fall heavily"},
    {word: "калоші", translation: "rain boots", guessed: false, example: "Wear your rain boots on wet days"},
    {word: "веселка", translation: "rainbow", guessed: false, example: "A beautiful rainbow appeared after the rain"},
    {word: "плащ", translation: "raincoat", guessed: false, example: "Don’t forget your raincoat before leaving"},
    {word: "крапля дощу", translation: "raindrop", guessed: false, example: "A single raindrop fell on my nose"},
    {word: "дощовий", translation: "rainy", guessed: false, example: "It’s a rainy day, stay inside"},
    {word: "блиск", translation: "shine", guessed: false, example: "The shine on the car was impressive"},
    {word: "прохідний дощ", translation: "shower", guessed: false, example: "There was a brief shower in the afternoon"},
    {word: "сльота", translation: "sleet", guessed: false, example: "The sleet made driving difficult"},
    {word: "сніг", translation: "snow", guessed: false, example: "Snow covered the ground overnight"},
    {word: "сніговий замет", translation: "snowdrift", guessed: false, example: "A snowdrift blocked the road"},
    {word: "опади снігу", translation: "snowfall", guessed: false, example: "The snowfall was heavy last night"},
    {word: "сніжний", translation: "snowy", guessed: false, example: "It’s a snowy winter day"},
    {word: "спекотний", translation: "stifling", guessed: false, example: "The stifling heat made it hard to breathe"},
    {word: "затхлий", translation: "stifling", guessed: false, example: "The room was stifling and needed air"},
    {word: "буря", translation: "storm", guessed: false, example: "A storm is approaching from the west"},
    {word: "сонячний", translation: "sunny", guessed: false, example: "It’s a bright and sunny morning"},
    {word: "грім", translation: "thunder", guessed: false, example: "The thunder scared the dog"},
    {word: "дути", translation: "to blow", guessed: false, example: "The wind began to blow harder"},
    {word: "посвітліти", translation: "to brighten", guessed: false, example: "The sky started to brighten after the rain"},
    {word: "розпогоджуватись", translation: "to brighten up", guessed: false, example: "The day began to brighten up in the afternoon"},
    {word: "прояснятися", translation: "to clear up", guessed: false, example: "The weather is expected to clear up later"},
    {word: "хмаритись", translation: "to cloud over", guessed: false, example: "The sky began to cloud over"},
    {word: "мрячити", translation: "to drizzle", guessed: false, example: "It started to drizzle lightly"},
    {word: "понижуватися", translation: "to fall", guessed: false, example: "Temperatures will fall tonight"},
    {word: "прогнозувати", translation: "to forecast", guessed: false, example: "They forecast rain for tomorrow"},
    {word: "замерзати", translation: "to freeze", guessed: false, example: "The pond will freeze over by morning"},
    {word: "охолоджуватись", translation: "to get cold", guessed: false, example: "It is starting to get cold now"},
    {word: "теплішати", translation: "to get warmer", guessed: false, example: "It will get warmer by the weekend"},
    {word: "змокнути", translation: "to get wet", guessed: false, example: "We will get wet if we go out"},
    {word: "збиратись на дощ", translation: "to look like rain", guessed: false, example: "It looks like rain is coming"},
    {word: "лити", translation: "to pour", guessed: false, example: "It started to pour heavily"},
    {word: "падати", translation: "to rain", guessed: false, example: "It will rain all day tomorrow"},
    {word: "падати", translation: "to snow", guessed: false, example: "It will snow heavily tonight"},
    {word: "гриміти", translation: "to thunder", guessed: false, example: "It began to thunder loudly"},
    {word: "парасоля", translation: "umbrella", guessed: false, example: "Take an umbrella to stay dry"},
    {word: "теплий", translation: "warm", guessed: false, example: "The weather is warm and pleasant"},
    {word: "тепло́", translation: "warmth", guessed: false, example: "The warmth of the fire was comforting"},
    {word: "погода", translation: "weather", guessed: false, example: "The weather is nice today"},
    {word: "погодні умови", translation: "weather conditions", guessed: false, example: "The weather conditions are favorable"},
    {word: "прогноз погоди", translation: "weather forecast", guessed: false, example: "The weather forecast predicts rain"},
    {word: "оглядач погоди", translation: "weatherman", guessed: false, example: "The weatherman said it would snow"},
    {word: "гумові чоботи", translation: "wellington boots", guessed: false, example: "Wear your wellington boots in the mud"},
    {word: "вітер", translation: "wind", guessed: false, example: "The wind is very strong today"},
    {word: "вітряний", translation: "windy", guessed: false, example: "It is a very windy afternoon"}
]
