export const lesson1Words = [
    {word: "кислотний дощ", translation: "acid rain", guessed: false, example: "Acid rain damages buildings and forests"},
    {word: "забруднення повітря", translation: "air pollution", guessed: false, example: "Air pollution is a major urban problem"},
    {word: "вирубування лісів", translation: "deforestation", guessed: false, example: "Deforestation affects climate and wildlife"},
    {word: "екологічний", translation: "ecological", guessed: false, example: "We need more ecological solutions"},
    {word: "еколог", translation: "ecologist", guessed: false, example: "An ecologist studies the environment"},
    {word: "екологія", translation: "ecology", guessed: false, example: "Ecology is a branch of biology"},
    {word: "нешкідливий для середовища", translation: "environment-friendly", guessed: false, example: "These products are environment-friendly"},
    {word: "середовище", translation: "environment", guessed: false, example: "Protecting the environment is crucial"},
    {word: "катастрофа екологічна", translation: "environmental disaster", guessed: false, example: "The oil spill was an environmental disaster"},
    {word: "вихлопні гази", translation: "exhaust fumes", guessed: false, example: "Exhaust fumes contribute to air pollution"},
    {word: "фабрика", translation: "factory", guessed: false, example: "The factory emits pollutants into the air"},
    {word: "удобрення", translation: "fertilization", guessed: false, example: "Fertilization helps plants grow better"},
    {word: "парниковий ефект", translation: "greenhouse effect", guessed: false, example: "The greenhouse effect warms the planet"},
    {word: "озон", translation: "ozone", guessed: false, example: "Ozone protects us from UV radiation"},
    {word: "нешкідливий для озонового шару", translation: "ozone friendly", guessed: false, example: "These products are ozone friendly"},
    {word: "озоновий шар", translation: "ozone layer", guessed: false, example: "The ozone layer is depleting"},
    {word: "папір", translation: "paper", guessed: false, example: "Recycled paper saves trees"},
    {word: "пестицид", translation: "pesticide", guessed: false, example: "Pesticide use must be controlled"},
    {word: "пластик", translation: "plastics", guessed: false, example: "Plastics are a major pollution source"},
    {word: "забруднений", translation: "polluted", guessed: false, example: "The river is heavily polluted"},
    {word: "забруднена вода", translation: "polluted water", guessed: false, example: "Polluted water is unsafe to drink"},
    {word: "забруднення", translation: "pollution", guessed: false, example: "Pollution affects health and environment"},
    {word: "зникаючий вид", translation: "protected species", guessed: false, example: "Laws protect endangered species"},
    {word: "що піддається переробці", translation: "recyclable", guessed: false, example: "Recyclable materials reduce waste"},
    {word: "рециклізація", translation: "recycling", guessed: false, example: "Recycling helps reduce pollution"},
    {word: "поновлюваний", translation: "renewable", guessed: false, example: "Solar energy is a renewable resource"},
    {word: "поновлювальне джерело енергії", translation: "renewable energy source", guessed: false, example: "Wind power is a renewable energy source"},
    {word: "багаторазового використання", translation: "reusable", guessed: false, example: "Use reusable bags to reduce waste"},
    {word: "сміття", translation: "rubbish", guessed: false, example: "Please take the rubbish out"},
    {word: "сміттєзвалище", translation: "rubbish dump", guessed: false, example: "The rubbish dump is full"},
    {word: "металолом", translation: "scrap metal", guessed: false, example: "Scrap metal can be recycled"},
    {word: "поділ", translation: "segregation", guessed: false, example: "Waste segregation is important"},
    {word: "стічні води", translation: "sewage", guessed: false, example: "Sewage treatment is essential for health"},
    {word: "очисні споруди", translation: "sewage treatment plant", guessed: false, example: "The sewage treatment plant is new"},
    {word: "смог", translation: "smog", guessed: false, example: "Smog is a serious urban problem"},
    {word: "зрубувати дерево", translation: "to chop down a tree", guessed: false, example: "They plan to chop down a tree"},
    {word: "забруднювати", translation: "to contaminate", guessed: false, example: "Factories can contaminate local water supplies"},
    {word: "вирубувати ліси", translation: "to deforest", guessed: false, example: "Companies deforest large areas for timber"},
    {word: "зрізати дерево", translation: "to fell a tree", guessed: false, example: "Permission is needed to fell a tree"},
    {word: "удобрювати", translation: "to fertilise", guessed: false, example: "Farmers fertilise fields to boost crops"},
    {word: "забруднювати", translation: "to pollute", guessed: false, example: "Cars and factories pollute the air"},
    {word: "розділяти сміття", translation: "to sort waste", guessed: false, example: "We need to sort waste for recycling"},
    {word: "виробляти енергію", translation: "to yield power", guessed: false, example: "Wind turbines yield power for homes"},
    {word: "відходи", translation: "waste", guessed: false, example: "Waste needs to be managed properly"},
    {word: "макулатура", translation: "waste paper", guessed: false, example: "Recycling waste paper helps the environment"},
    {word: "сортування сміття", translation: "waste sorting", guessed: false, example: "Waste sorting is required by law"}
]


