export const irrverbs = [
    {word: 'Бути', translation: 'be-was-were-been', guessed: false, example: "He has been a great friend for years"},
    {word: 'Бити', translation: 'beat-beat-beaten', guessed: false, example: "He beat a record in the last race"},
    {word: 'Ставати', translation: 'become-became-become', guessed: false, example: "She became a successful artist"},
    {word: 'Починати', translation: 'begin-began-begun', guessed: false, example: "They began the project last week"},
    {word: 'Дути', translation: 'blow-blew-blown', guessed: false, example: "The wind blew all night long"},
    {word: 'Ламати', translation: 'break-broke-broken', guessed: false, example: "I broke my phone yesterday"},
    {word: 'Приносити', translation: 'bring-brought-brought', guessed: false, example: "She brought me a delicious cake"},
    {word: 'Будувати', translation: 'build-built-built', guessed: false, example: "They have built a new bridge"},
    {word: 'Горіти', translation: 'burn-burnt-burnt', guessed: false, example: "A fire burnt all night in the fireplace"},
    {word: 'Купувати', translation: 'buy-bought-bought', guessed: false, example: "I bought a new laptop yesterday"},
    {word: 'Ловити', translation: 'catch-caught-caught', guessed: false, example: "He caught a ball during the game"},
    {word: 'Вибирати', translation: 'choose-chose-chosen', guessed: false, example: "I have chosen my new shoes"},
    {word: 'Приходити', translation: 'come-came-come', guessed: false, example: "She came to the party last night"},
    {word: 'Різати', translation: 'cut-cut-cut', guessed: false, example: "He cut the paper into pieces"},
    {word: 'Робити', translation: 'do-did-done', guessed: false, example: "I have done all my homework"},
    {word: 'Малювати', translation: 'draw-drew-drawn', guessed: false, example: "He drew a beautiful landscape"},
    {word: 'Мріяти', translation: 'dream-dreamt-dreamt', guessed: false, example: "I dreamt about flying last night"},
    {word: 'Пити', translation: 'drink-drank-drunk', guessed: false, example: "She drank a cup of coffee this morning"},
    {word: 'Водити', translation: 'drive-drove-driven', guessed: false, example: "He drove a car all the way"},
    {word: 'Їсти', translation: 'eat-ate-eaten', guessed: false, example: "I have eaten breakfast already"},
    {word: 'Падати', translation: 'fall-fell-fallen', guessed: false, example: "He fell off the ladder while painting"},
    {word: 'Годувати', translation: 'feed-fed-fed', guessed: false, example: "She fed a cat in the morning"},
    {word: 'Відчувати', translation: 'feel-felt-felt', guessed: false, example: "I felt so tired after the long walk"},
    {word: 'Боротися', translation: 'fight-fought-fought', guessed: false, example: "They fought bravely in the war"},
    {word: 'Знаходити', translation: 'find-found-found', guessed: false, example: "He found his wallet in the park"},
    {word: 'Підходити', translation: 'fit-fit-fit', guessed: false, example: "The dress fit perfectly"},
    {word: 'Літати', translation: 'fly-flew-flown', guessed: false, example: "She flew to London last week"},
    {word: 'Забувати', translation: 'forget-forgot-forgotten', guessed: false, example: "I forgot my keys at home"},
    {word: 'Прощати', translation: 'forgive-forgave-forgiven', guessed: false, example: "She forgave him for his mistake"},
    {word: 'Замерзати', translation: 'freeze-froze-frozen', guessed: false, example: "The lake has frozen completely"},
    {word: 'Отримувати', translation: 'get-got-got', guessed: false, example: "I got a new job offer today"},
    {word: 'Давати', translation: 'give-gave-given', guessed: false, example: "He gave me a gift for my birthday"},
    {word: 'Йти', translation: 'go-went-gone', guessed: false, example: "They have gone to the cinema"},
    {word: 'Зростати', translation: 'grow-grew-grown', guessed: false, example: "The plant has grown significantly"},
    {word: 'Вішати', translation: 'hang-hung-hung', guessed: false, example: "He hung the picture on the wall"},
    {word: 'Мати', translation: 'have-had-had', guessed: false, example: "I had a delicious meal last night"},
    {word: 'Слухати', translation: 'hear-heard-heard', guessed: false, example: "I heard the news this morning"},
    {word: 'Ховати', translation: 'hide-hid-hidden', guessed: false, example: "She hid the gift under the bed"},
    {word: 'Вдарити', translation: 'hit-hit-hit', guessed: false, example: "He hit the ball with a bat"},
    {word: 'Тримати', translation: 'hold-held-held', guessed: false, example: "She held the baby in her arms"},
    {word: 'Робити боляче', translation: 'hurt-hurt-hurt', guessed: false, example: "I hurt my knee while playing"},
    {word: 'Утримувати', translation: 'keep-kept-kept', guessed: false, example: "I have kept this secret for years"},
    {word: 'Знати', translation: 'know-knew-known', guessed: false, example: "I knew an answer to the question"},
    {word: 'Класти', translation: 'lay-laid-laid', guessed: false, example: "She laid the table for dinner"},
    {word: 'Вести', translation: 'lead-led-led', guessed: false, example: "He led the team to victory"},
    {word: 'Нахилятися', translation: 'lean-leant-leant', guessed: false, example: "She leant against the wall"},
    {word: 'Вчити', translation: 'learn-learnt-learnt', guessed: false, example: "I have learnt a lot from this book"},
    {word: 'Залишати', translation: 'leave-left-left', guessed: false, example: "She left the party early"},
    {word: 'Давати в борг', translation: 'lend-lent-lent', guessed: false, example: "He lent me his car for the weekend"},
    {word: 'Дозволяти', translation: 'let-let-let', guessed: false, example: "She let me borrow her book"},
    {word: 'Лежати', translation: 'lie-lay-lain', guessed: false, example: "He lay on the grass and looked at the sky"},
    {word: 'Втрачати', translation: 'lose-lost-lost', guessed: false, example: "I lost my keys this morning"},
    {word: 'Виробляти', translation: 'make-made-made', guessed: false, example: "She made a delicious cake for dinner"},
    {word: 'Мати на увазі', translation: 'mean-meant-meant', guessed: false, example: "I meant to call you earlier"},
    {word: 'Зустрічати', translation: 'meet-met-met', guessed: false, example: "I met him at the conference last year"},
    {word: 'Помилятися', translation: 'mistake-mistook-mistaken', guessed: false, example: "I mistook her for someone else"},
    {word: 'Платити', translation: 'pay-paid-paid', guessed: false, example: "I paid the bill yesterday"},
    {word: 'Доводити', translation: 'prove-proved-proven', guessed: false, example: "He proved his theory was correct"},
    {word: 'Покласти', translation: 'put-put-put', guessed: false, example: "I put the keys on a table"},
    {word: 'Виходити', translation: 'quit-quit-quit', guessed: false, example: "She quit her job last month"},
    {word: "Читати", translation: "read-read-read", guessed: false, example: "I read an interesting book last night"},
    {word: "Дзвонити", translation: "ring-rang-rung", guessed: false, example: "The phone rang just as I was leaving"},
    {word: "Підніматися", translation: "rise-rose-risen", guessed: false, example: "The sun rose early this morning"},
    {word: "Бігти", translation: "run-ran-run", guessed: false, example: "She ran to catch the bus"},
    {word: "Говорити", translation: "say-said-said", guessed: false, example: "He said he would come tomorrow"},
    {word: "Бачити", translation: "see-saw-seen", guessed: false, example: "I saw a beautiful bird in the park"},
    {word: "Шукати", translation: "seek-sought-sought", guessed: false, example: "They sought help from the teacher"},
    {word: "Продавати", translation: "sell-sold-sold", guessed: false, example: "She sold her car last week"},
    {word: "Надсилати", translation: "send-sent-sent", guessed: false, example: "He sent me a postcard from Paris"},
    {word: "Встановлювати", translation: "set-set-set", guessed: false, example: "I set the table for dinner"},
    {word: "Трясти", translation: "shake-shook-shaken", guessed: false, example: "He shook hands with the guest"},
    {word: "Показувати", translation: "show-showed-shown", guessed: false, example: "She showed me her new dress"},
    {word: "Закривати", translation: "shut-shut-shut", guessed: false, example: "He shut the door quietly"},
    {word: "Співати", translation: "sing-sang-sung", guessed: false, example: "They sang a beautiful song together"},
    {word: "Тонути", translation: "sink-sank-sunk", guessed: false, example: "A ship sank in the storm"},
    {word: "Сидіти", translation: "sit-sat-sat", guessed: false, example: "He sat by the window and read"},
    {word: "Спати", translation: "sleep-slept-slept", guessed: false, example: "I slept for eight hours last night"},
    {word: "Ковзати", translation: "slide-slid-slid", guessed: false, example: "He slid down the icy hill"},
    {word: "Говорити", translation: "speak-spoke-spoken", guessed: false, example: "She spoke to him about the project"},
    {word: "Промовляти по буквах", translation: "spell-spelt-spelt", guessed: false, example: "He spelt his name for the officer"},
    {word: "Витрачати", translation: "spend-spent-spent", guessed: false, example: "She spent the weekend with her family"},
    {word: "Розливати", translation: "spill-spilt-spilt", guessed: false, example: "I spilt coffee on my shirt"},
    {word: "Псувати", translation: "spoil-spoilt-spoilt", guessed: false, example: "The rain spoiled our picnic"},
    {word: "Поширювати", translation: "spread-spread-spread", guessed: false, example: "He spread butter on his toast"},
    {word: "Стояти", translation: "stand-stood-stood", guessed: false, example: "They stood in line for the concert"},
    {word: "Красти", translation: "steal-stole-stolen", guessed: false, example: "Someone stole my bike last night"},
    {word: "Плавати", translation: "swim-swam-swum", guessed: false, example: "He swam across the lake this morning"},
    {word: "Брати", translation: "take-took-taken", guessed: false, example: "She took the last piece of cake"},
    {word: "Вчити", translation: "teach-taught-taught", guessed: false, example: "He taught English for ten years"},
    {word: "Рвати", translation: "tear-tore-torn", guessed: false, example: "I tore the paper in half"},
    {word: "Розповідати", translation: "tell-told-told", guessed: false, example: "She told him about the surprise party"},
    {word: "Думати", translation: "think-thought-thought", guessed: false, example: "I thought about the problem for hours"},
    {word: "Кидати", translation: "throw-threw-thrown", guessed: false, example: "He threw a ball across the field"},
    {word: "Розуміти", translation: "understand-understood-understood", guessed: false, example: "She understood the concept quickly"},
    {word: "Просинатися", translation: "wake-woke-woken", guessed: false, example: "I woke up early this morning"},
    {word: "Носити", translation: "wear-wore-worn", guessed: false, example: "She wore a beautiful dress to the party"},
    {word: "Плакати", translation: "weep-wept-wept", guessed: false, example: "He wept tears of joy"},
    {word: "Змочити", translation: "wet-wet-wet", guessed: false, example: "The rain wet my clothes completely"},
    {word: "Вигравати", translation: "win-won-won", guessed: false, example: "Our team won the championship"},
    {word: "Писати", translation: "write-wrote-written", guessed: false, example: "She wrote a letter to her friend"}
]