export const verbs_think = [
    {word: "читати", translation: "read", guessed: false, example: "She will read the new novel during her weekend"},
    {word: "писати", translation: "write", guessed: false, example: "The students will write essays for their English assignment"},
    {word: "слухати", translation: "listen", guessed: false, example: "She likes to listen to music while she works"},
    {word: "чути", translation: "hear", guessed: false, example: "He heard a bird chirping outside his window"},
    {word: "бачити", translation: "see", guessed: false, example: "Visitors can see various animals in their natural habitat"},
    {word: "спостерігати", translation: "watch", guessed: false, example: "She will watch a movie with her friends"},
    {word: "глянути", translation: "look", guessed: false, example: "He decided to look for a new book at the bookstore"},
    {word: "вчитися", translation: "study", guessed: false, example: "She will study for an exam to understand the material"},
    {word: "вивчати", translation: "learn", guessed: false, example: "He wants to learn a new language to broaden his skills"},
    {word: "рахувати", translation: "count", guessed: false, example: "She will count the number of books on a shelf"},
    {word: "обчислювати", translation: "calculate", guessed: false, example: "He needs to calculate the total cost of his purchases"},
    {word: "додавати", translation: "add", guessed: false, example: "She will add the numbers together to find a total"},
    {word: "віднімати", translation: "subtract", guessed: false, example: "You need to subtract the smaller number from a larger one"},
    {word: "ділити", translation: "divide", guessed: false, example: "To split the pizza equally, we need to divide it"},
    {word: "множити", translation: "multiply", guessed: false, example: "Students learn how to multiply numbers using techniques"},
    {word: "виправляти", translation: "correct", guessed: false, example: "She will correct the spelling errors in a document"},
    {word: "обробляти", translation: "process", guessed: false, example: "He needs to process the data before creating a report"},
    {word: "редагувати", translation: "edit", guessed: false, example: "She will edit the essay to improve clarity and structure"},
    {word: "знати", translation: "know", guessed: false, example: "She will know more about the latest industry trends"},
    {word: "усвідомлювати", translation: "aware", guessed: false, example: "It is crucial to stay aware of market changes"},
    {word: "пояснювати", translation: "explain", guessed: false, example: "She will explain the process step by step"},
    {word: "виражати", translation: "express", guessed: false, example: "He used art to express his emotions"},
    {word: "винаходити", translation: "invent", guessed: false, example: "The scientist aimed to invent a machine to purify water"},
    {word: "розробляти", translation: "develop", guessed: false, example: "The inventor worked hard to develop renewable energy"},
    {word: "зрозуміти", translation: "understand", guessed: false, example: "She will understand the concept after study"},
    {word: "усвідомити", translation: "realize", guessed: false, example: "It took him time to realize the impact of his actions"},
    {word: "означати", translation: "mean", guessed: false, example: "His gesture may not mean much to others, but it impacted her"},
    {word: "май на увазі", translation: "keep in mind", guessed: false, example: "It's essential to keep in mind the long-term consequences"},
    {word: "перекладати", translation: "translate", guessed: false, example: "She will translate the document from English to French"},
    {word: "припускати", translation: "suppose", guessed: false, example: "She will suppose the meeting will start at 2 PM"},
    {word: "допускати", translation: "assume", guessed: false, example: "He will assume the package will arrive overnight"},
    {word: "думати", translation: "think", guessed: false, example: "She likes to think deeply about problems"},
    {word: "аналізувати", translation: "analyze", guessed: false, example: "He will analyze the data to draw conclusions"},
    {word: "експериментувати", translation: "experiment", guessed: false, example: "Students experiment with chemicals to observe reactions"},
    {word: "пам'ятати", translation: "remember", guessed: false, example: "She will try hard to remember details for the exam"},
    {word: "забувати", translation: "forget", guessed: false, example: "He forgot his keys before leaving the house"},
    {word: "дізнаватися/з'ясовувати", translation: "find out", guessed: false, example: "She will research to find out more about the event"},
    {word: "досліджувати", translation: "research", guessed: false, example: "She will research the effects of climate change"},
    {word: "відкривати (щось нове)", translation: "discover", guessed: false, example: "He discovered a new species of flower in the forest"},
    {word: "розглядати", translation: "consider", guessed: false, example: "She will consider options before choosing a college"},
    {word: "порівнювати", translation: "compare", guessed: false, example: "She will compare prices before making a purchase"},
    {word: "розрізняти", translation: "distinguish", guessed: false, example: "He can distinguish between similar-looking birds"},
    {word: "спостерігати", translation: "observe", guessed: false, example: "She will observe bird behavior in their habitat"},
    {word: "описувати", translation: "describe", guessed: false, example: "He can describe the mountain in great detail"},
    {word: "розпізнавати", translation: "recognize", guessed: false, example: "She could still recognize her friend in the crowd"},
    {word: "вирішувати", translation: "decide", guessed: false, example: "She needs to decide which college to attend"},
    {word: "робити висновок", translation: "conclude", guessed: false, example: "He concluded the best action was to accept a job"},
    {word: "переказати", translation: "retell", guessed: false, example: "She will retell the story in her own words"},
    {word: "перепитувати", translation: "ask again", guessed: false, example: "He will ask again for clarification about the assignment"},
    {word: "перефразовувати", translation: "rephrase", guessed: false, example: "She needs to rephrase the sentence for clarity"},
    {word: "стосуватися/відноситися/ставитися", translation: "relate", guessed: false, example: "She will relate an events to the present context"},
    {word: "навчати", translation: "teach", guessed: false, example: "A teacher tried to teach the students teamwork"},
    {word: "тренувати", translation: "train", guessed: false, example: "To become skilled, it is essential to train regularly"},
    {word: "доводити", translation: "prove", guessed: false, example: "A scientist conducted tests to prove the hypothesis"},
    {word: "заучувати", translation: "memorize", guessed: false, example: "She decided to memorize key points for the speech"},
    {word: "переконувати", translation: "convince", guessed: false, example: "She used arguments to convince her friends to join"},
    {word: "перевіряти", translation: "examine", guessed: false, example: "Scientists examine samples under the microscope"},
    {word: "описувати", translation: "describe", guessed: false, example: "He asked her to describe the beautiful sunset"},
    {word: "очікувати", translation: "expect", guessed: false, example: "She expects to receive good grades after studying"},
    {word: "брати до уваги", translation: "take into account", guessed: false, example: "It is crucial to take into account all preferences"},
    {word: "передумати", translation: "change the mind", guessed: false, example: "She decided to change her mind about the project"},
    {word: "підготовуватися", translation: "prepare", guessed: false, example: "She likes to prepare a healthy breakfast every morning"}
]