export const verbs_work = [
    {word: "переносити", translation: "carry", guessed: false, example: "He likes to carry a backpack when he goes hiking"},
    {word: "здійснювати", translation: "fulfill", guessed: false, example: "She worked hard to fulfill her dream"},
    {word: "робити", translation: "do", guessed: false, example: "She will do her homework after school"},
    {word: "зробити", translation: "make", guessed: false, example: "He will make a sandwich for lunch"},
    {word: "змішувати", translation: "mix", guessed: false, example: "She will mix the ingredients to make a cake"},
    {word: "псувати", translation: "spoil", guessed: false, example: "Leaving food out in the sun can spoil it"},
    {word: "кидати", translation: "throw", guessed: false, example: "She will throw the ball to her teammate"},
    {word: "падати", translation: "drop", guessed: false, example: "Be careful not to drop the glass"},
    {word: "керувати", translation: "manage", guessed: false, example: "She will manage the team to complete a project"},
    {word: "обробляти", translation: "handle", guessed: false, example: "He needs to handle the situation diplomatically"},
    {word: "полірувати", translation: "polish", guessed: false, example: "He likes to polish his shoes before events"},
    {word: "cпробувати", translation: "try", guessed: false, example: "She will try a new recipe for dinner"},
    {word: "запобігти", translation: "prevent", guessed: false, example: "The alarm system helps prevent unauthorized access"},
    {word: "вирішувати(задачу)", translation: "solve", guessed: false, example: "She will solve the math problem"},
    {word: "розв'язувати(проблему)", translation: "resolve", guessed: false, example: "He aims to resolve the conflict through communication"},
    {word: "спеціалізуватися", translation: "specialize", guessed: false, example: "He chose to specialize as a programmer"},
    {word: "підсвічувати", translation: "highlight", guessed: false, example: "She decided to highlight the room with lights"},
    {word: "отримати", translation: "retrieve", guessed: false, example: "He will retrieve the information from a database"},
    {word: "відтворити", translation: "recreate", guessed: false, example: "She will recreate the famous painting"},
    {word: "налагодити", translation: "rectify", guessed: false, example: "The IT department worked to rectify a issue"},
    {word: "виправити", translation: "fix", guessed: false, example: "I will fix this error today"},
    {word: "зав'язувати", translation: "tie", guessed: false, example: "He is learning how to tie his shoes"},
    {word: "анулювати/скасувати", translation: "undo", guessed: false, example: "She had to undo the last few edits"},
    {word: "застебнути", translation: "fasten", guessed: false, example: "Please fasten your helmet for safety"},
    {word: "будувати", translation: "build", guessed: false, example: "They plan to build a new house"},
    {word: "розстебнути", translation: "unfasten", guessed: false, example: "She decided to unfasten the buttons for comfort"},
    {word: "зварювати", translation: "weld", guessed: false, example: "He welded the metal pieces together"},
    {word: "приклеювати", translation: "stick", guessed: false, example: "He used glue to stick the pieces of paper together"},
    {word: "замінювати", translation: "substitute", guessed: false, example: "You can substitute butter with oil"},
    {word: "змочувати", translation: "moisten", guessed: false, example: "Moisten a stamp to activate the adhesive"},
    {word: "прибити цвях", translation: "nail", guessed: false, example: "To fix the picture he decided to nail it back"},
    {word: "проколоти", translation: "spike", guessed: false, example: "He used a nail to spike the wooden plank"},
    {word: "піднімати", translation: "pick up", guessed: false, example: "She helped pick up the toys after a party"},
    {word: "натирати", translation: "rub", guessed: false, example: "She needed to rub her hands to remove the sand"},
    {word: "пилити", translation: "saw", guessed: false, example: "He sawed the tree to create logs"},
    {word: "розкидати", translation: "scatter", guessed: false, example: "A wind scattered the leaves"},
    {word: "зішкрібати", translation: "scrape", guessed: false, example: "He accidentally scraped his car against the fence"},
    {word: "подряпати", translation: "scratch", guessed: false, example: "The cat likes to scratch its claws on a tree"},
    {word: "закручувати", translation: "screw", guessed: false, example: "He needed a screwdriver to screw the shelves"},
    {word: "упіймати", translation: "catch", guessed: false, example: "She tried to catch the ball but missed"},
    {word: "розсипати", translation: "spill", guessed: false, example: "Be careful not to spill the coffee"},
    {word: "змонтувати", translation: "assemble", guessed: false, example: "He followed instructions to assemble the bookshelf"},
    {word: "розбирати", translation: "disassemble", guessed: false, example: "They had to disassemble the furniture for moving"},
    {word: "проводити", translation: "conduct", guessed: false, example: "The scientist decided to conduct experiments"},
    {word: "знищувати", translation: "destroy", guessed: false, example: "He accidentally destroyed the document"},
    {word: "зносити", translation: "demolish", guessed: false, example: "The city decided to demolish an old bridge"},
    {word: "розбавляти", translation: "dilute", guessed: false, example: "Please dilute the juice with water"}
]
