export const verbs_everyday = [
    {word: "їсти", translation: "eat", guessed: false, example: "She likes to eat apples for a snack"},
    {word: "пити", translation: "drink", guessed: false, example: "He drinks a glass of water after exercising"},
    {word: "ковтати", translation: "swallow", guessed: false, example: "She accidentally swallowed a bug while drinking water"},
    {word: "різати", translation: "cut", guessed: false, example: "She used a sharp knife to cut vegetables"},
    {word: "кусати", translation: "bite", guessed: false, example: "The toddler tried to bite an apple"},
    {word: "бити", translation: "beat", guessed: false, example: "He used a spoon to beat eggs for the omelet"},
    {word: "випікати", translation: "bake", guessed: false, example: "She likes to bake cookies on weekends"},
    {word: "жарити", translation: "fry", guessed: false, example: "He fries eggs for breakfast every morning"},
    {word: "варити", translation: "boil", guessed: false, example: "Boil the water before adding pasta"},
    {word: "тушкувати", translation: "stew", guessed: false, example: "She decided to stew beef for dinner"},
    {word: "заснути", translation: "fall asleep", guessed: false, example: "After a long day I fall asleep quickly"},
    {word: "спати", translation: "sleep", guessed: false, example: "She likes to sleep early"},
    {word: "пробуджуватися", translation: "wake up", guessed: false, example: "He wakes up feeling refreshed"},
    {word: "йти в ліжко", translation: "go to bed", guessed: false, example: "She goes to bed at 10 PM every night"},
    {word: "мити/прати", translation: "wash", guessed: false, example: "She washes her hands before a meal"},
    {word: "прасувати", translation: "iron", guessed: false, example: "She will iron her clothes before the meeting"},
    {word: "одягатися", translation: "dress up", guessed: false, example: "She will dress up for the costume party"},
    {word: "носити одяг", translation: "wear", guessed: false, example: "She will wear a red dress for the party"},
    {word: "наливати", translation: "pour", guessed: false, example: "She will pour a tea into the cup"},
    {word: "висушувати", translation: "dry", guessed: false, example: "Hang the clothes outside to dry"},
    {word: "володіти", translation: "possess", guessed: false, example: "She will possess the skills to excel"},
    {word: "належати", translation: "belong", guessed: false, example: "The clock belongs to a family"},
    {word: "замикати(на ключ)", translation: "lock", guessed: false, example: "She will lock the door before leaving"},
    {word: "пригощати", translation: "treat", guessed: false, example: "He decided to treat his friends to dinner"},
    {word: "встановити", translation: "set", guessed: false, example: "She will set the table for dinner"},
    {word: "перебувати", translation: "stay", guessed: false, example: "The hotel offers comfortable rooms to stay"},
    {word: "поставити", translation: "put", guessed: false, example: "Put your backpack on the chair"},
    {word: "покласти", translation: "lay", guessed: false, example: "Lay the book on a table"},
    {word: "увімкнути", translation: "turn on", guessed: false, example: "Turn on the lights before sunset"},
    {word: "активувати", translation: "enable", guessed: false, example: "Please enable notifications on your phone"},
    {word: "вимкнути", translation: "turn off", guessed: false, example: "Turn off the lights before leaving"},
    {word: "деактивувати", translation: "disable", guessed: false, example: "Disable an alarm by entering the code"},
    {word: "складатися з", translation: "consist of", guessed: false, example: "The salad consists of greens, tomatoes, cucumbers"},
    {word: "відбирати(серед чогось)", translation: "select", guessed: false, example: "She will select the best option"},
    {word: "вибирати", translation: "choose", guessed: false, example: "He needs to choose a location for the event"},
    {word: "одягати", translation: "put on", guessed: false, example: "She likes to put on her sweater before heading out"},
    {word: "макіяж", translation: "make up", guessed: false, example: "She enjoys experimenting with makeup looks"},
    {word: "підходити/пасувати(про одяг)", translation: "suit", guessed: false, example: "She suited up for the job interview"},
    {word: "вирізати", translation: "cut out", guessed: false, example: "Cut out the shape along a lines"},
    {word: "знімати", translation: "take off", guessed: false, example: "Take off your jacket when it gets warm"},
    {word: "прокинутися зі сну", translation: "wake up", guessed: false, example: "I wake up to birds chirping"},
    {word: "робити завивку", translation: "perm", guessed: false, example: "She decided to perm her hair for a curly look"},
    {word: "вставати з ліжка", translation: "get out of bed", guessed: false, example: "It takes effort to get out of bed"},
    {word: "підходити(про одяг)", translation: "fit", guessed: false, example: "The dress fit perfectly"},
    {word: "вставати", translation: "get up", guessed: false, example: "He struggles to get up early every day"},
    {word: "шити", translation: "sew", guessed: false, example: "She likes to sew unique clothing items"},
    {word: "відпочивати", translation: "rest", guessed: false, example: "She likes to rest with a good book"},
    {word: "дихати", translation: "breathe", guessed: false, example: "Take a deep breath to calm down"},
    {word: "годувати", translation: "feed", guessed: false, example: "She feeds her cat every morning"},
    {word: "жувати", translation: "chew", guessed: false, example: "Chew your food carefully"},
    {word: "голитися", translation: "shave", guessed: false, example: "He shaves before heading to work"},
    {word: "чистити зуби", translation: "brush teeth", guessed: false, example: "Brush your teeth before bed"},
    {word: "готувати", translation: "cook", guessed: false, example: "She loves to cook for her family"},
    {word: "сідати", translation: "sit", guessed: false, example: "She likes to sit near the window"},
    {word: "витрачати", translation: "spend", guessed: false, example: "They spend time exploring new places"},
    {word: "псувати", translation: "spoil", guessed: false, example: "He spoiled tools trying to fix the table"},
    {word: "стояти", translation: "stand", guessed: false, example: "People often stand at concerts"},
    {word: "зберігати", translation: "store", guessed: false, example: "She stores produce in the refrigerator"},
    {word: "консервувати", translation: "preserve", guessed: false, example: "Preserve fruits by making jams"}
]