export const verbs_tech = [
    {word: "відстежувати", translation: "track", guessed: false, example: "He will track his daily steps using a fitness app"},
    {word: "вставити", translation: "insert", guessed: false, example: "She will insert a new paragraph into the document"},
    {word: "помістити", translation: "paste", guessed: false, example: "He will paste a copied text into the email"},
    {word: "копіювати", translation: "copy", guessed: false, example: "She will copy the text from a website for her research"},
    {word: "оновити", translation: "update", guessed: false, example: "She will update the software to a latest version"},
    {word: "освіжити", translation: "refresh", guessed: false, example: "After making changes, you may need to refresh the website"},
    {word: "перезавантажити", translation: "reload", guessed: false, example: "The laptop was reloaded very fast"},
    {word: "відкочувати", translation: "rollback", guessed: false, example: "They decided to rollback to the previous version after an issue"},
    {word: "прокручувати", translation: "scroll", guessed: false, example: "To read the article scroll down using the mouse"},
    {word: "перегортати", translation: "swipe", guessed: false, example: "You can swipe left or right to navigate on a touchscreen"},
    {word: "поширювати", translation: "spread", guessed: false, example: "They aim to spread awareness about environmental conservation"},
    {word: "розповсюджувати", translation: "distribute", guessed: false, example: "The company will distribute products to various locations"},
    {word: "реставрувати", translation: "restore", guessed: false, example: "She will restore the old painting to its original condition"},
    {word: "відновлювати", translation: "recover", guessed: false, example: "He aims to recover the lost files from his computer"},
    {word: "створювати", translation: "create", guessed: false, example: "She will create a beautiful piece of artwork"},
    {word: "генерувати", translation: "generate", guessed: false, example: "He used to generate innovative ideas for projects"},
    {word: "роздвинути", translation: "expand", guessed: false, example: "She plans to expand her business to new markets"},
    {word: "розширити", translation: "extend", guessed: false, example: "He wants to extend the deadline for more time"},
    {word: "втілювати", translation: "implement", guessed: false, example: "She will implement the new system to improve efficiency"},
    {word: "навести (над чимось)", translation: "hover", guessed: false, example: "Move a mouse to hover over the page title"},
    {word: "масштабувати", translation: "zoom", guessed: false, example: "She will zoom in on the image to look carefully"},
    {word: "відправити", translation: "send", guessed: false, example: "She will send an email with the updated report"},
    {word: "виявити", translation: "detect", guessed: false, example: "The system can detect unauthorized access to a building"},
    {word: "передавати (дані)", translation: "transmit", guessed: false, example: "The tower will transmit a signal across a wide area"},
    {word: "транслювати", translation: "broadcast", guessed: false, example: "A radio station will broadcast the news at noon"},
    {word: "торкнутися (екрану)", translation: "tap", guessed: false, example: "She will tap on a screen to open the application"},
    {word: "натиснути (клавішу)", translation: "press", guessed: false, example: "He needs to press a button to turn on the device"},
    {word: "доторкатися", translation: "touch", guessed: false, example: "They can touch a screen to activate the tablet"},
    {word: "клацнути (мишкою)", translation: "click", guessed: false, example: "He needs to click a mouse to interact with the software"},
    {word: "обробляти", translation: "process", guessed: false, example: "Workers carefully process raw materials into products"},
    {word: "призначати", translation: "assign", guessed: false, example: "They will assign tasks to each team member"},
    {word: "авторизовуватися", translation: "login", guessed: false, example: "Please enter your username and password to login"},
    {word: "зареєструватися", translation: "signup", guessed: false, example: "She will signup for the workshop to enhance her skills"},
    {word: "відправити", translation: "submit", guessed: false, example: "He needs to submit a report by the end of this day"}
]
