export const verbs_feels = [
    {word: "подобатися", translation: "like", guessed: false, example: "She likes to read books in her free time"},
    {word: "неподобатися", translation: "dislike", guessed: false, example: "He dislikes eating vegetables"},
    {word: "кохати", translation: "love", guessed: false, example: "She loves spending time with her family during the holidays"},
    {word: "ненавидіти", translation: "hate", guessed: false, example: "He hates it when his computer crashes during work"},
    {word: "закохатися", translation: "fall in love", guessed: false, example: "They fell in love at first sight"},
    {word: "захоплюватися", translation: "admire", guessed: false, example: "She admires her grandmother's wisdom and strength"},
    {word: "насолоджуватися", translation: "enjoy", guessed: false, example: "He enjoys reading books in his free time"},
    {word: "відчувати", translation: "feel", guessed: false, example: "She feels happy when she spends time with friends"},
    {word: "вагатися", translation: "hesitate", guessed: false, example: "She did not want to hesitate and miss the opportunity"},
    {word: "сумніватися", translation: "doubt", guessed: false, example: "He doubted an answer and asked the teacher"},
    {word: "сподіватися", translation: "hope", guessed: false, example: "She hopes for a better tomorrow"},
    {word: "вірити", translation: "believe", guessed: false, example: "He believes hard work leads to success"},
    {word: "розслаблятися", translation: "relax", guessed: false, example: "After work, she likes to relax by reading"},
    {word: "злитися", translation: "angry", guessed: false, example: "She became angry when her plans were canceled"},
    {word: "кричати", translation: "scream", guessed: false, example: "She screamed when she saw the spider"},
    {word: "вигукувати", translation: "shout", guessed: false, example: "The coach had to shout instructions"},
    {word: "верещати", translation: "yell", guessed: false, example: "He started to yell to express his emotions"},
    {word: "пишатися", translation: "proud", guessed: false, example: "She felt proud after completing the project"},
    {word: "плакати", translation: "cry", guessed: false, example: "She tends to cry during emotional movies"},
    {word: "страждати", translation: "suffer", guessed: false, example: "Animals suffer when not treated well"},
    {word: "робити боляче", translation: "hurt", guessed: false, example: "Do not hurt others' feelings with unkind words"},
    {word: "ображати", translation: "offend", guessed: false, example: "She did not mean to offend anyone"},
    {word: "посміхатися", translation: "smile", guessed: false, example: "She could not help but smile at the puppy"},
    {word: "сміятися", translation: "laugh", guessed: false, example: "The joke made everyone laugh"},
    {word: "віддавати перевагу", translation: "prefer", guessed: false, example: "He prefers watching movies at home"},
    {word: "хотіти", translation: "want", guessed: false, example: "She wants to buy a new bicycle for her birthday"},
    {word: "турбуватися", translation: "worry", guessed: false, example: "She worries about her exams"},
    {word: "скаржитися", translation: "complain", guessed: false, example: "He complains about the long commute"},
    {word: "робити винним", translation: "blame", guessed: false, example: "He tends to blame others for his mistakes"},
    {word: "обвинувачувати", translation: "accuse", guessed: false, example: "She did not accuse anyone without evidence"},
    {word: "погоджуватися", translation: "agree", guessed: false, example: "They will agree on the project timelines"},
    {word: "сперечатися", translation: "argue", guessed: false, example: "Siblings often argue over trivial matters"},
    {word: "доводити(точку зору)", translation: "prove", guessed: false, example: "They proved their theory through experiments"},
    {word: "підозрювати", translation: "suspect", guessed: false, example: "He suspected something was wrong"},
    {word: "обожнювати", translation: "adore", guessed: false, example: "She adores spending weekends reading"},
    {word: "бути в збудженому настрої", translation: "excite", guessed: false, example: "The news of her promotion excited her"},
    {word: "цінувати", translation: "appreciate", guessed: false, example: "I appreciate your help with the project"},
    {word: "вагатися", translation: "hesitate", guessed: false, example: "She did not hesitate to express her thoughts"},
    {word: "не зважати", translation: "disregard", guessed: false, example: "He chose to disregard the safety guidelines"},
    {word: "здаватися", translation: "give up", guessed: false, example: "She refused to give up on her goal"},
    {word: "заспокоїтися", translation: "calm down", guessed: false, example: "It took time for the baby to calm down"},
    {word: "турбуватися", translation: "care", guessed: false, example: "She cares for her plants diligently"},
    {word: "заздрити", translation: "envy", guessed: false, example: "He envies his colleague's language skills"},
    {word: "хвалитися", translation: "boast", guessed: false, example: "His work speaks better than words"},
    {word: "налякати", translation: "scare", guessed: false, example: "A sudden noise scared the cat"},
    {word: "наполохати", translation: "frighten", guessed: false, example: "A sound in the alley frightened a child"},
    {word: "сварити", translation: "scold", guessed: false, example: "She scolded her brother for not finishing homework"},
    {word: "боятися", translation: "fear", guessed: false, example: "He fears the dark and sleeps with a night light"},
    {word: "поважати", translation: "respect", guessed: false, example: "He respects his elders advice"},
    {word: "хвалити", translation: "praise", guessed: false, example: "She praised her students for their hard work"},
    {word: "покладатися", translation: "rely", guessed: false, example: "She can rely on her friend for support"},
    {word: "несподіванно здивувати", translation: "surprise", guessed: false, example: "The gift surprised her on her birthday"},
    {word: "дивувати", translation: "astonish", guessed: false, example: "The magic tricks astonish an audience"},
    {word: "вражати(емоція)", translation: "amaze", guessed: false, example: "The acrobats' performance amazed everyone"},
    {word: "ухилятися", translation: "shirk", guessed: false, example: "He tried to shirk his responsibilities"},
    {word: "уникнути", translation: "avoid", guessed: false, example: "She tried to avoid this conversation"},
    {word: "капітулювати", translation: "surrender", guessed: false, example: "The soldiers had to surrender"},
    {word: "стояти", translation: "stand", guessed: false, example: "He decided to stand and wait for the bus"},
    {word: "витримувати", translation: "bear", guessed: false, example: "She could not bear the headache"},
    {word: "не могти витерпіти(роздратування)", translation: "can't stand", guessed: false, example: "I can not stand to be a loser"},
    {word: "терпіти", translation: "endure", guessed: false, example: "A community endured the challenges"},
    {word: "поранити", translation: "wound", guessed: false, example: "He accidentally wounded his hand"}
]
