export const verbs_work = [
    {word: "застосовувати", translation: "apply", guessed: false, example: "He will apply for the scholarship to pursue his studies"},
    {word: "прикріпляти", translation: "attach", guessed: false, example: "She will attach the files to an email before sending it"},
    {word: "з'єднувати", translation: "connect", guessed: false, example: "He needs to connect the printer to his computer to start printing"},
    {word: "переносити", translation: "carry", guessed: false, example: "He likes to carry a backpack when he goes hiking"},
    {word: "продовжувати (працювати)", translation: "continue", guessed: false, example: "She decided to continue working after a short break"},
    {word: "продовжувати (презентацію)", translation: "go on", guessed: false, example: "He will go on with the presentation after a brief interruption"},
    {word: "продовжувати (розробку)", translation: "proceed", guessed: false, example: "They will proceed with the development after resolving an issue"},
    {word: "контролювати", translation: "control", guessed: false, example: "She needs to control her emotions during the interview"},
    {word: "тестувати", translation: "test", guessed: false, example: "He will test the software for errors before release"},
    {word: "перевіряти", translation: "check", guessed: false, example: "She will check her work for mistakes before submitting"},
    {word: "переглядати", translation: "review", guessed: false, example: "She will review the document before presenting it"},
    {word: "верифікувати", translation: "verify", guessed: false, example: "He needs to verify the information before deciding"},
    {word: "валідувати", translation: "validate", guessed: false, example: "She will validate the data before a meeting"},
    {word: "підтверджувати", translation: "confirm", guessed: false, example: "He called to confirm the reservation"},
    {word: "пропустити", translation: "skip", guessed: false, example: "You can skip to the next level by pressing an arrow key"},
    {word: "оцінювати", translation: "estimate", guessed: false, example: "She will estimate the cost of a project"},
    {word: "виключати", translation: "exclude", guessed: false, example: "She will exclude irrelevant information from the report"},
    {word: "ізолювати", translation: "isolate", guessed: false, example: "They decided to isolate infected individuals from the group"},
    {word: "наповнювати", translation: "fill", guessed: false, example: "She will fill the glass with water"},
    {word: "фільтрувати", translation: "filter", guessed: false, example: "They use a filter to improve water quality"},
    {word: "знаходити", translation: "find", guessed: false, example: "She will find her keys in the living room"},
    {word: "ховати", translation: "hide", guessed: false, example: "He likes to hide his toys under the bed"},
    {word: "відрегулювати", translation: "adjust", guessed: false, example: "She needs to adjust the camera settings"},
    {word: "підігнати", translation: "fit", guessed: false, example: "He will try to fit the puzzle pieces together"},
    {word: "вирівнювати", translation: "align", guessed: false, example: "She will align the text to a left side"},
    {word: "виправляти", translation: "fix", guessed: false, example: "She needs to fix the broken chair leg"},
    {word: "ремонтувати", translation: "repair", guessed: false, example: "He will repair the leaky faucet"},
    {word: "підготовлювати", translation: "prepare", guessed: false, example: "She will prepare a meal for dinner"},
    {word: "використовувати", translation: "use", guessed: false, example: "He will use the pen to write a letter"},
    {word: "закривати (вікно)", translation: "close", guessed: false, example: "He needs to close the window before it rains"},
    {word: "замикати (двері)", translation: "shut", guessed: false, example: "He asked his brother to shut the door"},
    {word: "відкривати", translation: "open", guessed: false, example: "She will open the door to welcome a guest"},
    {word: "замінити", translation: "replace", guessed: false, example: "She will replace the old lightbulb"},
    {word: "змінити", translation: "change", guessed: false, example: "He wants to change the wall color"},
    {word: "обміняти", translation: "exchange", guessed: false, example: "They decided to exchange items for better performance"},
    {word: "тягнути", translation: "pull", guessed: false, example: "He pulled the door to open it"},
    {word: "штовхати", translation: "push", guessed: false, example: "She pushed a cart through the supermarket"},
    {word: "перекривати", translation: "overlap", guessed: false, example: "The schedules for these two events overlap"},
    {word: "накривати/прикривати/заміщати", translation: "cover", guessed: false, example: "I cover my teammate due on his vacation time"},
    {word: "будувати", translation: "build", guessed: false, example: "They plan to build a new house"},
    {word: "виконувати(дію)", translation: "perform", guessed: false, example: "She will perform the experiment to test her hypothesis"},
    {word: "виконувати(план)", translation: "execute", guessed: false, example: "He will execute a plan to launch the product"},
    {word: "втілити/виконати", translation: "carry out", guessed: false, example: "I decided to carry out the plan as discussed"},
    {word: "здійснювати", translation: "fulfill", guessed: false, example: "She worked hard to fulfill her dream"},
    {word: "зменшити", translation: "reduce", guessed: false, example: "She will reduce her screen time"},
    {word: "збільшити", translation: "increase", guessed: false, example: "He wants to increase his exercise"},
    {word: "покращити", translation: "improve", guessed: false, example: "To improve the taste, she added more seasoning"},
    {word: "розшукувати", translation: "search", guessed: false, example: "She will search for information online"},
    {word: "шукати", translation: "seek", guessed: false, example: "He decided to seek advice from a mentor"},
    {word: "об'єднувати", translation: "merge", guessed: false, example: "The companies decided to merge"},
    {word: "розколювати", translation: "split", guessed: false, example: "They will split the tasks for better efficiency"},
    {word: "прив'язувати", translation: "bind", guessed: false, example: "She will bind the pages to create a book"},
    {word: "обгортати", translation: "wrap", guessed: false, example: "She will wrap the gift in paper"},
    {word: "загортати", translation: "envelop", guessed: false, example: "She will envelop the letter and send it"},
    {word: "запрошувати", translation: "invite", guessed: false, example: "She will invite her friends to the party"},
    {word: "зустрічати", translation: "meet", guessed: false, example: "They plan to meet at a coffee shop"},
    {word: "представляти", translation: "introduce", guessed: false, example: "She will introduce her friend to the group"},
    {word: "діяти", translation: "act", guessed: false, example: "She will act as a leader"},
    {word: "оперувати", translation: "operate", guessed: false, example: "The engineer explained how to operate a machine"},
    {word: "ламати", translation: "break", guessed: false, example: "She dropped the vase and it broke into pieces"},
    {word: "починатися", translation: "begin", guessed: false, example: "She will begin her journey"},
    {word: "закінчуватися", translation: "end", guessed: false, example: "The road ends in a few meters"},
    {word: "робити", translation: "do", guessed: false, example: "She will do her homework after school"},
    {word: "зробити", translation: "make", guessed: false, example: "He will make a sandwich for lunch"},
    {word: "змішувати", translation: "mix", guessed: false, example: "She will mix the ingredients to make a cake"},
    {word: "псувати", translation: "spoil", guessed: false, example: "Leaving food out in the sun can spoil it"},
    {word: "кидати", translation: "throw", guessed: false, example: "She will throw the ball to her teammate"},
    {word: "падати", translation: "drop", guessed: false, example: "Be careful not to drop the glass"},
    {word: "керувати", translation: "manage", guessed: false, example: "She will manage the team to complete a project"},
    {word: "обробляти", translation: "handle", guessed: false, example: "He needs to handle the situation diplomatically"},
    {word: "полірувати", translation: "polish", guessed: false, example: "He likes to polish his shoes before events"},
    {word: "cпробувати", translation: "try", guessed: false, example: "She will try a new recipe for dinner"},
    {word: "запобігти", translation: "prevent", guessed: false, example: "The alarm system helps prevent unauthorized access"},
    {word: "вирішувати(задачу)", translation: "solve", guessed: false, example: "She will solve the math problem"},
    {word: "розв'язувати(проблему)", translation: "resolve", guessed: false, example: "He aims to resolve the conflict through communication"},
    {word: "спеціалізуватися", translation: "specialize", guessed: false, example: "He chose to specialize as a programmer"},
    {word: "підсвічувати", translation: "highlight", guessed: false, example: "She decided to highlight the room with lights"},
    {word: "отримати", translation: "retrieve", guessed: false, example: "He will retrieve the information from a database"},
    {word: "відтворити", translation: "recreate", guessed: false, example: "She will recreate the famous painting"},
    {word: "налагодити", translation: "rectify", guessed: false, example: "The IT department worked to rectify a issue"},
    {word: "виправити", translation: "fix", guessed: false, example: "I will fix this error today"},
    {word: "зав'язувати", translation: "tie", guessed: false, example: "He is learning how to tie his shoes"},
    {word: "анулювати/скасувати", translation: "undo", guessed: false, example: "She had to undo the last few edits"},
    {word: "застебнути", translation: "fasten", guessed: false, example: "Please fasten your helmet for safety"},
    {word: "розстебнути", translation: "unfasten", guessed: false, example: "She decided to unfasten the buttons for comfort"},
    {word: "зварювати", translation: "weld", guessed: false, example: "He welded the metal pieces together"},
    {word: "приклеювати", translation: "stick", guessed: false, example: "He used glue to stick the pieces of paper together"},
    {word: "замінювати", translation: "substitute", guessed: false, example: "You can substitute butter with oil"},
    {word: "змочувати", translation: "moisten", guessed: false, example: "Moisten a stamp to activate the adhesive"},
    {word: "прибити цвях", translation: "nail", guessed: false, example: "To fix the picture he decided to nail it back"},
    {word: "проколоти", translation: "spike", guessed: false, example: "He used a nail to spike the wooden plank"},
    {word: "піднімати", translation: "pick up", guessed: false, example: "She helped pick up the toys after a party"},
    {word: "натирати", translation: "rub", guessed: false, example: "She needed to rub her hands to remove the sand"},
    {word: "пилити", translation: "saw", guessed: false, example: "He sawed the tree to create logs"},
    {word: "розкидати", translation: "scatter", guessed: false, example: "A wind scattered the leaves"},
    {word: "зішкрібати", translation: "scrape", guessed: false, example: "He accidentally scraped his car against the fence"},
    {word: "подряпати", translation: "scratch", guessed: false, example: "The cat likes to scratch its claws on a tree"},
    {word: "закручувати", translation: "screw", guessed: false, example: "He needed a screwdriver to screw the shelves"},
    {word: "упіймати", translation: "catch", guessed: false, example: "She tried to catch the ball but missed"},
    {word: "схопити", translation: "seize", guessed: false, example: "He managed to seize the opportunity"},
    {word: "розсипати", translation: "spill", guessed: false, example: "Be careful not to spill the coffee"},
    {word: "змонтувати", translation: "assemble", guessed: false, example: "He followed instructions to assemble the bookshelf"},
    {word: "розбирати", translation: "disassemble", guessed: false, example: "They had to disassemble the furniture for moving"},
    {word: "проводити", translation: "conduct", guessed: false, example: "The scientist decided to conduct experiments"},
    {word: "знищувати", translation: "destroy", guessed: false, example: "He accidentally destroyed the document"},
    {word: "зносити", translation: "demolish", guessed: false, example: "The city decided to demolish an old bridge"},
    {word: "розбавляти", translation: "dilute", guessed: false, example: "Please dilute the juice with water"}
]
