export const verb_state = [
    {word: "з'являтися", translation: "appear", guessed: false, example: "The sun will appear above a horizon"},
    {word: "затримувати", translation: "delay", guessed: false, example: "She is delaying the meeting"},
    {word: "закінчити", translation: "complete", guessed: false, example: "She will complete the final chapter"},
    {word: "завершувати", translation: "finish", guessed: false, example: "The team can finish a project early"},
    {word: "ставати(кимось)", translation: "become", guessed: false, example: "She will become a skilled pianist"},
    {word: "відкласти", translation: "put off", guessed: false, example: "They decided to put off the meeting"},
    {word: "перенести", translation: "postpone", guessed: false, example: "She will postpone her trip"},
    {word: "повторювати", translation: "repeat", guessed: false, example: "She will repeat the experiment"},
    {word: "відновити", translation: "resume", guessed: false, example: "She will resume her work after the break"},
    {word: "фіналізувати", translation: "finalize", guessed: false, example: "He aims to finalize the report by morning"},
    {word: "ставатися/відбуватися", translation: "happen", guessed: false, example: "She wants to see what will happen"},
    {word: "запускати", translation: "start", guessed: false, example: "Start the engine before driving"},
    {word: "зупиняти", translation: "stop", guessed: false, example: "She will stop at the red light"},
    {word: "призупиняти", translation: "suspend", guessed: false, example: "They decided to suspend him from work"},
    {word: "продовжувати", translation: "continue", guessed: false, example: "The meeting will continue after a break"},
    {word: "рухатися далі", translation: "go on", guessed: false, example: "We will go on to the next step"},
    {word: "запізнюватися", translation: "be late", guessed: false, example: "She was late due to traffic"},
    {word: "збирати", translation: "collect", guessed: false, example: "She will collect data for her research"},
    {word: "споживати", translation: "consume", guessed: false, example: "She will consume a nutritious breakfast"},
    {word: "вміщувати/містити в собі", translation: "contain", guessed: false, example: "The box contains school supplies"},
    {word: "пошкоджувати", translation: "damage", guessed: false, example: "The storm damaged a roof"},
    {word: "існувати", translation: "exist", guessed: false, example: "Unicorns do not actually exist"},
    {word: "скасувати", translation: "cancel", guessed: false, example: "They decided to cancel the meeting"},
    {word: "ліквідувати", translation: "eliminate", guessed: false, example: "They worked to eliminate errors in the report"},
    {word: "видалити", translation: "delete", guessed: false, example: "She chose to delete unnecessary files"},
    {word: "знищити", translation: "destroy", guessed: false, example: "She wants to destroy all mentions of the incident"},
    {word: "збиратися/збирати", translation: "gather", guessed: false, example: "The company will gather all members"},
    {word: "тримати", translation: "keep", guessed: false, example: "Please keep the tickets during your visit"},
    {word: "зберігати", translation: "store", guessed: false, example: "He stored the camping equipment in a garage"},
    {word: "визначати локацію", translation: "locate", guessed: false, example: "She will locate the nearest gas station"},
    {word: "підтримувати", translation: "support", guessed: false, example: "I support my friends and encourage them"},
    {word: "обслуговувати", translation: "maintain", guessed: false, example: "Oil changes are necessary to maintain the car"},
    {word: "потребувати", translation: "need", guessed: false, example: "She will need more time to complete the project"},
    {word: "розміщувати/визначати місце", translation: "place", guessed: false, example: "She placed a vase on the table"},
    {word: "накопичувати", translation: "accumulate", guessed: false, example: "He accumulated money for vacation"},
    {word: "додавати", translation: "add", guessed: false, example: "Please add sugar to the tea"},
    {word: "мати", translation: "have", guessed: false, example: "She will have dinner with her boyfriend"},
    {word: "виключати(щось з відкись)", translation: "exclude", guessed: false, example: "The chapter was excluded from a book"},
    {word: "включати до складу", translation: "include", guessed: false, example: "The package will include various products"},
    {word: "бракувати/не вистачати", translation: "lack", guessed: false, example: "I lack time to finish the project"},
    {word: "губити", translation: "lose", guessed: false, example: "He lost his keys during the trip"}
]
