export const verbs_social = [
    {word: "лікувати", translation: "treat", guessed: false, example: "The doctor will treat the patient's symptoms with medication"},
    {word: "жити", translation: "live", guessed: false, example: "She chose to live in the countryside surrounded by nature"},
    {word: "народитися", translation: "born", guessed: false, example: "He was born on a sunny day in May, bringing joy to his family"},
    {word: "чихати", translation: "sneeze", guessed: false, example: "When you have a cold, it's common to sneeze multiple times a day"},
    {word: "простудитися", translation: "catch a cold", guessed: false, example: "In winter, it's important to dress warmly to avoid catching a cold"},
    {word: "хворіти", translation: "ill", guessed: false, example: "She felt ill and decided to rest at home"},
    {word: "нездужати", translation: "sick", guessed: false, example: "He stayed home from work because he felt sick"},
    {word: "кашляти", translation: "cough", guessed: false, example: "In winter, people often cough due to the cold air"},
    {word: "зцілити", translation: "heal", guessed: false, example: "She followed the doctor's advice to heal quickly"},
    {word: "слабнути", translation: "weaken", guessed: false, example: "Lack of exercise and poor nutrition can weaken the immune system"},
    {word: "помирати", translation: "die", guessed: false, example: "Plants need water and sunlight, or they may die"},
    {word: "давати ім'я", translation: "name", guessed: false, example: "She decided to name her new puppy Max"},
    {word: "одружуватися", translation: "marry", guessed: false, example: "After years of dating, they decided to marry"},
    {word: "наймати на роботу", translation: "employ", guessed: false, example: "The company decided to employ new staff to meet demand"},
    {word: "звільняти", translation: "dismiss", guessed: false, example: "Due to budget cuts, the company had to dismiss employees"},
    {word: "належати", translation: "belong", guessed: false, example: "The old photo album belongs to my grandmother"},
    {word: "проводити/витрачати", translation: "spend", guessed: false, example: "He spend all time on unproductive activities"},
    {word: "марнувати", translation: "waste", guessed: false, example: "I do not waste time during summer break"},
    {word: "замовляти", translation: "order", guessed: false, example: "She likes to order her favorite food from the restaurant"},
    {word: "платити", translation: "pay", guessed: false, example: "He will pay for groceries at the checkout"},
    {word: "вести за собою/очолювати", translation: "lead", guessed: false, example: "She will lead a team in the new strategy"},
    {word: "працювати", translation: "work", guessed: false, example: "She likes to work in the garden planting flowers"},
    {word: "заробляти", translation: "earn", guessed: false, example: "He works hard to earn money for college"},
    {word: "економити", translation: "economize", guessed: false, example: "She decided to economize by cutting expenses"},
    {word: "заощаджувати", translation: "save", guessed: false, example: "He makes an effort to save a portion of his salary"},
    {word: "зберігати", translation: "keep", guessed: false, example: "I keep a jar for spare change"},
    {word: "накопичувати", translation: "accumulate", guessed: false, example: "It's important to accumulate savings consistently"},
    {word: "залежати", translation: "depend", guessed: false, example: "Project success depends on communication"},
    {word: "відмовлятися від когось", translation: "refuse", guessed: false, example: "Heartbreaking to see someone refuse a loyal pet"},
    {word: "покинути намір", translation: "abandon", guessed: false, example: "The explorers had to abandon their mission due to weather"},
    {word: "залучати", translation: "involve", guessed: false, example: "Volunteer work may involve helping with events"},
    {word: "приєднатися", translation: "join", guessed: false, example: "She will join a team for the project"},
    {word: "об’єднатися", translation: "unite", guessed: false, example: "They will unite their efforts for a common goal"}
]
