export const verbs_fight = [
    {word: "нападати", translation: "attack", guessed: false, example: "The enemy planned to attack a fortress under cover of darkness"},
    {word: "боротися", translation: "fight", guessed: false, example: "The soldiers showed courage as they fought for their homeland"},
    {word: "захищати", translation: "defend", guessed: false, example: "Archers were positioned to defend against threats"},
    {word: "виграти", translation: "win", guessed: false, example: "The team managed to win a championship"},
    {word: "програти", translation: "lose", guessed: false, example: "The soccer team lost a final match"},
    {word: "стріляти", translation: "shoot", guessed: false, example: "An officer had to shoot the suspect to protect bystanders"},
    {word: "поранити", translation: "wound", guessed: false, example: "A stray bullet accidentally wounded a pedestrian"},
    {word: "націлюватися", translation: "aim", guessed: false, example: "She aims to become a successful entrepreneur"},
    {word: "озброюватися", translation: "arm oneself", guessed: false, example: "In dangerous situations please arm oneself"},
    {word: "бути оточеним", translation: "be encircled", guessed: false, example: "The castle was encircled by a high wall"},
    {word: "бомбити", translation: "bomb", guessed: false, example: "The troops attempted to bomb a base"},
    {word: "вибухати", translation: "burst", guessed: false, example: "The balloon suddenly burst and startling everyone"},
    {word: "взірвати", translation: "explode", guessed: false, example: "The fireworks exploded in a display of colors"},
    {word: "захоплювати", translation: "capture", guessed: false, example: "The mission was to capture an enemy stronghold"},
    {word: "підкоряти", translation: "conquer", guessed: false, example: "The army set out to conquer new territories"},
    {word: "завдати поразки", translation: "defeat", guessed: false, example: "Our team can defeat their competitors"},
    {word: "роззброювати", translation: "disarm", guessed: false, example: "The sides agreed to disarm as a sign of goodwill"},
    {word: "виганяти", translation: "drive out", guessed: false, example: "The villagers banded together to drive out an invader"},
    {word: "вистрілювати", translation: "fire", guessed: false, example: "The soldiers fired their weapons to signal a start"},
    {word: "вдарити", translation: "hit", guessed: false, example: "A boxer hit his opponent in the jaw"},
    {word: "вторгатися", translation: "invade", guessed: false, example: "The army planned to invade a neighboring country"},
    {word: "убити", translation: "kill", guessed: false, example: "The assassin was hired to kill a leader"},
    {word: "звільняти", translation: "liberate", guessed: false, example: "The forces fought to liberate a city"},
    {word: "промахнутися", translation: "miss", guessed: false, example: "He missed with the last shot"},
    {word: "окупувати", translation: "occupy", guessed: false, example: "The army moved to occupy strategic positions"},
    {word: "перебороти", translation: "overcome", guessed: false, example: "She overcame obstacles to achieve her goals"},
    {word: "вказувати", translation: "point", guessed: false, example: "He pointed towards the horizon"},
    {word: "супротивлятися", translation: "resist", guessed: false, example: "He managed to resist the chocolate cake"},
    {word: "рятувати", translation: "rescue", guessed: false, example: "Firefighters risked their lives to rescue people"},
    {word: "боротися", translation: "struggle", guessed: false, example: "She struggled to lift the heavy box"},
    {word: "здаватися", translation: "surrender", guessed: false, example: "The enemy forces were forced to surrender"},
    {word: "загрожувати", translation: "threaten", guessed: false, example: "The clouds threatened a heavy downpour"},
    {word: "розв'язати війну", translation: "unleash war", guessed: false, example: "The decision to unleash war requires careful consideration"},
    {word: "вести війну", translation: "wage war", guessed: false, example: "The country decided to wage war leading to conflict"}
]
