export const verbs_tech = [
    {word: "відстежувати", translation: "track", guessed: false, example: "He will track his daily steps using a fitness app"},
    {word: "вставити", translation: "insert", guessed: false, example: "She will insert a new paragraph into the document"},
    {word: "помістити", translation: "paste", guessed: false, example: "He will paste a copied text into the email"},
    {word: "копіювати", translation: "copy", guessed: false, example: "She will copy the text from a website for her research"},
    {word: "оновити", translation: "update", guessed: false, example: "She will update the software to a latest version"},
    {word: "освіжити", translation: "refresh", guessed: false, example: "After making changes, you may need to refresh the website"},
    {word: "перезавантажити", translation: "reload", guessed: false, example: "The laptop was reloaded very fast"},
    {word: "відкочувати", translation: "rollback", guessed: false, example: "They decided to rollback to the previous version after an issue"},
    {word: "прокручувати", translation: "scroll", guessed: false, example: "To read the article scroll down using the mouse"},
    {word: "перегортати", translation: "swipe", guessed: false, example: "You can swipe left or right to navigate on a touchscreen"},
    {word: "поширювати", translation: "spread", guessed: false, example: "They aim to spread awareness about environmental conservation"},
    {word: "розповсюджувати", translation: "distribute", guessed: false, example: "The company will distribute products to various locations"},
    {word: "реставрувати", translation: "restore", guessed: false, example: "She will restore the old painting to its original condition"},
    {word: "відновлювати", translation: "recover", guessed: false, example: "He aims to recover the lost files from his computer"},
    {word: "створювати", translation: "create", guessed: false, example: "She will create a beautiful piece of artwork"},
    {word: "генерувати", translation: "generate", guessed: false, example: "He used to generate innovative ideas for projects"},
    {word: "роздвинути", translation: "expand", guessed: false, example: "She plans to expand her business to new markets"},
    {word: "розширити", translation: "extend", guessed: false, example: "He wants to extend the deadline for more time"},
    {word: "втілювати", translation: "implement", guessed: false, example: "She will implement the new system to improve efficiency"},
    {word: "навести (над чимось)", translation: "hover", guessed: false, example: "Move a mouse to hover over the page title"},
    {word: "масштабувати", translation: "zoom", guessed: false, example: "She will zoom in on the image to look carefully"},
    {word: "відіслати", translation: "send", guessed: false, example: "She will send an email with the updated report"},
    {word: "виявити", translation: "detect", guessed: false, example: "The system can detect unauthorized access to a building"},
    {word: "застосовувати", translation: "apply", guessed: false, example: "He will apply for the scholarship to pursue his studies"},
    {word: "прикріпляти", translation: "attach", guessed: false, example: "She will attach the files to an email before sending it"},
    {word: "з'єднувати", translation: "connect", guessed: false, example: "He needs to connect the printer to his computer to start printing"},
    {word: "продовжувати (працювати)", translation: "continue", guessed: false, example: "She decided to continue working after a short break"},
    {word: "продовжувати (презентацію)", translation: "go on", guessed: false, example: "He will go on with the presentation after a brief interruption"},
    {word: "продовжувати (розробку)", translation: "proceed", guessed: false, example: "They will proceed with the development after resolving an issue"},
    {word: "контролювати", translation: "control", guessed: false, example: "She needs to control her emotions during the interview"},
    {word: "тестувати", translation: "test", guessed: false, example: "He will test the software for errors before release"},
    {word: "перевіряти", translation: "check", guessed: false, example: "She will check her work for mistakes before submitting"},
    {word: "переглядати", translation: "review", guessed: false, example: "She will review the document before presenting it"},
    {word: "верифікувати", translation: "verify", guessed: false, example: "He needs to verify the information before deciding"},
    {word: "валідувати", translation: "validate", guessed: false, example: "She will validate the data before a meeting"},
    {word: "підтверджувати", translation: "confirm", guessed: false, example: "He called to confirm the reservation"},
    {word: "пропустити", translation: "skip", guessed: false, example: "You can skip to the next level by pressing an arrow key"},
    {word: "оцінювати", translation: "estimate", guessed: false, example: "She will estimate the cost of a project"},
    {word: "виключати", translation: "exclude", guessed: false, example: "She will exclude irrelevant information from the report"},
    {word: "ізолювати", translation: "isolate", guessed: false, example: "They decided to isolate infected individuals from the group"},
    {word: "наповнювати", translation: "fill", guessed: false, example: "She will fill the glass with water"},
    {word: "фільтрувати", translation: "filter", guessed: false, example: "They use a filter to improve water quality"},
    {word: "знаходити", translation: "find", guessed: false, example: "She will find her keys in the living room"},
    {word: "ховати", translation: "hide", guessed: false, example: "He likes to hide his toys under the bed"},
    {word: "відрегулювати", translation: "adjust", guessed: false, example: "She needs to adjust the camera settings"},
    {word: "підігнати", translation: "fit", guessed: false, example: "He will try to fit the puzzle pieces together"},
    {word: "вирівнювати", translation: "align", guessed: false, example: "She will align the text to a left side"},
    {word: "виправляти", translation: "fix", guessed: false, example: "She needs to fix the broken chair leg"},
    {word: "ремонтувати", translation: "repair", guessed: false, example: "He will repair the leaky faucet"},
    {word: "підготовлювати", translation: "prepare", guessed: false, example: "She will prepare a meal for dinner"},
    {word: "використовувати", translation: "use", guessed: false, example: "He will use the pen to write a letter"},
    {word: "закривати (вікно)", translation: "close", guessed: false, example: "He needs to close the window before it rains"},
    {word: "замикати (двері)", translation: "shut", guessed: false, example: "He asked his brother to shut the door"},
    {word: "відкривати", translation: "open", guessed: false, example: "She will open the door to welcome a guest"},
    {word: "замінити", translation: "replace", guessed: false, example: "She will replace the old lightbulb"},
    {word: "зменшити", translation: "reduce", guessed: false, example: "She will reduce her screen time"},
    {word: "збільшити", translation: "increase", guessed: false, example: "He wants to increase his exercise"},
    {word: "покращити", translation: "improve", guessed: false, example: "To improve the taste, she added more seasoning"},
    {word: "розшукувати", translation: "search", guessed: false, example: "She will search for information online"},
    {word: "шукати", translation: "seek", guessed: false, example: "He decided to seek advice from a mentor"},
    {word: "об'єднувати", translation: "merge", guessed: false, example: "The companies decided to merge"},
    {word: "розколювати", translation: "split", guessed: false, example: "They will split the tasks for better efficiency"},
    {word: "прив'язувати", translation: "bind", guessed: false, example: "She will bind the pages to create a book"},
    {word: "обгортати", translation: "wrap", guessed: false, example: "She will wrap the gift in paper"},
    {word: "загортати", translation: "envelop", guessed: false, example: "She will envelop the letter and send it"},
    {word: "запрошувати", translation: "invite", guessed: false, example: "She will invite her friends to the party"},
    {word: "зустрічати", translation: "meet", guessed: false, example: "They plan to meet at a coffee shop"},
    {word: "представляти", translation: "introduce", guessed: false, example: "She will introduce her friend to the group"},
    {word: "діяти", translation: "act", guessed: false, example: "She will act as a leader"},
    {word: "оперувати", translation: "operate", guessed: false, example: "The engineer explained how to operate a machine"},
    {word: "ламати", translation: "break", guessed: false, example: "She dropped the vase and it broke into pieces"},
    {word: "починатися", translation: "begin", guessed: false, example: "She will begin her journey"},
    {word: "закінчуватися", translation: "end", guessed: false, example: "The road ends in a few meters"},
    {word: "змінити", translation: "change", guessed: false, example: "He wants to change the wall color"},
    {word: "обміняти", translation: "exchange", guessed: false, example: "They decided to exchange items for better performance"},
    {word: "тягнути", translation: "pull", guessed: false, example: "He pulled the door to open it"},
    {word: "штовхати", translation: "push", guessed: false, example: "She pushed a cart through the supermarket"},
    {word: "перекривати", translation: "overlap", guessed: false, example: "The schedules for these two events overlap"},
    {word: "накривати/прикривати/заміщати", translation: "cover", guessed: false, example: "I cover my teammate due on his vacation time"},
    {word: "виконувати(дію)", translation: "perform", guessed: false, example: "She will perform the experiment to test her hypothesis"},
    {word: "виконувати(план)", translation: "execute", guessed: false, example: "He will execute a plan to launch the product"},
    {word: "втілити/виконати", translation: "carry out", guessed: false, example: "I decided to carry out the plan as discussed"},
    {word: "передавати (дані)", translation: "transmit", guessed: false, example: "The tower will transmit a signal across a wide area"},
    {word: "транслювати", translation: "broadcast", guessed: false, example: "A radio station will broadcast the news at noon"},
    {word: "торкнутися (екрану)", translation: "tap", guessed: false, example: "She will tap on a screen to open the application"},
    {word: "натиснути (клавішу)", translation: "press", guessed: false, example: "He needs to press a button to turn on the device"},
    {word: "доторкатися", translation: "touch", guessed: false, example: "They can touch a screen to activate the tablet"},
    {word: "клацнути (мишкою)", translation: "click", guessed: false, example: "He needs to click a mouse to interact with the software"},
    {word: "обробляти", translation: "process", guessed: false, example: "Workers carefully process raw materials into products"},
    {word: "призначати", translation: "assign", guessed: false, example: "They will assign tasks to each team member"},
    {word: "авторизовуватися", translation: "login", guessed: false, example: "Please enter your username and password to login"},
    {word: "зареєструватися", translation: "signup", guessed: false, example: "She will signup for the workshop to enhance her skills"},
    {word: "відправити", translation: "submit", guessed: false, example: "He needs to submit a report by the end of this day"}
]