export const it = [
    {word: "можливо", translation: "probably", guessed: false, example: "Probably it will rain later today"},
    {word: "доречі", translation: "by the way", guessed: false, example: "By the way, did you hear about a new restaurant?"},
    {word: "здатність", translation: "ability", guessed: false, example: "Her ability to learn new languages is impressive"},
    {word: "мета/ціль", translation: "aim", guessed: false, example: "His aim is to become a professional athlete"},
    {word: "ціль(планована)", translation: "goal", guessed: false, example: "My goal is to win the championship this year"},
    {word: "ціль(спрямована)", translation: "target", guessed: false, example: "The archer achieved his target"},
    {word: "досягнення", translation: "achievement", guessed: false, example: "Winning the competition was a great achievement for her"},
    {word: "виклик/випробування", translation: "challenge", guessed: false, example: "Climbing to the Everest was a great challenge"},
    {word: "перевага", translation: "advantage", guessed: false, example: "My advantage is to quickly learn all new things"},
    {word: "ставлення/відношення", translation: "attitude", guessed: false, example: "Positive attitude it is a great habit"},
    {word: "рішення", translation: "decision", guessed: false, example: "She always make a quick decision"},
    {word: "безумовно(100%)", translation: "definitely", guessed: false, example: "I will definitely be at the meeting tomorrow"},
    {word: "так, звичайно", translation: "sure", guessed: false, example: "Yes, sure, she will pass the exam"},
    {word: "рано", translation: "early", guessed: false, example: "Waking up early allows you to enjoy the sunrise"},
    {word: "легко", translation: "easy", guessed: false, example: "Swimming is an easy sport to learn"},
    {word: "тяжко", translation: "hard", guessed: false, example: "Learning a new language can be hard"},
    {word: "ефективний", translation: "efficient", guessed: false, example: "He was an efficient team member"},
    {word: "ефективно", translation: "effectively", guessed: false, example: "He communicated his ideas effectively to the team"},
    {word: "ефективність", translation: "efficiency", guessed: false, example: "Efficiency in the workplace leads to higher productivity"},
    {word: "зусилля", translation: "efforts", guessed: false, example: "His efforts paid off when he won the race"},
    {word: "достатньо", translation: "enough", guessed: false, example: "Eating a balanced diet is enough to stay healthy"},
    {word: "гарантую/ручаюся", translation: "ensure", guessed: false, example: "They ensure that every customer will be satisfied"},
    {word: "згідно з", translation: "according to", guessed: false, example: "According to the weather forecast, it will be sunny tomorrow"},
    {word: "фактичний результат", translation: "actual result", guessed: false, example: "Everyone was surprised by election results"},
    {word: "конфігурувати", translation: "configure", guessed: false, example: "He knows how to configure the computer network"},
    {word: "встановити", translation: "install", guessed: false, example: "She installed the new software on her laptop"},
    {word: "розгортати(сервер)", translation: "deploy", guessed: false, example: "The company plans to deploy new technology next month"},
    {word: "налаштувати", translation: "setup", guessed: false, example: "He needs to setup his email account"},
    {word: "абсолютно", translation: "absolutely", guessed: false, example: "Absolutely I would love to go to the concert with you"},
    {word: "повністю", translation: "completely", guessed: false, example: "She completely finished her homework before dinner"},
    {word: "в загальному", translation: "in general", guessed: false, example: "In general I enjoy spending time outdoors"},
    {word: "точний", translation: "accurate", guessed: false, example: "He is very accurate person"},
    {word: "переживання", translation: "concern", guessed: false, example: "She expressed her concern for the environment"},
    {word: "умови", translation: "conditions", guessed: false, example: "They cancelled a picnic according to the weather conditions"},
    {word: "заборонено", translation: "restricted", guessed: false, example: "Smoking is restricted in public places"},
    {word: "доступ", translation: "access", guessed: false, example: "Access to the building is restricted"},
    {word: "обліковий запис", translation: "account", guessed: false, example: "She forgot her password to her online account"},
    {word: "побоювання", translation: "afraid", guessed: false, example: "He was afraid of spiders"},
    {word: "додати", translation: "add", guessed: false, example: "Let's add some salt to enhance the flavor"},
    {word: "додатковий", translation: "additional", guessed: false, example: "She bought an additional ticket for her friend"},
    {word: "реклама", translation: "advertisement", guessed: false, example: "The new advertisement was very catchy"},
    {word: "додаток", translation: "application", guessed: false, example: "Application is working good on mobile phones"},
    {word: "запевнення", translation: "assurance", guessed: false, example: "She gave her assurance to leave early"},
    {word: "аутентифікація", translation: "authentication", guessed: false, example: "Authentication is required to access the secure system"},
    {word: "авторизація", translation: "authorization", guessed: false, example: "Authorization from the manager is needed"},
    {word: "штучні", translation: "artificial", guessed: false, example: "They used artificial intelligence to analyze the data"},
    {word: "перешкода", translation: "obstacle", guessed: false, example: "The fallen tree was an obstacle on the path"},
    {word: "домовлений/влаштований", translation: "arranged", guessed: false, example: "They arranged to meet at the park"},
    {word: "складність", translation: "complexity", guessed: false, example: "The complexity of a problem required a creative solution"},
    {word: "вплив", translation: "impact", guessed: false, example: "Having a positive attitude can impact your success in life"},
    {word: "як наслідок", translation: "consequently", guessed: false, example: "Consequently he missed his train and was late for work"},
    {word: "окремо", translation: "apart", guessed: false, example: "The two friends decided to sit apart in class"},
    {word: "припущення", translation: "assumption", guessed: false, example: "His assumption about the outcome turned out to be correct"},
    {word: "припустимо", translation: "suppose", guessed: false, example: "Suppose I believe you"},
    {word: "обставини", translation: "circumstances", guessed: false, example: "We have to adapt our plans according to the given circumstances"},
    {word: "заснування", translation: "establishment", guessed: false, example: "The establishment of a new company was a success"},
    {word: "дотримуватися", translation: "comply", guessed: false, example: "Employees must comply with the company's code of conduct"},
    {word: "сумісний", translation: "compliant", guessed: false, example: " The new software is fully compliant with industry standards"},
    {word: "відповідність", translation: "compliance", guessed: false, example: "Regular audits ensure compliance with safety regulations"},
    {word: "порівняти", translation: "compare", guessed: false, example: "Let's compare the prices before making a decision"},
    {word: "порівняння", translation: "comparison", guessed: false, example: "The prices comparison in a table form"},
    {word: "конкурентний", translation: "competitive", guessed: false, example: "The company faces competitive challenges in a market"},
    {word: "вкладення", translation: "attachment", guessed: false, example: "The attachment to an email was too large to send"},
    {word: "увага", translation: "attention", guessed: false, example: "Pay attention to the details in a contract"},
    {word: "доступний", translation: "available", guessed: false, example: "A latest version of the software is now available for download"},
    {word: "поведінка", translation: "behavior", guessed: false, example: "His behavior at the meeting was inappropriate"},
    {word: "окрім", translation: "besides", guessed: false, example: "Besides work, he enjoys playing tennis in his free time"},
    {word: "поміж", translation: "between", guessed: false, example: "She manages to find time for herself between work and family"},
    {word: "турбота", translation: "care", guessed: false, example: "Take care of yourself while you're traveling"},
    {word: "кар’єрний ріст", translation: "career growth", guessed: false, example: "Personal career growth is important for self-improvement"},
    {word: "символ", translation: "character", guessed: false, example: "Her character is admired by everyone who knows her"},
    {word: "переписка", translation: "chat", guessed: false, example: "Let's have a chat about the project tomorrow"},
    {word: "нагорода", translation: "award", guessed: false, example: "He received an award for his outstanding performance"},
    {word: "марне витрачання", translation: "waste", guessed: false, example: "Reducing waste is important for environmental sustainability"},
    {word: "ранг", translation: "rank", guessed: false, example: "The company's rank in an industry is rising steadily"},
    {word: "витрати", translation: "costs", guessed: false, example: "We need to cut costs to improve profitability"},
    {word: "курси", translation: "courses", guessed: false, example: "She enrolled in several courses to improve her skills"},
    {word: "розробка", translation: "development", guessed: false, example: "The development of a new product is progressing smoothly"},
    {word: "пристрій", translation: "device", guessed: false, example: "The device can be used for various purposes"},
    {word: "масштаб", translation: "scale", guessed: false, example: "You can choose the needed scale on a Google map"},
    {word: "випадаюче меню", translation: "dropdown menu", guessed: false, example: "The dropdown menu allows you to select from multiple options"},
    {word: "значок", translation: "icon", guessed: false, example: "Click on the icon to open an application"},
    {word: "зображення", translation: "image", guessed: false, example: "An image on the website was blurry"},
    {word: "блокер", translation: "blocker", guessed: false, example: "He installed an ad blocker to avoid pop-up ads"},
    {word: "баг", translation: "bug", guessed: false, example: "There was a bug in the software that caused it to crash"},
    {word: "помилка", translation: "error", guessed: false, example: "She fixed the error in a code before release"},
    {word: "несправність", translation: "malfunction", guessed: false, example: "The malfunction of a machine caused delays in production"},
    {word: "дефект", translation: "defect", guessed: false, example: "The defect in a product was discovered during testing"},
    {word: "скомпільований код", translation: "build", guessed: false, example: "The new build was deployed yesterday"},
    {word: "клавіша", translation: "button", guessed: false, example: "Click the button to submit your form"},
    {word: "поле редагування", translation: "edit field", guessed: false, example: "Enter your information in the required field"},
    {word: "спільний", translation: "common", guessed: false, example: "It is common for people to feel nervous before a presentation"},
    {word: "спілкуватися", translation: "communicate", guessed: false, example: "We need to communicate our expectations clearly"},
    {word: "повне співпадіння", translation: "completely matches", guessed: false, example: "Her description completely matches the suspect's appearance"},
    {word: "компонент", translation: "component", guessed: false, example: "The component is essential for a machine functioning"},
    {word: "конструктивний", translation: "constructive", guessed: false, example: "We appreciate your constructive feedback"},
    {word: "споживачі", translation: "consumers", guessed: false, example: "A company focuses on meeting the needs of consumers"},
    {word: "споживання", translation: "consumption", guessed: false, example: "Reducing energy consumption is important for sustainability"},
    {word: "витрати", translation: "consuming", guessed: false, example: "Consuming too much sugar can lead to health problems"},
    {word: "містить", translation: "contains", guessed: false, example: "The bottle contains water"},
    {word: "вміст", translation: "content", guessed: false, example: "The content of a book was interesting"},
    {word: "протиріччя", translation: "contradiction", guessed: false, example: "There was a contradiction in his statements"},
    {word: "вклад", translation: "contribution", guessed: false, example: "Her contribution to the project was significant"},
    {word: "загальноприйнятий", translation: "conventional", guessed: false, example: "The traditional method is considered conventional"},
    {word: "розмова", translation: "conversation", guessed: false, example: "We had a pleasant conversation over coffee"},
    {word: "зручність", translation: "convenience", guessed: false, example: "Online shopping offers convenience to customers"},
    {word: "падіння", translation: "crash", guessed: false, example: "The computer program crashed unexpectedly"},
    {word: "критика", translation: "criticism", guessed: false, example: "She received criticism for her work"},
    {word: "кросбраузерний", translation: "crossbrowser", guessed: false, example: "Make sure your website is compatible with crossbrowser platforms"},
    {word: "поточний", translation: "current", guessed: false, example: "What is your current address?"},
    {word: "на даний час", translation: "currently", guessed: false, example: "I am currently working on a new project"},
    {word: "користувач", translation: "user", guessed: false, example: "The user interface is easy to navigate"},
    {word: "клієнт", translation: "customer", guessed: false, example: "Customer satisfaction is our top priority"},
    {word: "потреби замовника", translation: "customer needs", guessed: false, example: "Understanding customer needs is essential for business success"},
    {word: "дані", translation: "data", guessed: false, example: "We need to analyze the data before making a decision"},
    {word: "за замовчуванням", translation: "by default", guessed: false, example: "The settings are set to standard by default"},
    {word: "відкладений", translation: "deferred", guessed: false, example: "The meeting has been deferred to next week"},
    {word: "доставка", translation: "delivery", guessed: false, example: "The delivery of a package was delayed"},
    {word: "потреба", translation: "demand", guessed: false, example: "There is a high demand for the product"},
    {word: "відділ", translation: "department", guessed: false, example: "He works in the marketing department"},
    {word: "опис", translation: "description", guessed: false, example: "The job description was detailed"},
    {word: "інший", translation: "other", guessed: false, example: "Please specify any other preferences you have"},
    {word: "різноманітний", translation: "different", guessed: false, example: "Different people have different opinions"},
    {word: "тяжко", translation: "difficult", guessed: false, example: "Learning a new language can be difficult"},
    {word: "прямий/безпосередній", translation: "direct", guessed: false, example: "Follow the signs for a direct route to a city"},
    {word: "відображати", translation: "display", guessed: false, example: "The display showed a temperature"},
    {word: "показувати", translation: "show", guessed: false, example: "Show me your driver license please"},
    {word: "порушувати", translation: "disrupt", guessed: false, example: "Disruptive behavior will not be tolerated"},
    {word: "розподілення", translation: "distribution", guessed: false, example: "The distribution of resources needs to be fair"},
    {word: "мрія", translation: "dream", guessed: false, example: "Achieving your dream requires hard work"},
    {word: "вчасно", translation: "due time", guessed: false, example: "The project will be completed in due time"},
    {word: "дублікат", translation: "duplicate", guessed: false, example: "Please delete the duplicate files"},
    {word: "працівник", translation: "employee", guessed: false, example: "Each employee has their own responsibilities"},
    {word: "інкапсуляція", translation: "encapsulation", guessed: false, example: "Encapsulation is a key concept in programming"},
    {word: "оточення", translation: "environment", guessed: false, example: "Protecting the environment is important for future generations"},
    {word: "обладнання", translation: "equipment", guessed: false, example: "The equipment needed for a job is ready"},
    {word: "повідомлення про помилку", translation: "error message", guessed: false, example: "An error message appeared on the screen"},
    {word: "оцінка (часу)", translation: "estimate", guessed: false, example: "We need to estimate a cost of the project"},
    {word: "точно", translation: "exactly", guessed: false, example: "Make sure you follow the instructions exactly"},
    {word: "приклад", translation: example, guessed: false, example: "For example, let's consider a simple case"},
    {word: "відмінно", translation: "excellent", guessed: false, example: "She received excellent feedback on her performance"},
    {word: "вихід", translation: "exit", guessed: false, example: "Click 'exit' to close the application"},
    {word: "очікування", translation: "expectation", guessed: false, example: "Our expectation is that the project will be completed on time"},
    {word: "очікуваний", translation: "expected", guessed: false, example: "The expected arrival time is 10 PM"},
    {word: "досвід", translation: "experience", guessed: false, example: "She has years of experience in the industry"},
    {word: "розширений", translation: "extended", guessed: false, example: "The deadline has been extended by a week"},
    {word: "провал (тесту)", translation: "fail", guessed: false, example: "If you fail the test, you can retake it"},
    {word: "пройдено (тест)", translation: "pass", guessed: false, example: "He passed the exam with flying colors"},
    {word: "збій", translation: "failure", guessed: false, example: "Failure is not an option because we must succeed"},
    {word: "логотип (на вкладці)", translation: "favicon", guessed: false, example: "Don't forget to set the favicon for the website"},
    {word: "страх", translation: "fear", guessed: false, example: "She overcame her fear of public speaking"},
    {word: "відчуття", translation: "feeling", guessed: false, example: "How do you feel about the new project?"},
    {word: "поле", translation: "field", guessed: false, example: "Please fill out all the fields in the form"},
    {word: "шрифт", translation: "font", guessed: false, example: "Choose a font that is easy to read"},
    {word: "підвал сайту", translation: "footer", guessed: false, example: "The footer contains important information about a website"},
    {word: "форма", translation: "form", guessed: false, example: "Submit the form once you have completed it"},
    {word: "подальший", translation: "further", guessed: false, example: "Further details will be provided in the next meeting"},
    {word: "злиття", translation: "fusion", guessed: false, example: "The fusion of different ideas led to innovation"},
    {word: "набуття", translation: "gain", guessed: false, example: "He worked hard to gain the necessary skills"},
    {word: "загальний", translation: "general", guessed: false, example: "In general, the project is going well"},
    {word: "закінчив навчання", translation: "graduated", guessed: false, example: "She graduated from college last year"},
    {word: "зростання", translation: "growth", guessed: false, example: "Personal growth is important for success"},
    {word: "керуватися", translation: "guided", guessed: false, example: "He was guided by his mentor throughout the process"},
    {word: "обробник", translation: "handler", guessed: false, example: "The event handler manages user interactions"},
    {word: "працелюбний", translation: "hardworking", guessed: false, example: "She is known for being hardworking and dedicated"},
    {word: "шапка сайту", translation: "header", guessed: false, example: "The header of a document includes several elements"},
    {word: "підказка", translation: "hint", guessed: false, example: "Here's a hint to help you solve the problem"},
    {word: "негайно", translation: "immediately", guessed: false, example: "Please respond to the email immediately"},
    {word: "важливий", translation: "important", guessed: false, example: "Attention to detail is important"},
    {word: "покращений", translation: "improved", guessed: false, example: "We have seen improved performance since the update"},
    {word: "вдосконалення", translation: "improvement", guessed: false, example: "Continuous improvement is key to success"},
    {word: "на додаток", translation: "in addition", guessed: false, example: "In addition to his other duties, he also handles customer inquiries"},
    {word: "невірно", translation: "incorrect", guessed: false, example: "The answer was marked as incorrect"},
    {word: "самостійно", translation: "independently", guessed: false, example: "He can work independently without supervision"},
    {word: "вплив", translation: "influence", guessed: false, example: "Her positive influence on the team was evident"},
    {word: "наслідування", translation: "inheritance", guessed: false, example: "The class teaches inheritance in object-oriented programming"},
    {word: "поле для вводу", translation: "input", guessed: false, example: "Please input your username and password"},
    {word: "вставка", translation: "insert", guessed: false, example: "Insert a key into the lock and turn it"},
    {word: "взаємодія", translation: "interaction", guessed: false, example: "User interaction with the interface is essential"},
    {word: "взаємозаміняємий", translation: "interchangeable", guessed: false, example: "This component is interchangeable for all modules"},
    {word: "інтерфейс", translation: "interface", guessed: false, example: "The new interface has better performance score"},
    {word: "керуватися", translation: "introduce", guessed: false, example: "Let me introduce you to our new team member"},
    {word: "вовлеченный", translation: "involved", guessed: false, example: "He was involved in every stage of the project"},
    {word: "нерегулярний", translation: "irregular", guessed: false, example: "There was an irregularity in the data"},
    {word: "проблема", translation: "issue", guessed: false, example: "We need to address this issue immediately"},
    {word: "іт-сфера", translation: "it sphere", guessed: false, example: "The IT sphere is constantly evolving"},
    {word: "ключ", translation: "key", guessed: false, example: "The key to success lies in knowledge and innovation"},
    {word: "знання", translation: "knowledge", guessed: false, example: "You can find all necessary knowledge in the manual"},
    {word: "ландшафтний режим", translation: "landscape mode", guessed: false, example: "Turn your phone to landscape mode for a better view"},
    {word: "рівень", translation: "level", guessed: false, example: "He reached the next level in his career"},
    {word: "посилання", translation: "link", guessed: false, example: "Click a link to visit the website"},
    {word: "місцевий", translation: "local", guessed: false, example: "Please enter your local address"},
    {word: "цикл", translation: "loop", guessed: false, example: "A program runs in a loop until the condition is met"},
    {word: "основні", translation: "major", guessed: false, example: "She is a major player in the industry"},
    {word: "робити", translation: "make", guessed: false, example: "Make sure to follow the instructions carefully"},
    {word: "обов’язково(законодавство)", translation: "mandatory", guessed: false, example: "Attendance at the meeting is mandatory"},
    {word: "обов’язковий(моральні норми)", translation: "obligatory", guessed: false, example: "This chapter is obligatory to know for passing the exam"},
    {word: "ручний/керівництво з експлуатації", translation: "manual", guessed: false, example: "Please refer to the manual for further instructions"},
    {word: "виробництво", translation: "manufacture", guessed: false, example: "The harmful manufacture is near my home"},
    {word: "лідер ринку", translation: "market leader", guessed: false, example: "The company is a market leader in its field"},
    {word: "стратегія маркетингова", translation: "marketing strategy", guessed: false, example: "Our marketing strategy focuses on social media"},
    {word: "найбільш важливо", translation: "most matters", guessed: false, example: "What matters most is achieving our goals"},
    {word: "зустріч", translation: "meeting", guessed: false, example: "Let's schedule a meeting to discuss the issue"},
    {word: "помилка", translation: "mistake", guessed: false, example: "Admitting a mistake is the first step to improvement"},
    {word: "збій", translation: "bug", guessed: false, example: "There seems to be a bug in the system"},
    {word: "проблема", translation: "issue", guessed: false, example: "He encountered an issue while trying to log in"},
    {word: "крім того", translation: "moreover", guessed: false, example: "Moreover, I would like to add another suggestion"},
    {word: "пропозиція (роботи, співпраці)", translation: "offer", guessed: false, example: "My offer still stands if you are interested"},
    {word: "пропозиції (словесні)", translation: "suggestion", guessed: false, example: "Do you have any suggestions for improving your workload?"},
    {word: "вузький", translation: "narrow", guessed: false, example: "The road became narrow as they drove into the mountains"},
    {word: "навігаційне меню", translation: "navigation menu", guessed: false, example: "Navigate through the menu to find what you need"},
    {word: "необхідно", translation: "necessary", guessed: false, example: "Patience is necessary when dealing with complex issues"},
    {word: "мережевий протокол", translation: "net protocol", guessed: false, example: "The net protocol ensures secure communication"},
    {word: "наступний", translation: "next", guessed: false, example: "Let's move on to the next agenda item"},
    {word: "попередній", translation: "previous", guessed: false, example: "You can view the previous entries by scrolling up"},
    {word: "повідомлення", translation: "notification", guessed: false, example: "Please check your notification settings"},
    {word: "сьогодення", translation: "nowadays", guessed: false, example: "Nowadays, technology is advancing rapidly"},
    {word: "часто(регулярно)", translation: "often", guessed: false, example: "Mistakes happen often but we learn from them"},
    {word: "часто(з певною постійністю)", translation: "frequently", guessed: false, example: "She frequently visits her parents on weekends"},
    {word: "без підготовки", translation: "on the spot", guessed: false, example: "A repairman fixed an issue on the spot"},
    {word: "закритий", translation: "close", guessed: false, example: "Make sure to close the door behind you"},
    {word: "думка", translation: "opinion", guessed: false, example: "His opinion is the opposite of mine"},
    {word: "можливість", translation: "opportunities", guessed: false, example: "There are many opportunities for growth in this company"},
    {word: "протилежний", translation: "opposite", guessed: false, example: "She took a position opposite to the generally accepted"},
    {word: "черга", translation: "order", guessed: false, example: "Please place your order at the counter"},
    {word: "перевизначати", translation: "override", guessed: false, example: "Sometimes you need to override default settings"},
    {word: "понаднормово", translation: "overtime", guessed: false, example: "He's been working overtime to meet the deadline"},
    {word: "сторінка", translation: "page", guessed: false, example: "The next page will provide more information"},
    {word: "батьківська", translation: "parent", guessed: false, example: "The parent company oversees all subsidiaries"},
    {word: "пристрасть", translation: "passion", guessed: false, example: "Her passion for the project was contagious"},
    {word: "умови оплати", translation: "payment terms", guessed: false, example: "We need to agree on the payment terms"},
    {word: "ідеальний", translation: "perfect", guessed: false, example: "She has perfect pitch when it comes to music"},
    {word: "персональні якості", translation: "personal qualities", guessed: false, example: "Positive personal qualities are important for success"},
    {word: "місце", translation: "place", guessed: false, example: "Let's find a place to sit and discuss"},
    {word: "плейсхолдер", translation: "placeholder", guessed: false, example: "Enter your name in the placeholder field"},
    {word: "платформа", translation: "platform", guessed: false, example: "The platform supports various operating systems"},
    {word: "вказівник", translation: "pointer", guessed: false, example: "Use the pointer to select the desired option"},
    {word: "поліморфізм", translation: "polymorphism", guessed: false, example: "Polymorphism allows objects to take on different forms"},
    {word: "вспливаюче вікно", translation: "pop-up", guessed: false, example: "I hate those annoying pop-up ads"},
    {word: "портретний режим", translation: "portrait mode", guessed: false, example: "Turn your phone to portrait mode for vertical viewing"},
    {word: "положення", translation: "position", guessed: false, example: "Please position the items on the shelf"},
    {word: "позитивний", translation: "positive", guessed: false, example: "Try to maintain a positive attitude"},
    {word: "негативний", translation: "negative", guessed: false, example: "Consider both the positive and negative aspects"},
    {word: "бажаний", translation: "preferable", guessed: false, example: "What are your preferable options?"},
    {word: "вподобання", translation: "preferences", guessed: false, example: "Please indicate your preferences on the form"},
    {word: "налаштування", translation: "settings", guessed: false, example: "I prepared all settings yesterday"},
    {word: "підготовка", translation: "preparing", guessed: false, example: "We are currently preparing for the upcoming event"},
    {word: "пріоритет", translation: "priority", guessed: false, example: "Customer satisfaction is our top priority"},
    {word: "вигода/прибуток", translation: "profit", guessed: false, example: "The company aims to maximize profit"},
    {word: "продвинуті", translation: "profound", guessed: false, example: "His knowledge of the subject is profound"},
    {word: "заборонено", translation: "prohibited", guessed: false, example: "Certain actions are prohibited by law"},
    {word: "прогнозування", translation: "predicting", guessed: false, example: "Predicting the weather is difficult without data"},
    {word: "цілком впевнений", translation: "entirely sure", guessed: false, example: "I'm not entirely sure about the solution"},
    {word: "деградувати", translation: "degrade", guessed: false, example: "The material will degrade if exposed to rain"},
    {word: "дивуватися", translation: "wonder", guessed: false, example: "I wonder what the result will be"},
    {word: "використовуючи", translation: "utilizing", guessed: false, example: "Utilizing resources efficiently is essential"},
    {word: "незалежно від того", translation: "regardless", guessed: false, example: "Regardless of the outcome, we must try"},
    {word: "обхід", translation: "bypass", guessed: false, example: "We need to bypass the traffic jam"},
    {word: "послідовність", translation: "sequence", guessed: false, example: "The sequence of numbers is important"},
    {word: "очевидно", translation: "obviously", guessed: false, example: "Obviously, the task is difficult"},
    {word: "піддається", translation: "exposed", guessed: false, example: "The paint will be damaged if exposed"},
    {word: "послідовний", translation: "consistent", guessed: false, example: "Consistent effort leads to success"},
    {word: "розуміння", translation: "comprehension", guessed: false, example: "Good comprehension is key to learning"},
    {word: "посилений", translation: "reinforced", guessed: false, example: "The wall is reinforced for strength"},
    {word: "дотримуватися", translation: "adhere", guessed: false, example: "Adhere to the guidelines strictly"},
    {word: "призначений", translation: "designated", guessed: false, example: "Follow the designated path for safety"},
    {word: "так само", translation: "likewise", guessed: false, example: "She likes the idea, and I do likewise"},
    {word: "достатній", translation: "sufficient", guessed: false, example: "Sufficient evidence is needed for a decision"},
    {word: "плюси-мінуси", translation: "pros-cons", guessed: false, example: "Let's weigh the pros-cons before deciding"},
    {word: "публічний", translation: "public", guessed: false, example: "The public is invited to an event"},
    {word: "якість", translation: "quality", guessed: false, example: "Our company is known for its quality products"},
    {word: "кількість", translation: "quantity", guessed: false, example: "We need to increase the quantity of our output"},
    {word: "запит", translation: "query", guessed: false, example: "Please submit your query through the online form"},
    {word: "швидко", translation: "quickly", guessed: false, example: "Respond quickly to the customer's request"},
    {word: "нещодавно", translation: "recently", guessed: false, example: "Recently we visited a new museum"},
    {word: "отримувач", translation: "recipient", guessed: false, example: "The recipient of an award was surprised"},
    {word: "запис", translation: "record", guessed: false, example: "Please keep a record of all expenses"},
    {word: "посилання", translation: "reference", guessed: false, example: "He included a reference to the source"},
    {word: "відносно", translation: "regarding", guessed: false, example: "I have questions regarding your proposal"},
    {word: "реєстрація", translation: "registration", guessed: false, example: "Registration for the event is now open"},
    {word: "жаліти", translation: "regret", guessed: false, example: "I regret missing the concert"},
    {word: "відносини", translation: "relations", guessed: false, example: "Their relations improved over time"},
    {word: "надійний", translation: "reliable", guessed: false, example: "This car is very reliable for long trips"},
    {word: "нагадувати", translation: "remind", guessed: false, example: "Please remind me about the meeting"},
    {word: "віддалено", translation: "remote", guessed: false, example: "They work in a remote office location"},
    {word: "прибрати", translation: "remove", guessed: false, example: "Please remove your shoes at the door"},
    {word: "видалити", translation: "delete", guessed: false, example: "You can delete unnecessary files"},
    {word: "повторення", translation: "repetition", guessed: false, example: "Avoid repetition in your essay"},
    {word: "відтворюваність", translation: "replicability", guessed: false, example: "Replicability is key in scientific studies"},
    {word: "звіт", translation: "report", guessed: false, example: "The final report is due tomorrow"},
    {word: "доповідач", translation: "reporter", guessed: false, example: "A reporter covered the latest news"},
    {word: "обов'язкові", translation: "required", guessed: false, example: "Attendance is required for all students"},
    {word: "вимоги", translation: "requirement", guessed: false, example: "Meeting the requirement is essential"},
    {word: "повага", translation: "respect", guessed: false, example: "We should always show respect to others"},
    {word: "відповідь", translation: "response", guessed: false, example: "Her response was quick and clear"},
    {word: "запит", translation: "request", guessed: false, example: "He made a request for more information"},
    {word: "обов'язки", translation: "responsibilities", guessed: false, example: "She has many responsibilities at work"},
    {word: "відповідальність", translation: "responsibility", guessed: false, example: "Responsibility comes with the job"},
    {word: "підзвітний", translation: "accountable", guessed: false, example: "Managers are accountable for their teams"},
    {word: "залишок (чогось)", translation: "the rest of", guessed: false, example: "The rest of a cake was delicious"},
    {word: "роздріб", translation: "retail", guessed: false, example: "He works in the retail industry"},
    {word: "роздрібний продавець", translation: "retailer", guessed: false, example: "The retailer offered a discount"},
    {word: "заможний", translation: "rich", guessed: false, example: "She comes from a rich family"},
    {word: "безглуздий", translation: "ridiculous", guessed: false, example: "The idea was simply ridiculous"},
    {word: "права доступу", translation: "access rights", guessed: false, example: "You need proper access rights"},
    {word: "дозвіл", translation: "permission", guessed: false, example: "We need permission to enter"},
    {word: "правила", translation: "rules", guessed: false, example: "Follow the rules to succeed"},
    {word: "зарплата", translation: "salary", guessed: false, example: "His salary increased last year"},
    {word: "продажі", translation: "sales", guessed: false, example: "Sales have doubled this month"},
    {word: "той же", translation: "the same", guessed: false, example: "They wore the same outfits"},
    {word: "задоволення", translation: "satisfy", guessed: false, example: "The meal will satisfy everyone"},
    {word: "графік", translation: "schedule", guessed: false, example: "Check the schedule for updates"},
    {word: "одночасно", translation: "simultaneously", guessed: false, example: "They arrived simultaneously at the venue"},
    {word: "смуга прокрутки", translation: "scrollbar", guessed: false, example: "Use the scrollbar to navigate"},
    {word: "друга освіта", translation: "second education", guessed: false, example: "She is pursuing a second education"},
    {word: "дуже рідко", translation: "seldom", guessed: false, example: "He seldom visits the old town"},
    {word: "рідко", translation: "rarely", guessed: false, example: "She rarely eats out"},
    {word: "іноді", translation: "occasionally", guessed: false, example: "We occasionally go hiking"},
    {word: "саморозвиток", translation: "self-improvement", guessed: false, example: "Self-improvement is a lifelong journey"},
    {word: "самоорганізація", translation: "self-organization", guessed: false, example: "Self-organization is key to success"},
    {word: "сенс", translation: "sense", guessed: false, example: "He has a good sense of humor"},
    {word: "речення", translation: "sentence", guessed: false, example: "Write a clear and concise sentence"},
    {word: "роздільні", translation: "separate", guessed: false, example: "Keep your tasks separate for clarity"},
    {word: "послуги", translation: "services", guessed: false, example: "Our services include delivery and setup"},
    {word: "набір значень", translation: "set of values", guessed: false, example: "We share a common set of values"},
    {word: "налаштування", translation: "settings", guessed: false, example: "Adjust the settings to your preference"},
    {word: "серйозність", translation: "severity", guessed: false, example: "The severity of an issue was high"},
    {word: "гострий", translation: "sharp", guessed: false, example: "Be careful with that sharp knife"},
    {word: "підпис", translation: "signature", guessed: false, example: "Please add your signature here"},
    {word: "визначна мета", translation: "significant goal", guessed: false, example: "Achieving a significant goal is rewarding"},
    {word: "навики", translation: "skills", guessed: false, example: "She has excellent programming skills"},
    {word: "слайдер/повзунок", translation: "slider", guessed: false, example: "Adjust the volume with a slider"},
    {word: "розумний(набута якість)", translation: "smart", guessed: false, example: "Anna is smart because she solved the puzzle quickly"},
    {word: "кмітливий", translation: "clever", guessed: false, example: "Her clever solution impressed everyone"},
    {word: "інтелектуальний", translation: "intelligent", guessed: false, example: "She is an intelligent and capable leader"},
    {word: "суспільство", translation: "society", guessed: false, example: "We live in a diverse society"},
    {word: "програмне забезпечення", translation: "software", guessed: false, example: "The new software was installed yesterday"},
    {word: "твердий", translation: "solid", guessed: false, example: "The foundation is solid and stable"},
    {word: "розширення екрану", translation: "screen resolution", guessed: false, example: "Check your screen resolution settings"},
    {word: "конкретний", translation: "specific", guessed: false, example: "Please provide specific details"},
    {word: "технічні характеристики", translation: "specifications", guessed: false, example: "All specifications are in the manual"},
    {word: "персонал", translation: "staff", guessed: false, example: "The staff meeting is at 9 AM"},
    {word: "кроки по відтворенню", translation: "steps to reproduce", guessed: false, example: "Document the steps to reproduce an error"},
    {word: "потік даних", translation: "data stream", guessed: false, example: "The data stream was interrupted"},
    {word: "сильні сторони", translation: "strengths", guessed: false, example: "Focus on your strengths"},
    {word: "структура", translation: "structure", guessed: false, example: "The structure of a document is clear"},
    {word: "підлеглі", translation: "subordinates", guessed: false, example: "He manages several subordinates"},
    {word: "успіх", translation: "success", guessed: false, example: "Achieving success takes hard work"},
    {word: "підсумок", translation: "summary", guessed: false, example: "Write a summary of the report"},
    {word: "постачальник", translation: "supplier", guessed: false, example: "A supplier delivered the goods on time"},
    {word: "служба підтримки", translation: "support", guessed: false, example: "They offer excellent customer support"},
    {word: "вкладка", translation: "tab", guessed: false, example: "Click on the tab to switch views"},
    {word: "таблиця", translation: "table", guessed: false, example: "Create a table to organize the data"},
    {word: "решітка", translation: "grid", guessed: false, example: "Use a grid to align the elements"},
    {word: "завдання", translation: "task", guessed: false, example: "Complete a task by the end of this day"},
    {word: "команда", translation: "team", guessed: false, example: "The team works well together"},
    {word: "колеги", translation: "colleagues", guessed: false, example: "Her colleagues are supportive"},
    {word: "члени команди", translation: "teammates", guessed: false, example: "He trusts his teammates"},
    {word: "тимчасовий", translation: "temporary", guessed: false, example: "The position is temporary"},
    {word: "текстове поле", translation: "textbox", guessed: false, example: "Enter text in the textbox"},
    {word: "саме тому", translation: "therefore", guessed: false, example: "Therefore, we need to reconsider our approach"},
    {word: "хоча", translation: "though", guessed: false, example: "Though it was late, he continued working"},
    {word: "заголовок", translation: "title", guessed: false, example: "The title of a book is interesting"},
    {word: "верхня частина сайту", translation: "header", guessed: false, example: "Include a header on each page"},
    {word: "рідко", translation: "rarely", guessed: false, example: "She rarely visits her hometown"},
    {word: "безпека", translation: "safety", guessed: false, example: "Safety measures must be taken seriously"},
    {word: "відповідальний", translation: "responsible", guessed: false, example: "He is responsible for the team's success"},
    {word: "вспливаюча підказка", translation: "tooltip", guessed: false, example: "A tooltip appeared when I hovered over the icon"},
    {word: "підказка", translation: "hint", guessed: false, example: "Here's a hint to solve the puzzle"},
    {word: "грубий", translation: "tough", guessed: false, example: "The exam was tough but fair"},
    {word: "відслідковування", translation: "tracking", guessed: false, example: "Tracking the package is easy with this app"},
    {word: "тренуватись", translation: "train", guessed: false, example: "They will train the new employees next week"},
    {word: "транзакція", translation: "transaction", guessed: false, example: "Each transaction is recorded in the ledger"},
    {word: "лікування", translation: "treating", guessed: false, example: "Treating everyone with respect is important"},
    {word: "трігер", translation: "trigger", guessed: false, example: "A loud noise triggered the alarm"},
    {word: "тип", translation: "type", guessed: false, example: "What type of music do you like"},
    {word: "інтерфейс користувача", translation: "user interface", guessed: false, example: "The user interface is very intuitive"},
    {word: "незабутній", translation: "unforgettable", guessed: false, example: "The trip to Paris was unforgettable"},
    {word: "терміново", translation: "urgently", guessed: false, example: "The issue needs to be addressed urgently"},
    {word: "користувач", translation: "user", guessed: false, example: "A user reported a bug in the system"},
    {word: "відпустка", translation: "vacation", guessed: false, example: "They are going on vacation next month"},
    {word: "дійсні дані", translation: "valid data", guessed: false, example: "Ensure you enter valid data in the form"},
    {word: "що завгодно", translation: "whatever", guessed: false, example: "You can choose whatever you like"},
    {word: "недійсні дані", translation: "invalid data", guessed: false, example: "Invalid data will be rejected by the system"},
    {word: "цінні поради", translation: "valuable advices", guessed: false, example: "She gave me some valuable advice"},
    {word: "значення", translation: "value", guessed: false, example: "Understanding the value of time is crucial"},
    {word: "змінна", translation: "variable", guessed: false, example: "Define the variable in your code"},
    {word: "навпаки", translation: "vice versa", guessed: false, example: "Vice versa can also be true"},
    {word: "чекати", translation: "wait", guessed: false, example: "Please wait here for a moment"},
    {word: "слабкості", translation: "weaknesses", guessed: false, example: "Identifying weaknesses can help improve performance"},
    {word: "вебсайт", translation: "website", guessed: false, example: "The company launched a new website"},
    {word: "втручання", translation: "interference", guessed: false, example: "Interference from other devices can cause issues"},
    {word: "гурт", translation: "wholesale", guessed: false, example: "They buy products wholesale for better prices"},
    {word: "широкий досвід", translation: "wide experience", guessed: false, example: "She has wide experience in marketing"},
    {word: "вікно", translation: "window", guessed: false, example: "Open the window to let in some fresh air"},
    {word: "навантаження", translation: "workload", guessed: false, example: "The workload has been heavy this week"},
    {word: "хвилюватись", translation: "worry", guessed: false, example: "I worry about his health"},
    {word: "хибний", translation: "wrong", guessed: false, example: "The answer you gave is wrong"},
    {word: "графік", translation: "schedule", guessed: false, example: "Let's review the schedule for next week"},
    {word: "позаду", translation: "behind", guessed: false, example: "He is always behind in his work"},
    {word: "сформовані", translation: "formed", guessed: false, example: "The team has formed a strong bond"},
    {word: "нестача", translation: "lack", guessed: false, example: "There is a lack of resources for the project"},
    {word: "вага", translation: "weigh", guessed: false, example: "We need to weigh the pros and cons"},
    {word: "дозвіл", translation: "permission", guessed: false, example: "You need permission to access this area"},
    {word: "усвідомлення", translation: "awareness", guessed: false, example: "Awareness of the issue is growing"},
    {word: "відсутність", translation: "lack", guessed: false, example: "There is a lack of information on the subject"},
    {word: "бути в курсі/обізнаний", translation: "aware of", guessed: false, example: "Be aware of your surroundings"},
    {word: "скоріше", translation: "rather", guessed: false, example: "I'd rather stay home tonight"},
    {word: "прямий", translation: "straight", guessed: false, example: "Go straight down the road"},
    {word: "відсутній", translation: "absent", guessed: false, example: "He was absent from the meeting"},
    {word: "в наявності", translation: "available", guessed: false, example: "The file is available for download"},
    {word: "необхідний", translation: "necessary", guessed: false, example: "A valid ID is necessary for entry"},
    {word: "присутний", translation: "present", guessed: false, example: "He was present at the event"},
    {word: "достатній", translation: "sufficient", guessed: false, example: "We have sufficient evidence to proceed"},
    {word: "зайнятий в", translation: "engage in", guessed: false, example: "They engage in various community activities"},
    {word: "відразу", translation: "straight away", guessed: false, example: "Please start the task straight away"},
    {word: "очевидно", translation: "obviously", guessed: false, example: "Obviously, we need to address this problem"},
    {word: "сприйняття", translation: "perception", guessed: false, example: "Perception is key in understanding others"},
    {word: "актуальним", translation: "relevant", guessed: false, example: "The information must be relevant to a topic"},
    {word: "безумовно", translation: "definitely", guessed: false, example: "I will definitely attend the meeting"},
    {word: "злегка", translation: "slightly", guessed: false, example: "The water was slightly cold"},
    {word: "причиною", translation: "cause", guessed: false, example: "The storm caused a lot of damage"},
    {word: "раптово", translation: "suddenly", guessed: false, example: "He left suddenly without saying goodbye"},
    {word: "підозріло", translation: "suspiciously", guessed: false, example: "She looked at him suspiciously"},
    {word: "певний", translation: "certain", guessed: false, example: "I am certain that we can succeed"},
    {word: "розбірна", translation: "collapsible", guessed: false, example: "The table is collapsible for easy storage"},
    {word: "відповідно", translation: "in accordance", guessed: false, example: "Everything was done in accordance with the rules"},
    {word: "забагато", translation: "too much", guessed: false, example: "You put too much sugar in the tea"},
    {word: "також", translation: "also", guessed: false, example: "He also likes to read"},
    {word: "далеко", translation: "farther", guessed: false, example: "The store is farther than I thought"},
    {word: "більше", translation: "more", guessed: false, example: "I need more information to make a decision"},
    {word: "однак", translation: "however", guessed: false, example: "The plan sounds good however there are some risks"},
    {word: "більше того", translation: "moreover", guessed: false, example: "Moreover, we should consider the budget"},
    {word: "зараз", translation: "for now", guessed: false, example: "For now, let's focus on the current task"},
    {word: "так", translation: "so", guessed: false, example: "So, what do you think about the proposal"},
    {word: "у будь-якому випадку", translation: "anyway", guessed: false, example: "Anyway, we should get started"},
    {word: "попри", translation: "in spite of", guessed: false, example: "In spite of the rain we went hiking"},
    {word: "факт", translation: "fact", guessed: false, example: "The fact is that we need more time"},
    {word: "поки", translation: "while", guessed: false, example: "While he was working, she was reading"},
    {word: "хоча", translation: "though", guessed: false, example: "He said he was tired, though he kept working"},
    {word: "ще", translation: "still", guessed: false, example: "It's still raining outside"},
    {word: "правильно", translation: "properly", guessed: false, example: "Make sure the system is working properly"},
    {word: "увесь", translation: "entire", guessed: false, example: "We spent the entire day at a beach"},
    {word: "конкретно", translation: "particular", guessed: false, example: "He has a particular interest in history"},
    {word: "орієнтовний", translation: "tentative", guessed: false, example: "The plans are still tentative"},
    {word: "справедливо", translation: "fairly", guessed: false, example: "She is fairly certain about her decision"},
    {word: "натхнений", translation: "inspired", guessed: false, example: "The movie inspired me to travel"},
    {word: "відданий", translation: "committed", guessed: false, example: "He is committed to his work"},
    {word: "знайомий", translation: "familiar", guessed: false, example: "She is familiar with the software"},
    {word: "повторюючий", translation: "recurring", guessed: false, example: "This is a recurring problem in our system"},
    {word: "пов'язані", translation: "related", guessed: false, example: "These issues are related to each other"},
    {word: "важливий етап", translation: "milestone", guessed: false, example: "The project reached a milestone when the prototype was completed"},
    {word: "кінцевий термін", translation: "deadline", guessed: false, example: "Missing the deadline could delay the entire project"},
    {word: "дорожня карта", translation: "roadmap", guessed: false, example: "The roadmap outlines the features we plan to release this year"},
    {word: "кінцевий результат", translation: "deliverable", guessed: false, example: "The main deliverables include a mobile app and a website"},
    {word: "спринт", translation: "sprint", guessed: false, example: "We are focusing on the core functionalities in this sprint"},
    {word: "обсяг проєкту", translation: "scope", guessed: false, example: "Scope creep can cause project delays and budget issues"},
    {word: "список завдань", translation: "backlog", guessed: false, example: "The backlog is reviewed every week to prioritize tasks"},
    {word: "менеджер проєкту", translation: "project manager", guessed: false, example: "The project manager is coordinating with all departments to ensure smooth execution"},
    {word: "зацікавлена сторона", translation: "stakeholder", guessed: false, example: "Regular updates are provided to stakeholders to keep them informed"},
    {word: "власник продукту", translation: "product owner", guessed: false, example: "The product owner decides which features are the most important"},
    {word: "член команди", translation: "team member", guessed: false, example: "Each team member has specific responsibilities to meet the project goals"},
    {word: "спонсор", translation: "sponsor", guessed: false, example: "The project sponsor is committed to supporting the project financially"},
    {word: "гнучка методологія", translation: "agile", guessed: false, example: "We follow Agile practices to adapt quickly to changes"},
    {word: "щоденна зустріч", translation: "daily standup", guessed: false, example: "The daily standup helps keep everyone on the same page"},
    {word: "ретроспектива", translation: "retrospective", guessed: false, example: "Retrospectives help us continuously improve our processes"},
    {word: "розподіл ресурсів", translation: "resource allocation", guessed: false, example: "Resource allocation is a key part of project planning"},
    {word: "графік", translation: "timeline", guessed: false, example: "The timeline for the project includes both major milestones and deadlines"},
    {word: "бюджет", translation: "budget", guessed: false, example: "Staying within budget is one of the project’s success criteria"},
    {word: "оцінка", translation: "estimation", guessed: false, example: "Accurate estimation helps us set realistic deadlines"},
    {word: "пріоритезація", translation: "prioritization", guessed: false, example: "Task prioritization helps the team focus on critical issues first"},
    {word: "оцінка ризиків", translation: "risk assessment", guessed: false, example: "Risk assessment is essential before we begin any new phase"},
    {word: "залежності", translation: "dependencies", guessed: false, example: "We need to complete Task A before moving to Task B due to dependencies"},
    {word: "оновлення статусу", translation: "status update", guessed: false, example: "Weekly status updates keep the team aligned"},
    {word: "відстеження проблем", translation: "issue tracking", guessed: false, example: "An effective issue tracking system helps manage project challenges"},
    {word: "запит на зміну", translation: "change request", guessed: false, example: "The client submitted a change request for additional features"},
    {word: "почати зустріч", translation: "start the meeting", guessed: false, example: "Let's start the meeting and go over today's agenda"},
    {word: "порядок денний", translation: "agenda", guessed: false, example: "The agenda for today includes project updates and upcoming deadlines"},
    {word: "взяти слово", translation: "take the floor", guessed: false, example: "If anyone has any questions, please feel free to take the floor"},
    {word: "передати слово", translation: "pass the floor", guessed: false, example: "I'll pass the floor to our team lead for an update"},
    {word: "віддалений", translation: "remote", guessed: false, example: "Many team members are working remote"},
    {word: "учасник", translation: "participant", guessed: false, example: "We have all the participants in the call, so let's begin"},
    {word: "демонстрація екрана", translation: "screen sharing", guessed: false, example: "I'll start screen sharing to go over the project details"},
    {word: "приглушити мікрофон", translation: "mute the microphone", guessed: false, example: "Please mute your microphone if you're not speaking"},
    {word: "затримка звуку", translation: "audio delay", guessed: false, example: "There seems to be an audio delay, could you repeat that?"},
    {word: "поганий зв’язок", translation: "poor connection", guessed: false, example: "We are experiencing a poor connection"},
    {word: "очікувати на приєднання", translation: "waiting to join", guessed: false, example: "We’re waiting for a few more people to join"},
    {word: "запис зустрічі", translation: "meeting recording", guessed: false, example: "We'll share the meeting recording afterward for those who couldn’t attend"},
    {word: "перевірка звуку", translation: "sound check", guessed: false, example: "Can everyone hear me? Let's do a quick sound check"},
    {word: "очікувати", translation: "hold on", guessed: false, example: "Hold on a moment while I pull up the document"},
    {word: "попередження", translation: "heads-up", guessed: false, example: "Just a heads-up: the deadline has been moved up by one week"},
    {word: "узгодити", translation: "align", guessed: false, example: "We need to align the project goals"},
    {word: "узагальнити/підвести підсумок", translation: "wrap up", guessed: false, example: "Let’s wrap up the meeting with a quick summary"},
    {word: "підвести підсумок", translation: "summarize", guessed: false, example: "Could someone summarize the main points of today’s discussion?"},
    {word: "обговорити пізніше", translation: "take it offline", guessed: false, example: "Lets take it offline and follow up later"},
    {word: "забронювати", translation: "book", guessed: false, example: "Please book time with me if you have any questions"},
    {word: "бути в курсі", translation: "keep in the loop", guessed: false, example: "Please keep me in the loop on any updates"},
    {word: "опитування", translation: "poll", guessed: false, example: "Take a quick poll to share your opinion"},
    {word: "бути на одній хвилі", translation: "be on the same page", guessed: false, example: "We need to be on the same page regarding our priorities"},
    {word: "питання", translation: "question", guessed: false, example: "Does anyone have any questions about the new changes?"},
    {word: "завершити зустріч", translation: "end the meeting", guessed: false, example: "If there are no more questions, let's end the meeting here"},
    {word: "вимкнути камеру", translation: "turn off camera", guessed: false, example: "If you’re experiencing connection issues, try turning off your camera"},
    {word: "план на майбутнє", translation: "next steps", guessed: false, example: "Before we finish, let's go over the next steps"},
    {word: "внести правки", translation: "make adjustments", guessed: false, example: "We’ll make adjustments to the plan based on today's feedback"},
    {word: "спільний документ", translation: "shared document", guessed: false, example: "I've attached a shared document for everyone to review"},
    {word: "вирішення проблем", translation: "problem solving", guessed: false, example: "Let’s dedicate some time to problem solving if issues arise"},
    {word: "розклад зустрічей", translation: "meeting schedule", guessed: false, example: "I’ll send out the meeting schedule for the month"},
    {word: "спільний екран", translation: "shared screen", guessed: false, example: "Could you share your screen so we can see the presentation?"},
    {word: "приєднатися до виклику", translation: "join the call", guessed: false, example: "Please join the call promptly at the scheduled time"},
    {word: "вихід із зустрічі", translation: "leave the meeting", guessed: false, example: "You can leave the meeting if you have no further questions"}
];
